### DISCUSSION TITLE
list cache

### DISCUSSION THREAD

**Discussion by a1exhedb** [serverpod/serverpod#1166] [Q&A] [answered]
Is it possible to cache a list of SerializableEntity objects somehow?
The idea is to loop the set cache function or how would you cache a list of categories?
Thanks!

**Comment by vlidholt** [comment, marked as answer]
You can currently only cache serializable entities. However, you can easily create an extra class that holds the list of your entities.

```yaml
class: MyCachableList
fields:
  entities: List<MyCachableEntity>
```
