### DISCUSSION TITLE
Type 'Null' is not a subtype of type 'String' Error

### DISCUSSION THREAD

**Discussion by MrFahrenheit-55** [serverpod/serverpod#1701] [Q&A]
Good day everyone. 

I am having some issues when using the Serverpod-generated endpoints. 

I am getting the following error:

```log
METHOD CALL: model.loadFinancialModel duration: 5ms numQueries: 0 authenticatedUser: null
type 'Null' is not a subtype of type 'String'
#0      SerializationManager.deserialize (package:serverpod_serialization/src/serialization.dart:59:14)
#1      Protocol.deserialize (package:finmodel_server/src/generated/protocol.dart:296:18)
#2      new FinancialModel.fromJson (package:finmodel_server/src/generated/financialmodel.dart:31:12)
#3      Protocol.deserialize (package:finmodel_server/src/generated/protocol.dart:245:33)
#4      DatabaseConnection._formatTableRow (package:serverpod/src/database/database_connection.dart:239:45)
#5      DatabaseConnection.find (package:serverpod/src/database/database_connection.dart:178:18)
<asynchronous suspension>
#6      Database.find (package:serverpod/src/database/database.dart:60:12)
<asynchronous suspension>
#7      ModelEndpoint.loadFinancialModel (package:finmodel_server/src/endpoints/model_endpoint.dart:37:12)
<asynchronous suspension>
#8      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:111:20)
<asynchronous suspension>
#9      Server._handleRequest (package:serverpod/src/server/server.dart:243:18)
<asynchronous suspension>
```

My Yaml file looks as follows:

```yaml
class: FinancialModel
table: financial_model
fields:
  model: String
  start: String
  scenario: String, api
  length: String, api

```

The endpoint code is: 

```dart
import 'package:serverpod/serverpod.dart';

import '../generated/protocol.dart';

class ModelEndpoint extends Endpoint {
  Future<List<FinancialModel>> loadFinancialModel(Session session) async {
    return await FinancialModel.find(session);
  }
}

```

If anyone can please assist with this, it would be really helpful.

Thanks in advance.

**Comment by MrFahrenheit-55** [comment]
I forgot to make the .yaml file api fields nullable.

```yaml
class: FinancialModel
table: financial_model
fields:
  model: String
  start: String
  scenario: String?, api
  length: String?, api
```
