### DISCUSSION TITLE
Model Relations - foreign key field

### DISCUSSION THREAD

**Discussion by MrFahrenheit-55** [serverpod/serverpod#1790] [Q&A] [answered]
Good evening.

If I have a model specified as:

```yaml

class: SomeModel
table: some_model
fields:
  modelUuid: UuidValue
  modelName: String
```

and I have another model specified as:

```yaml

class: SomeModelParameters
table: some_model_params
fields:
  modelUuid: UuidValue 
  modelParameterName: String
```

Can I have a relation setup between the model and the modelParameters using the Uuid field? 

For example, I believe the model parameters should then be specified as:

```yaml

class: SomeModelParameters
table: some_model_params
fields:
  modelUuid: UuidValue
  parameterUuid: UuidValue
  model: SomeModel? relation(field=modelUuid)
  modelParameterName: String
```

Is this possible or will the relation ID always be Int? I want to use cascade delete if a model is deleted. This is because the server generates a UUID for the model to have minimal read-write operations in the database. The user can add and remove parameters all in-app memory without unnecessary reads/writes to the DB. The model is automatically saved every 5 min to the db or when the user chooses to save the model.
