### DISCUSSION TITLE
Breaking changes in 0.9.8

### DISCUSSION THREAD

**Discussion by vlidholt** [serverpod/serverpod#182] [Announcements]
Version 0.9.8 brings a slightly new format for the configuration files. If you upgrade from an earlier version, you will need to update your configuration to match the new format, or Serverpod will crash when starting.

Affected files are `config/development.yaml`, `config/staging.yaml`, and `config/production.yaml`

This is an example of the new format:

```yaml
# This is the configuration file for your production environment.
# Typically, you will want to route the traffic through a load balancer
# which adds SSL security through https. If you use Serverpod's standard
# Terraform scripts to deploy your server, all you need to change in
# this file is the examplepod.com domain name.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: api.examplepod.com
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: insights.examplepod.com
  publicPort: 443
  publicScheme: https

# This is the database setup for your servers.
database:
  host: database.examplepod.com
  port: 5432
  name: serverpod
  user: postgres

# This is the setup for Redis.
redis:
  enabled: false
  host: redis.examplepod.com
  port: 6379
```
