### DISCUSSION TITLE
migration failed

### DISCUSSION THREAD

**Discussion by sulthanalihsan** [serverpod/serverpod#1830] [Q&A] [answered]
I often encounter schema examples in the documentation like this:

implicit one-to-many relationship

company.yaml
```
class: Company
table: company
fields:
  name: String
  employees: List<Employee>, relation
```

employee.yaml
```
class: Employee
table: employee
fields:
  name: String
```
  
However, I'm curious why when I tried it, an error occurred: 
`Fields with model relations must be nullable (e.g., employees:List<Employee>?)`
