### DISCUSSION TITLE
Breaking changes in 0.9.9

### DISCUSSION THREAD

**Discussion by vlidholt** [serverpod/serverpod#190] [Announcements]
`serverId` has changed from `int` to `String`/`text` to better support AWS EC2 instance IDs. It affects the following database tables:
`serverpod_future_call`.

The following tables have been modified and it's recommended to delete the old tables and recreate them with the following code:

```sql
--
-- Class SessionLogEntry as table serverpod_session_log
--

CREATE TABLE serverpod_session_log (
  "id" serial,
  "serverId" text NOT NULL,
  "time" timestamp without time zone NOT NULL,
  "module" text,
  "endpoint" text,
  "method" text,
  "duration" double precision,
  "numQueries" integer,
  "slow" boolean,
  "error" text,
  "stackTrace" text,
  "authenticatedUserId" integer,
  "isOpen" boolean,
  "touched" timestamp without time zone NOT NULL
);

ALTER TABLE ONLY serverpod_session_log
  ADD CONSTRAINT serverpod_session_log_pkey PRIMARY KEY (id);

CREATE INDEX serverpod_session_log_serverid_idx ON serverpod_session_log USING btree ("serverId");
CREATE INDEX serverpod_session_log_touched_idx ON serverpod_session_log USING btree ("touched");
CREATE INDEX serverpod_session_log_isopen_idx ON serverpod_session_log USING btree ("isOpen");


--
-- Class QueryLogEntry as table serverpod_query_log
--

CREATE TABLE serverpod_query_log (
  "id" serial,
  "serverId" text NOT NULL,
  "sessionLogId" integer NOT NULL,
  "messageId" integer,
  "query" text NOT NULL,
  "duration" double precision NOT NULL,
  "numRows" integer,
  "error" text,
  "stackTrace" text,
  "slow" boolean NOT NULL,
  "order" integer NOT NULL
);

ALTER TABLE ONLY serverpod_query_log
  ADD CONSTRAINT serverpod_query_log_pkey PRIMARY KEY (id);

CREATE INDEX serverpod_query_log_sessionLogId_idx ON serverpod_query_log USING btree ("sessionLogId");

ALTER TABLE ONLY serverpod_query_log
  ADD CONSTRAINT serverpod_query_log_fk
    FOREIGN KEY("sessionLogId")
      REFERENCES serverpod_session_log(id)
        ON DELETE CASCADE;

--
-- Class MessageLogEntry as table serverpod_message_log
--

CREATE TABLE serverpod_message_log (
  "id" serial,
  "sessionLogId" integer NOT NULL,
  "serverId" text NOT NULL,
  "messageId" integer NOT NULL,
  "endpoint" text NOT NULL,
  "messageName" text NOT NULL,
  "duration" double precision NOT NULL,
  "error" text,
  "stackTrace" text,
  "slow" boolean NOT NULL,
  "order" integer NOT NULL
);

ALTER TABLE ONLY serverpod_message_log
  ADD CONSTRAINT serverpod_message_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY serverpod_message_log
  ADD CONSTRAINT serverpod_message_log_fk
    FOREIGN KEY("sessionLogId")
      REFERENCES serverpod_session_log(id)
        ON DELETE CASCADE;

--
-- Class LogEntry as table serverpod_log
--

CREATE TABLE serverpod_log (
  "id" serial,
  "sessionLogId" integer NOT NULL,
  "messageId" integer,
  "reference" text,
  "serverId" text NOT NULL,
  "time" timestamp without time zone NOT NULL,
  "logLevel" integer NOT NULL,
  "message" text NOT NULL,
  "error" text,
  "stackTrace" text,
  "order" integer NOT NULL
);

ALTER TABLE ONLY serverpod_log
  ADD CONSTRAINT serverpod_log_pkey PRIMARY KEY (id);

CREATE INDEX serverpod_log_sessionLogId_idx ON serverpod_log USING btree ("sessionLogId");

ALTER TABLE ONLY serverpod_log
  ADD CONSTRAINT serverpod_log_fk
    FOREIGN KEY("sessionLogId")
      REFERENCES serverpod_session_log(id)
        ON DELETE CASCADE;
```

In addition, two new tables have been added:

```sql
--
-- Class ServerHealthConnectionInfo as table serverpod_health_connection_info
--

CREATE TABLE serverpod_health_connection_info (
  "id" serial,
  "serverId" text NOT NULL,
  "type" integer NOT NULL,
  "timestamp" timestamp without time zone NOT NULL,
  "active" integer NOT NULL,
  "closing" integer NOT NULL,
  "idle" integer NOT NULL
);

ALTER TABLE ONLY serverpod_health_connection_info
  ADD CONSTRAINT serverpod_health_connection_info_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX serverpod_health_connection_info_timestamp_idx ON serverpod_health_connection_info USING btree ("timestamp", "serverId", "type");


--
-- Class ServerHealthMetric as table serverpod_health_metric
--

CREATE TABLE serverpod_health_metric (
  "id" serial,
  "name" text NOT NULL,
  "serverId" text NOT NULL,
  "timestamp" timestamp without time zone NOT NULL,
  "isHealthy" boolean NOT NULL,
  "value" double precision NOT NULL
);

ALTER TABLE ONLY serverpod_health_metric
  ADD CONSTRAINT serverpod_health_metric_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX serverpod_health_metric_timestamp_idx ON serverpod_health_metric USING btree ("timestamp", "serverId", "name");
```

Finally, there has been a change to the configuration file format. The easiest way to update the files may be to create a new project with the same name as the current project and copy the contents of `config/development.yaml`, `config/staging.yaml`, and `config/production.yaml` from there. The new project also comes with a new set of AWS Terraform files which contain bug fixes and adds support for the new web server.

This is an example of the new configuration file format:

```yaml
# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.
#
# When running your server locally, the server ports are the same as the public
# facing ports.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http

# This is the database setup for your server.
database:
  host: localhost
  port: 8090
  name: projectname
  user: postgres

# This is the setup for Redis.
redis:
  enabled: false
  host: localhost
  port: 8091
```
