### DISCUSSION TITLE
Right way to create One2Many objects

### DISCUSSION THREAD

**Discussion by bubalopetar** [serverpod/serverpod#2009] [Q&A] [answered]
Hello, I was looking through the Serverpod documentation and have done some testing but haven't found out how to handle the creation of objects in One2Many implicitly defined relations like this one:
```
class: Company
table: company
fields:
  name: String
  employees: List<Employee>?, relation

class: Employee
table: employee
fields:
  name: String

```
If users creates a new Company object  like this one:
```
Company(
    name: 'SomeCompany',
    employees: [
        Employee("John"),
        Employee("Matt"),
    ]
);
```

Now on the server side, there would be some endpoint with a create method that would write new company and its employees to DB:
```
Future<Company> create(Session session, Company company) async {
    Company.db.insertRow(session, company);
}
```
Since this function would only create a company, the question is how to save the employees. Is there a possibility of creating them automatically when creating a company or they should be created separately?
If they should be created separately how to do it since the companyID field in the employee class can't be accessible through the constructor. 
Or maybe declaring explicit relations and having separate endpoints and methods for creating both company and employee is a better practice for this use case?
