### DISCUSSION TITLE
List object relation not being saved automatically

### DISCUSSION THREAD

**Discussion by itsJoKr** [serverpod/serverpod#2033] [Q&A] [answered]
**Describe the bug**
I have one-to-many relation, one `CustomConfig` having many `CustomFieldConfig`:

```yaml
class: CustomConfig
table: custom_config
fields:
    useRestock: bool
    useLots: bool
    useDecimals: bool
    customFields: List<CustomFieldConfig>?, relation
```

```yaml
class: CustomFieldConfig
table: custom_field_config
fields:
    entity: int
    name: String
    required: bool
    options: List<String>?
    type: CustomFieldType
    
```

**To Reproduce**
1. Insert a `CustomConfig` with `List<CustomFieldConfig>` populated

**Expected behavior**
I expected that when saving `CustomConfig` it will auto-save the one-to-many relation for `CustomFieldConfig`. But it's not doing that. Am I supposed to manually manage that? I'm so confused because the docs imply that it's automatically managed for me.

**Screenshots**
- Here's proof that I'm sending non-empty List<CustomFieldConfig>

<img width="994" alt="Screenshot 2024-03-20 at 22 40 25" src="https://github.com/serverpod/serverpod/assets/11093480/d2ca21b5-e119-41af-9a88-504461dcd851">

- Here's screenshot showing that items are null, and in fact there are no rows in the table at all
<img width="1210" alt="Screenshot 2024-03-20 at 22 44 46" src="https://github.com/serverpod/serverpod/assets/11093480/409a938d-d625-43d0-a35c-d9dcbe989f14">

**Serverpod versions**
 -  _CLI Version:_ 1.2.5
 - _Library version:_ 1.2.5

**Platform information**
Running on Macbook Pro M1

**Comment by SandPod** [comment, marked as answer]
Hey @itsJoKr!

Unfortunately we don't support saving related data in a single query yet. Attaching or detaching related data requires a separate request to the database. You can read more about these operations here: https://docs.serverpod.dev/concepts/database/relation-queries#update

We have an issue tracking that feature here: https://github.com/serverpod/serverpod/issues/1343


> I'm so confused because the docs imply that it's automatically managed for me.

It's not good that we give indications that this is handles automatically. Could you give us a pointer to where in the docs we gave this impressions so that we can clarify it?

**Reply by itsJoKr** [reply]
@SandPod Thank your for the quick answer.

It was never directly mentioned in the docs, so it could be that only I misunderstood this. There's this part:
```
By directly specifying the Address type in the User class, Serverpod can automatically handle the relation for you.
```

And other ORMs like Hibernate work this way, so I just expected this would work out of the box.

**Reply by SandPod** [reply]
Makes totalt sense, that would be the most intuitive way the API would operate.

Thanks for the feedback on the documentation 👍

**Reply by itsJoKr** [reply]
@SandPod I would appreciate if you could answer me how do I save manually one-to-many? 

I'm trying to do it but I don't see any example on how to do it. I though I either need to use setter or attach method, but it doesn't look like it's one of those:
```dart
  Future<void> saveConfig(Session session, CustomConfig config) async {
    final savedConfig = await CustomConfig.db.insertRow(session, config);

    if (config.customFields != null) {
      for (final customField in config.customFields!) {
        config.customFields[0]._customConfigCustomfieldsCustomConfigId = savedConfig.id; // There's not setter for this foreign key
        
        // There's no attachRow method for CustomConfig or CustomFieldConfig
      }
    }
  }
```

**Reply by SandPod** [reply]
The attach methods are going to be defined on the side that you have defined the object relation.

Using your custom config definition as base:

```yaml
class: CustomConfig
table: custom_config
fields:
    useRestock: bool
    useLots: bool
    useDecimals: bool
    customFields: List<CustomFieldConfig>?, relation
```

There are two methods generated depending on if you want to attach a single or multiple objects.
- For a single object you can use `CustomConfig.db.attachRow.customFields(session, ...)`.
- For many objects you can use `CustomConfig.db.attach.customFields(session, ...)`.

Here are some tests that attach multiple rows to an entry:
https://github.com/serverpod/serverpod/blob/db5df4b21b06bf9ef34af5fcaf216906027ec307/tests/serverpod_test_server/test_integration/database_operations/entity_relations/nested_one_to_many/count/where_any_test.dart#L22-L43
