### DISCUSSION TITLE
Converting object to an encodable object failed

### DISCUSSION THREAD

**Discussion by baudee** [serverpod/serverpod#2072] [Q&A] [answered]
I get an error when I am trying to fetch one of my models. I don't know why and how to resolve. It could be a pleasure if someone could help me.

Here are my models:

```yaml
class: Category
table: category
serverOnly: true
fields:
  path: String
  isLeaf: bool
  trSizeTypes: List<TrCategorySizeType>?, relation(name=category_size_type)
  isAvailable: bool
indexes:
  category_path_idx:
    fields: path
    unique: true

```

```yaml
class: SizeType
table: size_type
serverOnly: true
fields:
  name: String
  sizes: List<Size>?, relation(optional)
  categories: List<TrCategorySizeType>?, relation(optional, name=size_type_category)
  isAvailable: bool
indexes:
  size_category_name_idx:
    fields: name
    unique: true
```

```yaml
class: Size
table: size
fields:
  name: String
  isAvailable: bool
```

The code that makes the error:
```dart
  Future<List<Size>> findAllByCategoryPath(Session session, String path) async {
    final categoryWithInclude = await Category.db.findFirstRow( // get the error here
      session,
      where: (c) => c.path.equals(path) & c.isAvailable,
      include: Category.include(
        trSizeTypes: TrCategorySizeType.includeList(
          include: TrCategorySizeType.include(sizeType: SizeType.include(sizes: Size.includeList())),
        ),
      ),
    );
    if (categoryWithInclude == null) {
      return [];
    }
    return categoryWithInclude.trSizeTypes!.expand((type) => type.sizeType!.sizes!).toList();
  }
```

The error:
```
Converting object to an encodable object failed: Instance of 'ColumnBool'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:793:7)
#1      _JsonStringStringifier.printOn (dart:convert/json.dart:982:17)
#2      _JsonStringStringifier.stringify (dart:convert/json.dart:967:5)
#3      JsonEncoder.convert (dart:convert/json.dart:345:30)
#4      SerializationManager.encode (package:serverpod_serialization/src/serialization.dart:175:7)
#5      ValueEncoder.convert (package:serverpod/src/database/value_encoder.dart:43:49)
#6      EscapedExpression.toString (package:serverpod/src/database/expressions.dart:72:40)
#7      _resolveWhereQuery (package:serverpod/src/database/database_query.dart:655:24)
#8      _resolveWhereQuery.<anonymous closure> (package:serverpod/src/database/database_query.dart:621:21)
#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#10     ListIterable.join (dart:_internal/iterable.dart:156:22)
#11     _resolveWhereQuery (package:serverpod/src/database/database_query.dart:622:10)
#12     _buildWhereQuery (package:serverpod/src/database/database_query.dart:585:19)
#13     SelectQueryBuilder.build (package:serverpod/src/database/database_query.dart:83:17)
#14     DatabaseConnection.find (package:serverpod/src/database/database_connection.dart:68:10)
#15     DatabaseConnection.findFirstRow (package:serverpod/src/database/database_connection.dart:92:22)
#16     Database.findFirstRow (package:serverpod/src/database/database.dart:62:38)
#17     CategoryRepository.findFirstRow (package:unique_server/src/generated/models/articles/category/category.dart:473:27)
...
```

Do I do something wrong with my yaml files or the `includes` ?
