### DISCUSSION TITLE
base response

### DISCUSSION THREAD

**Discussion by alalawy** [serverpod/serverpod#2081] [Q&A]
hi, i want to know how to create a BaseResponse so my api response not like :

`[
  {
     "key": "value"
  }
]`

but i want it have base response maybe like like :

`{
"data": [
  {
     "key": "value"
  }
],
"status": "success",
"pagination": {
      "page": 1
      "total": 10
    }
}`

**Comment by zhaiyong4118** [comment]
i have same question, anybody can help?
I tried to define BaseResponse<T> like BaseRespone<User>, but deserialization failed

**Comment by marcelomendoncasoares** [comment]
Unfortunately, Serverpod's serialization system doesn't currently support generic wrapper types with dynamic data fields like `BaseResponse<T>` or `List<dynamic>`. Through models, it is possible to do it by creating individual response types, like:

```yaml
# protocol/user_list_response.yaml
class: UserListResponse
fields:
  data: List<User>
  status: String
  pagination: PaginationInfo?, nullable
```

Or you can try to [use a middleware to intercept](https://docs.serverpod.dev/concepts/webserver/middleware) the responses at the HTTP layer, though this goes outside Serverpod's serialization and might not be straightforward to add custom data.
