### DISCUSSION TITLE
"Default" Value for Models

### DISCUSSION THREAD

**Discussion by Johannes-Schiel** [serverpod/serverpod#2098] [Q&A] [answered]
Hello, i am new to the hole Flutter/Dart/Serverpod Ecosystem and my question is, if there is any solution to define a default "value" for a new column in the model. So when i do something like this:

```
class: ToDo
table: todo
fields:
    label: String
```

and change the model later to something like this:

```
class: ToDo
table: todo
fields:
    label: String
    status: bool
```

that every ToDo currently in the database gets to false for example.
