### DISCUSSION TITLE
How do I generate passwords.yaml again?

### DISCUSSION THREAD

**Discussion by kaljitism** [serverpod/serverpod#2108] [Q&A] [answered]
I was on a windows cleaning spree and since all my projects are backed up on Github, I deleted the local files. I don't have passwords.yaml file which is giving me this error 

`Failed to load passwords. Serverpod cannot not start.` when I try to start the server using `dart .\bin\main.dart --apply-migrations` in server directory. How do I generate it again or would I need to manually create it?

**Comment by NeroSong** [comment, marked as answer]
Ran into the same thing, and attempts to recreate one failed 😅 I ended up creating a new project and use its `passwords.yaml`.

Just copy and update the `development` section with the relevant parameters from the `docker-compose.yaml` file. 


```yaml
# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'ZvFEWyrI3OGkEj15RNRAbPAtRN9Bdlcu'
  redis: 'ughEyj-wJeucmQlB6TKtWLUHLKViS3cV'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'QI_M7QsUHbEolL8OenSvlV0gBrHh-QNO'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'use_new_safe_created_password'
  serviceSecret: 'use_new_safe_created_password-5G3WKCtl'

# Passwords used in production mode.
production:
  database: 'use_new_safe_created_password'
  serviceSecret: 'ew9-use_new_safe_created_password'

```

Hope this helps someone who is experiencing the same situation.
