### DISCUSSION TITLE
Modelling Many-To-Many relationships with the current code generator

### DISCUSSION THREAD

**Discussion by mindreframer** [serverpod/serverpod#223] [Q&A] [answered]
Hey @vlidholt, 

what would be the best way to model a many-to-many relation, like post and tags? 

```yaml
class: Post
table: posts
fields:
  tags: List<Tags>

--- 
class: Tag
table: tags
fields:
  posts: List<Post>
```

generates 2 tables with **embedded** objects. Is it possible to model relations with `DB JOIN`s?

**Comment by vlidholt** [comment, marked as answer]
Serverpod doesn't yet automatically support database joins (this is a planned future feature). However, the current recommended pattern is to mark the fields as `api` only. That prevents a field from being stored in the database.

E.g.
```yaml
class: Post
table: posts
fields:
  tags: List<Tag>?, api
```

After you pull your post from the database you make a second request where you pull the tags and assign them to your post object. You can now pass the post object to your client.
