### DISCUSSION TITLE
Getting relationships right in ServerPod

### DISCUSSION THREAD

**Discussion by CordMemescape** [serverpod/serverpod#2252] [Q&A]
Hi all,

I have read the ServerPod documentation and have a reasonably good SQL background. However, I am struggling to determine how to represent the following relationships. I have several contrived models, such as ThingA, ThingB, and ThingC. I would like to track activity in another model called Transaction. The abbreviated YAML files look like this:

```yaml
# thinga.yaml
class: ThingA
table: thinga
fields:
  name: String
  description: String?
  knowsAbout: String
  addedAt: DateTime
```

```yaml
# thingb.yaml
class: ThingB
table: thingb
fields:
  name: String
  description: String?
  hasNodes: boolean?
  addedAt: DateTime
```

```yaml
# thingc.yaml
class: ThingC
table: thingc
fields:
  name: String
  description: String?
  length: integer?
  width: integer?
  addedAt: DateTime
```

The Transaction model must be a single model and table that references all three Things above. We don't know which Thing needs to be recorded in the table until something happens. So the Transaction model might look something like this:

```yaml
# transaction.yaml
class: Transaction
table: transaction
fields:
  timestamp: DateTime
  thing: ????????      # <-- this is the relationship bit I can't figure out. It could be a ThingA, a ThingB or a ThingC
  note: String?
  canDelete: boolean?
  modifiedAt: DateTime?
```

Does anyone have any thoughts how I might achieve this? I don't really want to have a ThingsATransactions, ThingsCTransactions and a ThingsCTransactions.

Thanks in advance!

**Comment by Isakdl** [comment]
What are you trying to achieve?

I would say that in general if you have several tables like this you either have to add a relation per thing you want to link in the `transaction` table. Alternatively, reverse the dependency so that the thing points to the transaction instead of the other way around. But to fully understand what a good solution is for your use-case I would need to understand the problem you want to solve.

Dart does not support union types so it will not be possible to have completely different classes represented by the same field.

**Comment by CordMemescape** [comment]
Thanks for the reply @Isakdl, much appreciated.

So, I was trying to simplify the use case to something a little more generic that I was hoping might be a bit easier to represent here and get an indicative solution that I could then apply to my specific use case.

To briefly explain what we're trying to achieve (and have currently solved using Appwrite, which is the backend I'm migrating to ServerPod from), we have a table called Transfers. Transfers tracks the movements of food waste from where it is produced to where it is finally processed into renewable energy. Food waste can be deposited by someone (entity) into a caddy (entity), the caddy can be emptied into a bin (entity) and the bin collected by a waste management company (entity). The waste management company can take the food waste to an aggregation site (entity) and from there to a processor (entity). Food waste can move through each of these entities where, by law, it becomes the responsibility of that entity to properly manage the journey to the next entity.

The current Transfers table has the following fields, among others:

```yaml
timestamp integer # milliseconds since Epoch
entityFrom enum # the current 'owner' of the food waste (producer, caddy, bin, collector, aggregator, processor)
entityFromId String # the UID of the current owner - found in producer, caddy, bin, collector, aggregator, or processor table
entityTo enum # the new 'owner' of the food waste (producer, caddy, bin, collector, aggregator, processor)
EntityToId # the UID of the new owner - found in producer, caddy, bin, collector, aggregator, or processor table
weight integer # the weight of the food waste being transferred
previousTransferId String # self-referential ID pointing to the previous Transfer in the sequence
```

There are discrete tables for the producers, caddies, bins, collectors, aggregators, and processors. The enum helps us figure out, when looking at a Transfer, which of these tables we need to look into for more information about the entity. We had to adopt this approach because when we started working with Appwrite, it did not support relationships. However, what it has allowed us to do is record all the Transfers in a single table, and thereby create a nice timeline of the movement of the food waste.

Does that paint a clearer picture of what we are doing?

**Reply by Isakdl** [reply]
I see! Interesting problem. 

I don't think there is anything wrong with modeling it the way you have, but with that setup, you cannot do a relation between the entities. The issue is that a single column cannot be represented as a relation to multiple different tables in PostgreSQL. 

Without changing the data model you would instead have to setup one column per entity, and you could put that into a bridge table so that your `entityFromId` and `entityToId` points to the same table.

That table then contains:
```
producerId: int?
caddyId: int?
binId: int?
collectorId: int?
aggregatorId: int?
processorId: int?
```

Where only one is set per entry. This doesn't scale well if you want to add more steps as this table would have to grow an additional column per thing but if these tables are fixed an unlikely to change much it could work.

The benefit of a relation here is that you would be able to make more complex queries from your transfer table. Such as give me all transfers originating from all producers created after date x (or any other data recorded for any of the different entities).

Example query:
 ```dart
Transfers.db.find(
  where: (t) => t.entityFrom.producer.createdAt > DateTime.parse('2024-05-24'),
);
```

In the end I think mostly comes down to a data modeling problem and to create a nice relation model you might have to think a little about how you structure your models and if your current setup is the best way to solve the problem or not. 

Maybe you really want this transfer log, perhaps business-critical information? In that case, I would keep it as is. But if you need to query data in a way you are not able to do today then I would rethink the models. It depends on how you want to read the data and what type of structural guarantees you want from the db.

**Reply by CordMemescape** [reply]
Part of the motivation to switch from Appwrite to ServerPod is the ability to do exactly those types of queries! In a much simplified and more readable way. Right now, to accomplish the same thing, I have to return all the producer records created after a particular date and manually build a list of producer IDs that feed into another query to return all Transfer records where the producerId matches that list. It's all done client-side over REST. :-/

For now, there are a fixed number of entities in the process. But the food waste might follow a path like this: producer -> bin -> collector -> aggregator -> collector -> (a different) aggregator -> collector -> processor. It is operationally dependent on different customers. Of course, even though all the entities are known, this is real life and who can predict what the process might look like in a year or a decade from now?!

Being new to ServerPod, I'm still trying to wrap my head around how to model bridging tables, what the field and table names should look like, etc. I know it's a big ask, @Isakdl, but do you think you could start me off with a sample of what the producer model, the transfer model and the bridging table might look like? I can extrapolate and build all the other models from that.

**Reply by Isakdl** [reply]
Alright cool! Well the setup I described above could be represented in the following way with Serverpod:


```yaml
# transaction.yaml
class: Transaction
table: transaction
fields:
  timestamp: DateTime
  # Making a 1:1 defined on both sides as an example for the entityFrom, if you do not need that
  # you can define it on one side with the same syntax of entityTo
  entityFromId: int
  entityFrom: EntityBridge?, relation(field=entityFromId, name=transaction_entity_bridge)
  entityTo: EntityBridge?, relation
  weight: int
  previousTransferId: int?, relation(parent=transaction)
  # The above could also be represented as an object like so:
  # previousTransfer: Transaction?, relation
indexes: 
   # Adding indexes to enforce a 1:1 relation
   entity_from_unique_idx:
      fields: entityFrom
      unique: true
   entity_to_unique_idx:
      fields: entityTo
      unique: true
```

```yaml
class: EntityBridge
table: entity_bridge
fields:
  # Making a 1:n example of the producer where both sides are defined
  # if you don't need the relation on the producer side just remove the name
   producerId: int?
   producer: Producer?, relation(field=producerId, name=entity_bridge_producer)

   # Define on only this side
   binId: int?
   bin: Bin?, relation(field=binId)

   # This is equivalent to the bin definition, but less verbose
   caddy: Caddy?, relation(optional)
   # and so on

   # You can also add the transaction in here and make a 1:1 relation both ways
   # if you need it.
   transactionFrom: Transaction?, relation(name=transaction_entity_bridge)

# These should most likely be 1:n relations so no indexes needed
```

```yaml
class: Producer
table: producer
fields:
  ...
  entityBridges: List<EntityBridge>?, relation(name=entity_bridge_producer)
```

Then when inserting data I would set everything null except for the specific id column you are interested in. Then you have two options to understand which entity you are linked to, use an enum like you did before or assuming you always leave the others as null you can find the object that is not null.

In either way, this part becomes a little awkward in your dart code. You have to have additional logic to figure out what object you are linked to, but no different from what I imagine you are already doing.

I hope this is of some help! My knowledge of your problem area is limited, there may be more suitable ways to structure the data around the problem but with the above, you should be able to do relational queries in one go without having to query several tables and then filter in code.

For the full explanation on relation setups see: https://docs.serverpod.dev/concepts/database/relations/one-to-one
For how to include data: https://docs.serverpod.dev/concepts/database/relation-queries
And how to filter on relations: https://docs.serverpod.dev/concepts/database/filter#relation-operations
