### DISCUSSION TITLE
Relation queries

### DISCUSSION THREAD

**Discussion by AdamMusa** [serverpod/serverpod#2320] [Q&A] [answered]
Hello everyone i need a help from you. I have some database model, linked each other  with relationship so i want retrieve all post his appreciaiton and owner so here are my code

```
class: Post
table: post
fields:
  description: String
  allowVisibilityTo: List<String>?
  media: List<String>?
  publishTo: String? #groupe id
  isPublish: bool?
  toPublishDate: DateTime?
  owner: module:auth:UserInfo?, relation
  appreciation: List<Appreciation>?,relation
  createAt: DateTime?
  updatedAt: DateTime?
```

```
class: Appreciation
table: appreciation
fields:
  appreciationtype: AppreciationType
  user: module:auth:UserInfo?, relation
  post: Post? ,relation
  createdAt: DateTime?
  updatedAt: DateTime? 
```
And how i make to retrieve all posts

```
Future<List<Post>> posts(Session session) async {
    return await Post.db.find(
      session,
      include: Post.include(
        owner: UserInfo.include(),
        appreciation: Appreciation.includeList(),
      ),
    );
  }
```
when i fetch the method i only get List<Post> without including the relations model so how can i  fix this bug ?

**Comment by Isakdl** [comment, marked as answer]
Question: How are you inserting the data?

The appreciations will only be included if you have attached them to the same reference. I suspect that you are adding the post on appreciation side but since all your relations are only defined on one side you effectively have two different relations between appreciation and post.

To add data to be able to query in the way you are doing right now you would have to insert the relation this way:

```dart
final post = Post(...);
final appreciation = Appreciation();

final newPost = await Post.db.insertRow(session, post);
final newAppreciation = await Appreciation.db.insertRow(session, appreciation);

await Post.db.attachRow.appreciation(session, newPost!, newAppreciation!);
```

Instead I suspect you want the appreciation list in the Post model and the post object in the appreciation model to represent the same value, this can be done by giving the relation a name, like so:

```yaml
class: Post
table: post
fields:
  description: String
  allowVisibilityTo: List<String>?
  media: List<String>?
  publishTo: String? #groupe id
  isPublish: bool?
  toPublishDate: DateTime?
  owner: module:auth:UserInfo?, relation
  appreciation: List<Appreciation>?,relation(name=post_appreciation)
  createAt: DateTime?
  updatedAt: DateTime?
```

```yaml
class: Appreciation
table: appreciation
fields:
  appreciationtype: AppreciationType
  user: module:auth:UserInfo?, relation
  post: Post? ,relation(name=post_appreciation)
  createdAt: DateTime?
  updatedAt: DateTime? 
```

Now you can create the relation in the following way (the one above is still valid):

```dart
final post = Post();
final newPost = await Post.db.insertRow(session, post);

final appreciation = Appreciation(postId: newPost.id!);

final newAppreciation = await Appreciation.db.insertRow(session, appreciation);  // We are inserting the id to the post when creating the appreciation
```

Since we have linked the relation from both sides they now refer to the same column in the database and you no longer have two independent columns. 

Relevant documentation for how to do relational queries including updating the relations can be found here: https://docs.serverpod.dev/concepts/database/relation-queries
