### DISCUSSION TITLE
Stack Overflow head scratcher

### DISCUSSION THREAD

**Discussion by CordMemescape** [serverpod/serverpod#2474] [Q&A] [answered]
Hi!

I've bumped into a head scratcher that's driving me a little nuts. I have an endpoint that iterates through an array of model classes to populate my database ahead of deployment. The premise is that if the record does not exist, it will be created and if it does, then the IDs are properly referenced to create the relationships. A sample of the array is below, with sensitive information removed.

```Dart
List<Carrier> carrierRows = [
  Carrier(
    companyName: 'companyName',
    registeredAddressId: -1,
    registeredAddress: Address(
      line1: 'line1',
      postcode: 'postcode',
      country: Country(
        name: 'United Kingdom of Great Britain and Northern Ireland (The)',
        alpha2Code: 'GB',
        alpha3Code: 'GBR',
        numericCode: 826,
      ),
    ),
    companyType: CompanyType(
      name: 'Private company limited by shares',
      categoryType: CategoryType(name: 'Registered company'),
    ),
    tradingAs: 'tradingAs',
    carrierUsers: [
      CarrierUser(
        carrierId: -1,
        userId: -1,
        user: User(
          userInfoId: -1,
          userInfo: UserInfo(
            userIdentifier: 'user@email.com',
            fullName: 'fullName',
            email: 'user@email.com',
            created: createdDateTime,
            scopeNames: [],
            blocked: false,
          ),
        ),
        role: Role(
          name: 'User',
          description: 'Regular user',
        ),
      ),
      CarrierUser(
        carrierId: -1,
        userId: -2,
        user: User(
          userInfoId: -2,
          userInfo: UserInfo(
            userIdentifier: 'user@email.com',
            fullName: 'fullName',
            email: 'user@email.com',
            created: createdDateTime,
            scopeNames: [],
            blocked: false,
          ),
        ),
        role: Role(
          name: 'User',
          description: 'Regular user',
        ),
      ),
    ],
    carrierSites: [
      CarrierSite(
        carrierId: -1,
        carrier: Carrier(companyName: 'companyName'),
        addressId: -2,
        address: Address(
          line1: 'line1',
          postcode: 'postcode',
          country: Country(
            name: 'United Kingdom of Great Britain and Northern Ireland (The)',
            alpha2Code: 'GB',
            alpha3Code: 'GBR',
            numericCode: 826,
          ),
        ),
        tradingAs: 'tradingAs',
      ),
    ],
  ),
  Carrier(
    companyName: 'companyName',
    registeredAddressId: -3,
    registeredAddress: Address(
      line1: 'line1',
      postcode: 'postcode',
      country: Country(
        name: 'United Kingdom of Great Britain and Northern Ireland (The)',
        alpha2Code: 'GB',
        alpha3Code: 'GBR',
        numericCode: 826,
      ),
    ),
    companyType: CompanyType(
      name: 'Private company limited by shares',
      categoryType: CategoryType(name: 'Registered company'),
    ),
    tradingAs: 'tradingAs',
    carrierUsers: [
      CarrierUser(
        carrierId: -2,
        userId: -3,
        user: User(
          userInfoId: -3,
          userInfo: UserInfo(
            userIdentifier: 'user@email.com',
            fullName: 'fullName',
            email: 'user@email.com',
            created: createdDateTime,
            scopeNames: [],
            blocked: false,
          ),
        ),
        role: Role(
          name: 'User',
          description: 'Regular user',
        ),
      ),
    ],
    carrierSites: [
      CarrierSite(
        carrierId: -2,
        carrier: Carrier(companyName: 'companyName'),
        addressId: -4,
        address: Address(
          line1: 'line1',
          postcode: 'postcode',
          country: Country(
            name: 'United Kingdom of Great Britain and Northern Ireland (The)',
            alpha2Code: 'GB',
            alpha3Code: 'GBR',
            numericCode: 826,
          ),
        ),
        tradingAs: 'tradingAs',
      ),
    ],
  ),
];
```

The process isn't very complicated and generally worked well. However, now when I run it (perhaps because the depth has increased), I get a Stack Overflow error. The thing is, there are no recursive function calls in the code, just a simple loop. However, this happens, and I don't know why. Does anyone have a suggestion as to what might be going on?

```
METHOD CALL: internal.addData duration: 254ms numQueries: 0 authenticatedUser: 3
Stack Overflow
#0      _CarrierUserImpl.copyWith (package:limetrack_server/src/generated/carrier_user.dart:206:3)
#1      _guardedCopyWith (package:serverpod_serialization/src/copy_with.dart:76:20)
#2      CloneList.clone.<anonymous closure> (package:serverpod_serialization/src/copy_with.dart:23:23)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#5      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:882:20)
#6      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#7      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#8      new List.of (dart:core-patch/array_patch.dart:39:18)
#9      Iterable.toList (dart:core/iterable.dart:497:7)
#10     CloneList.clone (package:serverpod_serialization/src/copy_with.dart:23:59)
#11     _CarrierImpl.copyWith (package:limetrack_server/src/generated/carrier.dart:407:32)
#12     _CarrierUserImpl.copyWith (package:limetrack_server/src/generated/carrier_user.dart:221:66)
#13     _guardedCopyWith (package:serverpod_serialization/src/copy_with.dart:76:20)
#14     CloneList.clone.<anonymous closure> (package:serverpod_serialization/src/copy_with.dart:23:23)
#15     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#16     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#17     WhereTypeIterator.moveNext (dart:_internal/iterable.dart:882:20)
#18     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#19     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#20     new List.of (dart:core-patch/array_patch.dart:39:18)
#21     Iterable.toList (dart:core/iterable.dart:497:7)
#22     CloneList.clone (package:serverpod_serialization/src/copy_with.dart:23:59)
#23     _CarrierImpl.copyWith (package:limetrack_server/src/generated/carrier.dart:407:32)
#24     _CarrierUserImpl.copyWith (package:limetrack_server/src/generated/carrier_user.dart:221:66)
#25     _guardedCopyWith (package:serverpod_serialization/src/copy_with.dart:76:20)
#26     CloneList.clone.<anonymous closure> (package:serverpod_serialization/src/copy_with.dart:23:23)
#27     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#28     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#29     WhereTypeIterator.moveNext (dart:_internal/iterable.dart:882:20)
#30     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#31     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#32     new List.of (dart:core-patch/array_patch.dart:39:18)
#33     Iterable.toList (dart:core/iterable.dart:497:7)
#34     CloneList.clone (package:serverpod_serialization/src/copy_with.dart:23:59)
#35     _CarrierImpl.copyWith (package:limetrack_server/src/generated/carrier.dart:407:32)
#36     _CarrierUserImpl.copyWith (package:limetrack_server/src/generated/carrier_user.dart:221:66)
#37     _guardedCopyWith (package:serverpod_serialization/src/copy_with.dart:76:20)
#38     CloneList.clone.<anonymous closure> (package:serverpod_serialization/src/copy_with.dart:23:23)
#39     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
...
...
#7775   Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#7776   Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#7777   Future._completeWithValue (dart:async/future_impl.dart:652:5)
#7778   _rootRunUnary (dart:async/zone.dart:1407:47)
#7779   _FutureListener.handleValue (dart:async/future_impl.dart:163:18)
#7780   Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#7781   Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#7782   Future._completeWithValue (dart:async/future_impl.dart:652:5)
#7783   _rootRunUnary (dart:async/zone.dart:1407:47)
#7784   _FutureListener.handleValue (dart:async/future_impl.dart:163:18)
#7785   Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#7786   Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#7787   Future._completeWithValue (dart:async/future_impl.dart:652:5)
#7788   _rootRunUnary (dart:async/zone.dart:1407:47)
#7789   _FutureListener.handleValue (dart:async/future_impl.dart:163:18)
#7790   Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#7791   Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#7792   Future._completeWithValue (dart:async/future_impl.dart:652:5)
#7793   _rootRunUnary (dart:async/zone.dart:1407:47)
#7794   _FutureListener.handleValue (dart:async/future_impl.dart:163:18)
#7795   Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#7796   Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#7797   Future._completeWithValue (dart:async/future_impl.dart:652:5)
#7798   Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:722:7)
#7799   _rootRun (dart:async/zone.dart:1399:13)
#7800   _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#7801   _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#7802   _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#7803   _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#7804   _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7805   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

**Comment by CordMemescape** [comment]
As an aside, I've noticed that if I invoke the endpoint several time in succession, usually by the third or fourth attempt, everything executes completely as expected. However, if I clear down all the added data, the cycle starts over with two to three Stack Overflow exceptions and then completes successfully.

**Comment by CordMemescape** [comment]
So I've worked out that the issue is caused by the relationships between two of my models recursively calling each other when I reference them in code until the exception occurs. The two models look like this (simplified):
```
### Carrier
class: Carrier
table: carriers

fields:
  companyName: String
  registeredAddress: Address?, relation(optional)
  tradingAs: String?
  carrierUsers: List<CarrierUser>?, relation(name=carrier_carrierUser, optional)
  deleted: bool?

indexes:
  carrier_unique_idx:
    fields: companyName
    unique: true


### CarrierUser
class: CarrierUser
table: carrier_users

fields:
  carrier: Carrier?, relation(name=carrier_carrierUser)
  user: User?, relation
  role: Role?, relation(optional)
  deleted: bool?

indexes:
  carrier_user_unique_idx:
    fields: carrierId, userId
    unique: true
```
The work-around is to remove the `List<CarrierUser>` relationship in the `Carrier` model but I understood that this bi-directional relationship was possible and if I'm honest, is extremely useful to have! What am I doing wrong with how I've implemented it?

**Reply by Isakdl** [reply]
I think the error is in your population code, if you are adding references automatically and you do that for all relations for each model down the tree. Then you must keep track of "visited" nodes or models to know when you are on a looping branch, if you have bidirectional relations. 

Think of it like a [graph](https://en.wikipedia.org/wiki/Graph_(abstract_data_type)), when you have no bidirectional relations you have created a [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph) (assuming no cyclic relations over several models, e.g. A -> B -> C -> A) and therefore don't have to worry about this problem. 

A side note
```
carrierUsers: List<CarrierUser>?, relation(name=carrier_carrierUser, optional)
```

Is wrong, are you not getting any errors from this?

The optional keyword should be placed on the other side of the relation e.g.

```
carrier: Carrier?, relation(name=carrier_carrierUser, optional)
```

**Comment by CordMemescape** [comment]
> I think the error is in your population code

Yes, I think I agree. The error definitely happens when I'm populating the database in code because when I run the same code multiple times, if the related records already exist, the population part is skipped and a populated related object is returned from a `.find()`. I think perhaps I'm trying to return too much information all at once in the population step by building up and updating the returned object with all the related objects that were added. A good workaround might be to add all the relationships as I am doing, but at the very end of the process, return a fully populated object (with all the relationships) using `.findById()`.

> Is wrong, are you not getting any errors from this?
> 
> The optional keyword should be placed on the other side of the relation e.g.

The way that I was thinking about this is that a carrier may or may not have carrierUsers defined. But, a carrierUser will ALWAYS belong to a carrier. So with this in mind, have I not defined the relationship correctly?

**Reply by Isakdl** [reply]
> The way that I was thinking about this is that a carrier may or may not have carrierUsers defined. But, a carrierUser will ALWAYS belong to a carrier. So with this in mind, have I not defined the relationship correctly?

In that case simply removing the optional keyword (it shouldn't do anything anyway, in your situation) will be the correct setup. The optional keyword is used to make the foreign key column nullable in the database.

**Comment by CordMemescape** [comment]
In that case simply removing the optional keyword (it shouldn't do anything anyway, in your situation) will be the correct setup. The optional keyword is used to make the foreign key column nullable in the database.

Do you mean removing the optional keyword from the carrier model, like so?

```
### Carrier
class: Carrier
table: carriers

fields:
  companyName: String
  registeredAddress: Address?, relation(optional)
  tradingAs: String?
  carrierUsers: List<CarrierUser>?, relation(name=carrier_carrierUser)
  deleted: bool?
```
Surely that will require all carriers to have carrierUsers? Or does the way that Serverpod manages foreign keys for Lists differ to the way that it manages foreign keys for other types?

**Reply by Isakdl** [reply, marked as answer]
Correct, the list it self will never have a foreign key in the same class as the list (in this case on the carriers table), and since your relation is named the foreign key is managed by the CarrierUser class. What you effectively have told Serverpod is that this list is populated by looking at the foreign key inside "CarrierUser". 

Example:
```yaml
### Carrier
class: Carrier
table: carriers
fields:
  carrierUsers: List<CarrierUser>?, relation(name=carrier_carrierUser)
  ...


### CarrierUser
class: CarrierUser
table: carrier_users
fields:
  carrier: Carrier?, relation(name=carrier_carrierUser)
  ...
```

is the same as
```yaml
### Carrier
class: Carrier
table: carriers
fields:
  carrierUsers: List<CarrierUser>?, relation(name=carrier_carrierUser)
  ...


### CarrierUser
class: CarrierUser
table: carrier_users
fields:
  carrierId: int
  carrier: Carrier?, relation(name=carrier_carrierUser, field=carrierId)
  ...
```

And with the optional keyword:

```yaml
### Carrier
class: Carrier
table: carriers
fields:
  carrierUsers: List<CarrierUser>?, relation(name=carrier_carrierUser)
  ...


### CarrierUser
class: CarrierUser
table: carrier_users
fields:
  carrier: Carrier?, relation(name=carrier_carrierUser, optional)
  ...
```

is the same as
```yaml
### Carrier
class: Carrier
table: carriers
fields:
  carrierUsers: List<CarrierUser>?, relation(name=carrier_carrierUser)
  ...


### CarrierUser
class: CarrierUser
table: carrier_users
fields:
  carrierId: int?
  carrier: Carrier?, relation(name=carrier_carrierUser, field=carrierId)
  ...
```

This means you can create a Carrier without any CarrierUser. But since the relation to a carrier is required on a CarrierUser you cannot create a carrier user without having a carrier to link it to. The relation is completely dictated by the value of `carrierId` for both sides of the relation.
