### DISCUSSION TITLE
How to use bidirectional relationships?

### DISCUSSION THREAD

**Discussion by CordMemescape** [serverpod/serverpod#2510] [Q&A] [answered]
@vlidholt @SandPod 

When creating models with a bidirectional relationship, how do you create the related records in Serverpod?

Below are two models with (hopefully) a bidirectional relationship.

```
### Bin
class: Bin
table: bins

fields:
  binBodyId: int
  binBody: BinBody?, relation(name=bin_binBody, field=binBodyId)
  underMaintenanceUntilDate: DateTime?
  deleted: bool?

indexes:
  bin_unique_idx:
    fields: binBodyId
    unique: true


### BinBody
class: BinBody
table: bin_bodies

fields:
  binId: int
  bin: Bin?, relation(name=bin_binBody)
  volume: int?
  weight: int?
  deleted: bool?

indexes:
  bin_body_unique_idx:
    fields: binId
    unique: true
```

Is the correct order of events to first create the BinBody and then the Bin record, and then attach the BinBody to the Bin like so?

```
BinBody binBody = await BinBody.db.insertRow(session, BinBody(binId: -1, volume: 20000));
Bin bin = await Bin.db.insertRow(session, Bin(binBodyId: binBody.id!));

await Bin.db.attachRow.binBody(session, bin, binBody);
```

Does it matter which way you do the attachRow, given that the relationship is bidirectional? Are there any issues with foreign keys that will likely cause an exception?
