### DISCUSSION TITLE
Storing JSON (Map<String,dynamic>)

### DISCUSSION THREAD

**Discussion by seanradford** [serverpod/serverpod#2600] [Q&A] [answered]
With regards to database models, the documentation states that:

> Storing a field with a primitive / core dart type will be handled as its respective type. However, if you use a complex type, such as another model, a List, or a Map, these will be stored as a json object in the database.

However, the following `spy.yaml` errors on generation:

```
class: TestEntity
table: test_entity
fields:
  uuid: String
  jsonData: Map<String,dynamic>
```

```
Found 1 issue.
Error on line 6, column 13 of lib/src/models/test_entity.spy.yaml: The datatype "dynamic" is not supported in models.
   ╷
6 │   jsonData: Map<String,dynamic>
```

If `dynamic` is not supported as the value of a `Map`, how do we store JSON data?

Thank you and regards,
