### DISCUSSION TITLE
Best practice: how to get length of relation

### DISCUSSION THREAD

**Discussion by mades5** [serverpod/serverpod#2665] [Q&A] [answered]
When I have 2 models

```
# company.yaml
class: Company
table: company
fields:
  name: String
  employees: List<Employee>?, relation(name=company_employees)

# employee.yaml
class: Employee
table: employee
fields:
  name: String
  companyId: int?, relation(name= company_employees, parent=company)
```

what is the best practice to display a list of companies with the number of employees?

```
final companies = await Company.db.findById(
  session,
  include: Company.include(
    employees: Employee.includeList()
  ),
);

for (final company in companies) print(company.employees.length);
```

But I think this will produce a lot of sql queries.
Is there a better way to do that?
