### DISCUSSION TITLE
Persistent 502 Bad Gateway Errors with Serverpod 2.0.2 on Docker Setup with Nginx Proxy Manager

### DISCUSSION THREAD

**Discussion by PlaxXOnline** [serverpod/serverpod#2675] [Q&A] [answered]
I’m encountering persistent 502 Bad Gateway errors when trying to host Serverpod version 2.0.2 on a dedicated server using Docker and Nginx Proxy Manager. My setup is as follows:

**Domains and Nginx Proxy Manager Configurations:**

	•	api.kahle.dev -> forwards to diving_school_api:8080
	•	insights.kahle.dev -> forwards to diving_school_api:8081
	•	db.kahle.dev -> forwards to diving_school_db:8090

The DNS is managed via Namecheap and points correctly to my dedicated server.

**Docker Compose Configuration:**

	•	Postgres on 8090:5432
	•	Redis on 8091:6379
	•	Serverpod API on 8080, 8081, 8082 (tried it with and without the ports)

**Serverpod Configuration:**

        apiServer:
          port: 8080
          publicHost: api.kahle.dev
          publicPort: 443
          publicScheme: https
        
        insightsServer:
          port: 8081
          publicHost: insights.kahle.dev
          publicPort: 443
          publicScheme: https
        
        webServer:
          port: 8082
          publicHost: kahle.dev
          publicPort: 443
          publicScheme: https
          
  
  **Problems Encountered:**

	1.	502 Bad Gateway Errors: Nginx logs consistently show connect() failed (111: Connection refused) when trying to connect to the upstream services (172.19.0.10:8081, 172.19.0.10:8082).
	2.	SSL Handshake Failures: There are multiple SSL handshake failed errors, indicating potential issues with how SSL/TLS is being handled between Nginx and the Serverpod services.

**Steps Taken to Troubleshoot:**

	1.	Checked Container Logs: Verified that the containers (API, DB) are running and listening on the correct ports. (I absolutely don´t know why Insights didn´t start)
	2.	Direct Connection Tests: Used curl from the server to test direct connections to the internal Docker IPs and ports. (8080 is the only one working)
	3.	Nginx Configuration Adjustments: Attempted to adjust the Nginx Proxy Manager settings to use http instead of https for upstream connections, given that the internal services might not be configured for SSL.
	4.	Network and Firewall Check: Ensured that Docker networks and firewall settings aren’t blocking any necessary connections.

**Current Situation:**

Despite these efforts, the issue persists. I should note that forwarding to Docker containers using Nginx Proxy Manager has never been an issue before, and it works smoothly for my other services. I’m looking for guidance on further troubleshooting steps or potential misconfigurations specific to running Serverpod in this setup. Any insights or recommendations would be greatly appreciated.

Here are the Nginx Proxy Manager Proxy Hosts (I also tried it with https scheme):

![Bildschirmfoto 2024-08-26 um 22 58 01](https://github.com/user-attachments/assets/294210bb-fbae-46eb-a99d-5ee36a8904cb)

Edit:

To further troubleshoot, I’ve now completely disabled Nginx Proxy Manager and am trying to route everything through Traefik. However, I’m still encountering issues, with the following error being thrown: HandshakeException (HandshakeException: Handshake error in client (OS Error: TLSV1_ALERT_UNRECOGNIZED_NAME(tls_record.cc:592))).

**Comment by SandPod** [comment]
Hey @PlaxXOnline 👋 

As a first step, look through this issue and see if there is anything of help there: https://github.com/serverpod/serverpod/issues/2642

**Reply by PlaxXOnline** [reply]
Hey @SandPod :)

Yes, i looked through but that didn´t help.
I have now also tried it with the Dockerfile generated by Serverpod, unfortunately without success.

In any case, I was able to find out that no certificates are created. The acme.json is permanently empty and the Flutter app as well as Insights report a HandshakeException 

Flutter Mobile App:
HandshakeException (HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393)))

Insights:
![image](https://github.com/user-attachments/assets/9c158e0b-0da7-489a-9144-ed71ffda91d1)

**Reply by SandPod** [reply]
Hmm, it would be good to rule out if this is something connected to Serverpod or if this has to do with how you issue the certificate.

How about you deploy a simpler container that always responds with a 200 code. Does that make it possible to issue the certificate?

**Reply by PlaxXOnline** [reply, marked as answer]
After two days of pure despair, I was able to solve it.

The error was in the Dockerfile, I strictly followed the Dockerfile from @BenAuerDev  tutorial but I suspect that it was originally created for an older version of Serverpod.

Long story short, the path to runtime was missing in my Dockerfile.


```
COPY --from=build /runtime/ /app/  <--------- I had to add this Line
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/web/ web/
COPY --from=build /app/migrations/ /migrations/
COPY --from=build /app/templates/ /templates/

RUN chmod -R 755 /app    <--------- and this one also
```

After I added the two lines, everything runs smoothly via the Nginx Proxy Manager on my VPS with Docker.

Many thanks for your efforts @SandPod

**Reply by SandPod** [reply]
Awesome! Happy that you are up and running 🚀

**Reply by BenAuerDev** [reply]
@PlaxXOnline Thanks for the tag I just updated the Dockerfile in the article and added the line setting the runtime path. :muscle: :+1:  
For why the `RUN chmod -R 755 /app` is necessary I'll look into that and if needed I'll update the file accordingly :)

**Comment by Schamppu** [comment]
Hey @PlaxXOnline I've been trying to configure this like crazy, but still getting `Connection refused, errno = 111`. I have the exact same setup as you, trying to configure it with Nginx Proxy Manager.

Can you give any more insight into this? I'm starting to lose hope. I've tried the fix you mentioned here, but still nothing. I think that in my case, it might be that the Nginx Proxy Manager or Postgres is setup incorrectly, causing the connection to fail. I get 502 Bad Gateway if I try to go to the domain I've setup for Postgres.

Any help is welcome, I'm starting to get desperate.

**Reply by PlaxXOnline** [reply]
Sure i try to help you, what exactly do you need?

Can you please post your Configurations?

**Reply by Schamppu** [reply]
Thank you so much for quick response! Here are the configs:

Dockerfile:

```
# Stage 1: Build the server application
FROM --platform=$BUILDPLATFORM dart:3.2.5 AS build

# Resolve app dependencies.
WORKDIR /app
COPY walkscape_devtools_server /app

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

# Stage 2: Create the final Docker image
FROM debian:buster-slim

# Set environment variables
ENV runmode=production
ENV serverid=default
ENV logging=normal
ENV role=monolith

# Copy the built artifacts from the previous stage
COPY --from=build /runtime/ /app/
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/web/ web/
COPY --from=build /app/migrations/ migrations/

RUN chmod -R 755 /app

# Copy passwords file
COPY ./walkscape_devtools_server/config/passwords.yaml /app/config/passwords.yaml

# Expose ports
EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

# Define the command to run the server application
CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role --apply-migrations
```

Production.yaml
```
apiServer:
  port: 8080
  publicHost: api.tools.walkscape.app
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: insights.tools.walkscape.app
  publicPort: 443
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: web.tools.walkscape.app
  publicPort: 443
  publicScheme: https

database:
  host: db.tools.walkscape.app
  port: 5432
  name: serverpod
  user: postgres

redis:
  enabled: false
  host: redis.tools.walkscape.app
  port: 6379
```

docker-compose.yaml
```
version: '3.8'
services:
  postgresql:
    image: postgres
    container_name: walkscape-devtools-db
    volumes:
      - /data/postgres:/var/lib/postgresql/data
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_DB=serverpod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    networks:
      - web

  redis:
    image: redis:6.2.6
    container_name: walkscape-devtools-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - /data/redis:/redis/data

    networks:
      - web

  walkscape-devtools:
    image: ghcr.io/schamppu/walkscape-devtools:latest
    container_name: walkscape-devtools-api
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - web

  nginx_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - web

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 10 --debug
    networks:
      - web

networks:
  web:
    external: true
```

On Nginx Proxy Manager:
![image](https://github.com/user-attachments/assets/f9c947da-58c5-4198-a38f-372b78d84b39)

![image](https://github.com/user-attachments/assets/2e0aaa3c-1ad4-485e-8311-979c875909d6)

![image](https://github.com/user-attachments/assets/314571c9-1289-42ad-822b-ca19f7d6a260)

**Reply by PlaxXOnline** [reply]
If all your Nginx Proxy Host Configurations looks same, you have to enable "force SSL" at first point.

If that doesn't help i'll take a closer look tomorrow.

**Reply by Schamppu** [reply]
> If all your Nginx Proxy Host Configurations looks same, you have to enable "force SSL" at first point.
> 
> If that doesn't help i'll take a closer look tomorrow.

Gave that a try, no effect. I've tried the DNS setup by putting the login page to [test.tools.walkscape.app](https://test.tools.walkscape.app) and that works just fine.

**Reply by Schamppu** [reply]
Got it working. Shouldn't have tried to reverse proxy the DB, instead changed the Serverpod's DB to refer to the container name:

```
database:
  host: walkscape-devtools-db # This instead of db.tools.walkscape.app
  port: 5432
  name: serverpod
  user: postgres
```
