### DISCUSSION TITLE
repair migration doesn't work for one project only on one computer

### DISCUSSION THREAD

**Discussion by Metaildust** [serverpod/serverpod#2720] [Q&A] [answered]
I accidentally deleted one migration. So, I should run "repair migration" and restart server with "apply repair migration" then everything should be fine, but turns out it poped
`"Failed to apply database migrations. DatabaseException: relation "question" does not exist"`

here's my models yaml file:
```
class: ServerNode
table: node
fields: 
    bank: Bank?, relation(name=bank_nodes)
    parents: List<NodeRelation>?,relation(name=node_childSide, optional)
    children: List<NodeRelation>?, relation(name=node_parentSide, optional)
    ps: String?
    index: List<int>
    title: String
    question: Question?, relation (optional)
    knowledge: Knowledge?, relation (optional)
indexes: 
    node_knowledge_unique_idx:
        fields: knowledgeId
        unique: true
    node_question_unique_idx:
        fields: questionId
        unique: true
```
        
And here's the repair migration file:
```
BEGIN;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "knowledge" (
    "id" bigserial PRIMARY KEY,
    "content" text NOT NULL
);

--
-- ACTION ALTER TABLE
--
ALTER TABLE "node" ADD COLUMN "questionId" bigint;
ALTER TABLE "node" ADD COLUMN "knowledgeId" bigint;
CREATE UNIQUE INDEX "node_knowledge_unique_idx" ON "node" USING btree ("knowledgeId");
CREATE UNIQUE INDEX "node_question_unique_idx" ON "node" USING btree ("questionId");
ALTER TABLE ONLY "node"
    ADD CONSTRAINT "node_fk_1"
    FOREIGN KEY("questionId")
    REFERENCES "question"("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
ALTER TABLE ONLY "node"
    ADD CONSTRAINT "node_fk_2"
    FOREIGN KEY("knowledgeId")
    REFERENCES "knowledge"("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
--
-- ACTION ALTER TABLE
--
ALTER TABLE "node_relation" DROP CONSTRAINT "node_relation_fk_0";
ALTER TABLE "node_relation" DROP CONSTRAINT "node_relation_fk_1";
ALTER TABLE ONLY "node_relation"
    ADD CONSTRAINT "node_relation_fk_0"
    FOREIGN KEY("parentSideId")
    REFERENCES "node"("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
ALTER TABLE ONLY "node_relation"
    ADD CONSTRAINT "node_relation_fk_1"
    FOREIGN KEY("childSideId")
    REFERENCES "node"("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
--
-- ACTION CREATE TABLE
--
CREATE TABLE "question" (
    "id" bigserial PRIMARY KEY,
    "content" text NOT NULL,
    "answer" text NOT NULL
);


--
-- MIGRATION VERSION FOR gen
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('gen', '20240827002313952', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20240827002313952', "timestamp" = now();

--
-- MIGRATION VERSION FOR serverpod
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod', '20240516151843329', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20240516151843329', "timestamp" = now();

--
-- MIGRATION VERSION FOR serverpod_auth
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod_auth', '20240520102713718', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20240520102713718', "timestamp" = now();

--
-- MIGRATION VERSION FOR _repair
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('_repair', '20240908120036164', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20240908120036164', "timestamp" = now();


COMMIT;

```
And if I restart the server with "apply-migrations", it shows can't found the migration I deleted before: 
```
Failed to apply database migrations. Exception: Version 20240816224735501 not found in project.
Insights listening on port 8081
Server default listening on port 8080
Webserver listening on port 8082

```

and the weird thing is, this serverpod project works well on my another pc. I tried delete this project and rebuild with the same project name on the original pc, but this problem "Version 20240816224735501 not found in project" still comes out on this pc as long as it's using the same project name, even if it's a brand new default serverpod project with default migration. Still, "relation 'question' does not exist" poped out for the project I rebuild when I repair migration. And I have to use the old database password so I guess even if I recreate and rebuild this project, there's still something old that is not recreated as long as it's using the same project name.
So how do I fix this?
If all my conjecture was right, how do I delete this project completely so I can recreate this project?
