### DISCUSSION TITLE
How do you deploy a Flutter web app to GCP?

### DISCUSSION THREAD

**Discussion by LukasMirbt** [serverpod/serverpod#2839] [Q&A] [answered]
I have managed to deploy my Flutter web app to GCP and can access it on `app.myproject.com/` (following similar steps as in https://github.com/serverpod/serverpod/discussions/678). 

However, when I go to `app.myproject.com/sign-in`, I get an Error 404 page. It seems like the web server is handling the path instead of passing it to Flutter.

I have tried various different configurations but can't seem to figure it out.
How do I get paths other than `/` to work?

Here's my setup:

`scipts/build_web`:

```bash
#!/bin/sh

# Makes sure we break the script on any error.
set -e

# Build the web app.
cd myproject_flutter
flutter build web --release --target lib/main_production.dart
cd ..

# Copy the build files into the web/app diretory.
rm -rf myproject_server/web/app
cp -r myproject_flutter/build/web myproject_server/web/app

# Move the index.html file into the templates directory.
mv myproject_server/web/app/index.html myproject_server/web/templates/index.html
```

`deployment-gcp.yml`:

```yaml
       [...]
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Make build_web executable
        run: chmod +x scripts/build_web

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Compile Flutter web app
        shell: bash
        run: |
          scripts/build_web

      - name: Create passwords file
        working-directory: myproject_server
        shell: bash
        env:
          SERVERPOD_PASSWORDS: ${{ secrets.SERVERPOD_PASSWORDS }}
        run: |
          pwd
          echo "$SERVERPOD_PASSWORDS" > config/passwords.yaml
          ls config/
        [...]
```

`server.dart`

```dart
  // Setup a default page at the web root.
  pod.webServer.addRoute(RouteRoot(), '/');
  pod.webServer.addRoute(RouteRoot(), '/index.html');
  // Serve all files in the /static directory.
  pod.webServer.addRoute(
    RouteStaticDirectory(serverDirectory: 'app', basePath: '/'),
    '/*',
  );
```

`myproject_server/lib/src/web/routes/root.dart`

```dart
class RouteRoot extends WidgetRoute {
  @override
  Future<Widget> build(Session session, HttpRequest request) async {
    return IndexPageWidget();
  }
}
```

`myproject_server/lib/src/web/widgets/index_page_widget.dart`

```dart
class IndexPageWidget extends Widget {
  IndexPageWidget() : super(name: 'index');
}
```

**Comment by Isakdl** [comment, marked as answer]
You can create a SinglePageAppRouter like I showed in another discussion here: https://github.com/serverpod/serverpod/discussions/2793#discussioncomment-10808277

Then you can go to any path and load the flutter app!

**Reply by LukasMirbt** [reply]
Thanks, I was able to get it to work with the help of #2793 👍
Sharing the full solution for other people (including some steps for Google Sign-in). Does this look right @Isakdl?

`scripts/build_web `

```bash
#!/bin/sh

# Exit script on any error.
set -e

# Build the web app.
cd myproject_flutter
flutter build web --release --target lib/main_production.dart
cd ..

# Remove old build files and copy new ones into web/static.
rm -rf myproject_server/web/static
mkdir -p myproject_server/web/static
cp -r myproject_flutter/build/web/* myproject_server/web/static/
```

`.github/workflows/deployment-gcp.yml`

```yaml
name: Deploy to GCP
on:
  push:
    branches: [deployment-gcp-production, deployment-gcp-staging]
  workflow_dispatch:
    inputs:
      target:
        description: "Target"
        required: true
        default: "production"
        type: choice
        options:
          - "staging"
          - "production"

env:
  PROJECT: "myproject-serverpod-1562j"
  REGION: europe-north1
  ZONE: europe-north1-c

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setting Target Mode from Input
        if: ${{ github.event.inputs.target != '' }}
        run: echo "TARGET=${{ github.event.inputs.target }}" >> $GITHUB_ENV

      - name: Setting Target mode based on branch
        if: ${{ github.event.inputs.target == '' }}
        run: echo "TARGET=${GITHUB_REF##*-}" >> $GITHUB_ENV

      - name: Set repository
        run: echo "REPOSITORY=serverpod-${{ env.TARGET }}-container" >> $GITHUB_ENV

      - name: Set Image Name
        run: echo "IMAGE_NAME=serverpod" >> $GITHUB_ENV

      - name: Set Service Name
        run: echo "SERVICE_NAME=$(echo $IMAGE_NAME | sed 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_ENV

      - name: Test
        run: echo $SERVICE_NAME

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Make build_web executable
        run: chmod +x scripts/build_web

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Compile Flutter web app
        shell: bash
        run: |
          scripts/build_web

      - name: Create passwords file
        working-directory: myproject_server
        shell: bash
        env:
          SERVERPOD_PASSWORDS: ${{ secrets.SERVERPOD_PASSWORDS }}
        run: |
          pwd
          echo "$SERVERPOD_PASSWORDS" > config/passwords.yaml
          ls config/

      - name: Create google_client_secret.json
        working-directory: myproject_server
        shell: bash
        env:
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: |
          pwd
          echo "$GOOGLE_CLIENT_SECRET" > config/google_client_secret.json
          ls config/

      - name: Configure Docker
        working-directory: myproject_server
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build the Docker image
        working-directory: myproject_server
        run: "docker build -t $IMAGE_NAME ."

      - name: Tag the Docker image
        working-directory: myproject_server
        run: docker tag $IMAGE_NAME ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/$IMAGE_NAME

      - name: Push Docker image
        working-directory: myproject_server
        run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY }}/$IMAGE_NAME

      - name: Restart servers in instance group
        run: |
          gcloud compute instance-groups managed rolling-action replace serverpod-${{ env.TARGET }}-group \
           --project=${{ env.PROJECT }} \
           --replacement-method='substitute' \
           --max-surge=1 \
           --max-unavailable=1 \
           --zone=${{ env.ZONE }}
```

`myproject_server/lib/src/web/routes/single_page_app_router.dart`

```dart
import 'dart:io';

import 'package:serverpod/serverpod.dart';

/// Route for serving a single page app.
///
/// This route will serve the file at `web/$appRootPath` for all request that
/// do not match any other static files in the `serverDirectory`.
class SinglePageAppRouter extends RouteStaticDirectory {
  /// Creates a single page app route.
  ///
  /// The [appRootPath] is the path to the root file of the single page app
  /// relative to the [serverDirectory]. Defaults to 'index.html'.
  SinglePageAppRouter({
    required super.serverDirectory,
    String appRootPath = 'index.html',
    super.basePath,
    super.serveAsRootPath,
  }) : appRootFilePath = 'web/$serverDirectory/$appRootPath';

  /// The path to the root file of the single page app.
  final String appRootFilePath;

  @override
  Future<bool> handleCall(Session session, HttpRequest request) async {
    final staticFileFound = await super.handleCall(session, request);
    if (staticFileFound) {
      return staticFileFound;
    }

    try {
      final fileContents = await File(appRootFilePath).readAsBytes();
      request.response.add(fileContents);
      return true;
    } catch (_) {}

    return false;
  }
}
```

`myproject_server/lib/server.dart`

```dart
  [...]

  // This route needs to be registered before the SinglePageAppRouter.
  pod.webServer.addRoute(auth.RouteGoogleSignIn(), '/googlesignin');

  pod.webServer.addRoute(
    SinglePageAppRouter(serverDirectory: 'static', basePath: '/'),
    '/*',
  );

  auth.AuthConfig.set(
    auth.AuthConfig(
      minPasswordLength: 12,
    ),
  );

  // Start the server.
  await pod.start();

  [...]
```
