### DISCUSSION TITLE
How to insert model with many-to-many relation ?

### DISCUSSION THREAD

**Discussion by HD16K** [serverpod/serverpod#2887] [Q&A] [answered]
_Forgive me if this thread has appeared somewhere but I have not found it._

So, suppose I have these models :
``` yaml
class: APIEvent
table: event
fields:
  eventTitle: String
  weight: int
  junction: List<APIPresetEvents>?,relation(name=event_junctions)
```
```yaml
class: APIPresetEvents
table: pej
fields:
  events: APIEvent?,relation(name=event_junctions)
  presets: APIPreset?,relation(name=preset_junctions)
indexes:
  pej_index_idx:
    fields: eventsId, presetsId
    unique: true
```
```yaml
class: APIPreset
table: preset
fields:
  presetName: String
  junctions: List<APIPresetEvents>?,relation(name=preset_junctions) 
```

and now I would like to insert, for example, APIPreset with the name 'TestPreset' and with 10 events.
I grasp the concept of enpoints and I also have an idea how to pass data to the server, but I have no idea how to make it save in the database with this 'complex' relation.

Maybe it is just skill issue and and the solution is obvious but for me (I'd say I'm more of a beginner) it's not understandable.

For the record, I'm asking for code that allows you to save APIPreset in the database, along with relationships to APIEvent
