### DISCUSSION TITLE
Model filtering on Set<String>

### DISCUSSION THREAD

**Discussion by tricaricom** [serverpod/serverpod#3055] [Q&A]
Let's say I have a model like:

```
class: Post
table: posts
fields:
 title: String
 content: String
 tags: List<String>
```

I want to filter posts based on matching tags:

```
Future<List<Post>> getPostsByTags(Session session, Set<String> filterOnTheseTags) async {

    var query = Post.db.find(
      session,
      where: (t) => t.tags.inSet(filterOnTheseTags) /// something like this pseudocode
    );

    return await query;
  }
```

The brute force way would be to get the posts first, then iterate over each post's tag list, then filter that way.
