### DISCUSSION TITLE
Get serverOnly field on FutureCall

### DISCUSSION THREAD

**Discussion by mades5** [serverpod/serverpod#3103] [Q&A]
Hi,
I have a model with a field marked as serverOnly. I started a FutureCall and need to get the contents of this field. If I try to get that field with Model.db.findById I just get all other field but not the one marked as serverOnly. How can I get that field and its contents?

**Comment by Isakdl** [comment]
Hey @mades5 could you show a code example of your problem?

Do you get any errors?

**Comment by mades5** [comment]
```
class: Model
table: models
fields:
  name1: String
  name2: String?, scope: serverOnly
```
when I create that model and try to access that via endpoint by

`Model.db.findById(1)`

I just get {"name1": "value1"}, I can write to name2 but cannot access.
