### DISCUSSION TITLE
How to select field in parent relations?

### DISCUSSION THREAD

**Discussion by nglsondao113** [serverpod/serverpod#3140] [Q&A]
In the address table, I don't want to take the id field of the user table as a foreign key, I want to take the userId field of the user table as a foreign key. What should I do?
```
class: User
table: user
fields:
  userId: int, relation(parent=serverpod_user_info) 
indexes:
  user_userInfo_unique_idx:
    fields: userId
    unique: true

#############
class: Address
table: address
fields:
  userId: int, relation(parent=user)  #If I leave it like this, it will take the id of the user table as a foreign key. I want the userId field of the user table to be a foreign key, what should I do?
indexes:
  address_user_unique_idx:
    fields: userId
    unique: true
```
