### DISCUSSION TITLE
API Server not accessible in production

### DISCUSSION THREAD

**Discussion by wanclem** [serverpod/serverpod#3212] [Q&A]
Hi, I'm having trouble accessing the API server in a Kubernetes cluster.

I've set up an `HTTPRoute` and an associated `Service` but am encountering an issue where the API server endpoints are not accessible.

Here are my configurations:

#### `httproute.yaml`
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app-server-dev
  namespace: servers
  labels:
    app: app-server-dev
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - "flutter-api.myapp.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1
      backendRefs:
        - name: app-server-dev
          port: 8080
          namespace: servers
    - matches:
        - path:
            type: PathPrefix
            value: /v1/health
      backendRefs:
        - name: app-server-dev
          port: 8082
          namespace: servers
```

####  `service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: app-server-dev
  namespace: servers
  labels:
    app: app-server-dev
spec:
  selector:
    app: app-server-dev
  ports:
    - protocol: TCP
      port: 8080
      name: api
      targetPort: 8080 # API server
    - protocol: TCP
      port: 8082
      name: web
      targetPort: 8082 # Web server
```

When I visit the health check endpoint:
`https://flutter-api.myapp.com/v1/health
`
I receive a successful response.

However, when my client tries to connect to the API:

```dart
var client = Client('https://flutter-api.myapp.com/v1/',
    authenticationKeyManager: FlutterAuthenticationKeyManager())
  ..connectivityMonitor = FlutterConnectivityMonitor();
```

I receive the following error from the network console:

`Endpoint v1 not found`

Here's how I defined my web server routes:

```dart
void _manageWebServerRoutes(Serverpod pod) {
  pod.webServer.addRoute(
    RouteStaticDirectory(serverDirectory: 'static', basePath: '/'),
    '/*',
  );
  pod.webServer.addRoute(HealthCheckRoute(), '/v1/health');
}

```

**Health Check Route Implementation**
```dart
import 'dart:io';
import 'package:serverpod/serverpod.dart';

class HealthCheckRoute extends Route {
  @override
  Future<bool> handleCall(Session session, HttpRequest request) async {
    request.response.statusCode = HttpStatus.ok;
    request.response.write('OK');
    await request.response.close();
    return true;
  }
}
```
What could I be doing wrong?

Thanks so much for serverpod!
