### DISCUSSION TITLE
Help me deploy my serverpod app to railway (the right way) so I can open source it!

### DISCUSSION THREAD

**Discussion by Coffiie** [serverpod/serverpod#3349] [Q&A]
Hi.

I have a working Flutter web app and a serverpod backend. The problem is that I have no prior experience in deployment and I prefer to deploy to railway.app as it has a free tier so I can test my app there.

After failing to deply several times the proper way, I am turning to serverpod discussion for help

My app is already deployed on railway.app but I had to hardcode some things and for that reason I have to switch my repo from public to private so that I don't end up exposing sensitive server configurations.

Here's what I did:
- Created a file called `configs.dart` with content

```
import 'package:serverpod/serverpod.dart';

class Configs {
  static final serverpodConfig = ServerpodConfig(
    apiServer: ServerConfig(
      port: 8080, //original config
      publicScheme: 'https', //original config
      publicHost: 'api.examplepod.com', //original config
      publicPort: 443, //original config
    ),
    database: DatabaseConfig(
    //this is where I added my railway config
      host: 'Host',
      port: 0000,
      user: 'User',
      password: 'password',
      name: 'name',
    ),
    webServer: ServerConfig(
      port: 8082, //original config
      publicScheme: 'https', //original config
      publicHost: 'app.examplepod.com', //original config
      publicPort: 443, //original config
    ),
  );
}
```

In order to set these configs I use this line to set the config:
```
final pod = Serverpod(
    args,
    Protocol(),
    Endpoints(),
    config: Configs.serverpodConfig, //<--- Setting the configs mentioned above
    authenticationHandler: auth.authenticationHandler, 
  );
 ```

Now to securely reference these settings inside the `production.yaml` file and to make the Github repo open source, I need to use the railway.app provided variables.

Railway provides me following variables that I have referenced in the `production.yaml` file

```
apiServer:
  port: 8080
  publicHost: $RAILWAY_PUBLIC_DOMAIN
  publicPort: 443
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: insights.examplepod.com
  publicPort: 443
  publicScheme: https

webServer:
  port: 8082
  publicHost: app.examplepod.com
  publicPort: 443
  publicScheme: https

database:
  host: $PGHOST
  port: $PGPORT
  name: $PGDATABASE
  user: $PGUSER
  password: $PGPASSWORD #<-- Added the field "password" on my own and referenced the Railway provided variable
  requireSsl: true

redis:
  enabled: false
  host: redis.private-production.examplepod.com
  port: 6379

# Configuration for the main server
server:
  port: $PORT
  address: 0.0.0.0
```

While deploying it gives me this error:
```
SERVERPOD version: 2.4.0, dart: 3.7.0 (stable) (Wed Feb 5 04:53:58 2025 -0800) on "linux_x64", time: 2025-03-24 18:26:39.408131Z

mode: development, role: maintenance, logging: normal, serverId: default

Unhandled exception:
Exception: Missing database password.
#0      new DatabaseConfig._fromJson (package:serverpod_shared/src/config.dart:330:7)
#1      new ServerpodConfig.loadFromMap (package:serverpod_shared/src/config.dart:131:26)
#2      new ServerpodConfig.load (package:serverpod_shared/src/config.dart:186:30)
#3      Serverpod._initializeServerpod (package:serverpod/src/server/serverpod.dart:344:25)
#4      new Serverpod (package:serverpod/src/server/serverpod.dart:317:5)
#5      run (package:discord_server/server.dart:33:15)
#6      main (file:///app/bin/main.dart:6:3)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:313:33)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:12)
```

I am hoping that someone has deployed before to Railway and I would really like some help here. 

Thank you so much

**Comment by Isakdl** [comment]
Have you taken a look at the docs for [how to configure Serverpod](https://docs.serverpod.dev/concepts/configuration)?

Normally you would put the database password in the `passwords.yaml` file. 

Like so:

```yaml
production:
  database: 'production_password'
```

You can also configure every single setting by environment variables if you want to, this way you do not need to dynamically populate the yaml file, instead you just supply the envs. 

For example to configure the database password you can set the varialbe `SERVERPOD_DATABASE_PASSWORD`, see the linked docs for the full list of all available configurations!

**Reply by Coffiie** [reply]
Yes I have read the configuration part, but what I don't understand is, how will Railway understand the Environment variables? 

The problem is that where will this password load from? As I am deploying from the code in my github repo, and it does not have the `passwords.yaml` file pushed. If I push, isn't that going to be another security problem?

**Reply by Coffiie** [reply]
After changing the `production.yaml` file's database field

```
database:
  host: $PGHOST
  port: 13099
  name: $PGDATABASE
  user: $PGUSER
  password: $SERVERPOD_DATABASE_PASSWORD
  requireSsl: true
 ```
 
 It still does not work.
