### DISCUSSION TITLE
How to insert/return data with relation

### DISCUSSION THREAD

**Discussion by robpot95** [serverpod/serverpod#355] [Q&A]
Hi,

i'm new to Serverpod and i wonder how can i insert data with relation. I've read through the docs. But i could not find anything alike.

Table:
```
class: Advert
table: advert
fields:
  description: String
  adress: String
```
```
class: Item
table: item
fields:
  advertId: int, parent=Advert
  price: int
```

So if i would like to insert Item which has the parent Advert and item which expect an ```advertId```
How will i return an ```item```with the parent ```Advert```
