### DISCUSSION TITLE
Database update script

### DISCUSSION THREAD

**Discussion by stantemo** [serverpod/serverpod#364] [Ideas]
Hi,
This is my first post so firstly I would like to thank you guys at Serverpod for this great backend. Such an awesome job and it's not even at 1.0 yet ❤️ Secondly, damn you for making me re-write my backend once more 😅 
I've been testing Serverpod for a few days now and boy it really speeds up my development. 💨 Heja Sverige (Go Sweden go)

My idea and reason for this post is that once the backend is going into production, it's not that straight forward to make changes to the database table structure. Basically it requires db-knowledge.

Yes I know I can create additional tables and copy that newly generated SQL-code from the tables.pgsql but that also makes it less clear of what part is from the initial setup and what part is from a later change.

So my idea is that is to add a "version" attribute to the yaml-file that indicates if the modification requires an alter to the table (script created in a table_vX.pgsql-file) or if it should be in the initial-setup script (tables.pgsql).

For instance this would be my initial script for creating a users-table, indicated by the 1 in table_version. If version is omitted 1 is implied.
```
class: User
table: users
version: 1
fields:
  name: String
  email: String
  hair_color: String
```

A few months later I want to do to do three changes.
1. separate the name-column into surname and lastname (rename name-column and create a lastname-column)
2. add a totally new column
3. delete an existing column
So I add the following to my yaml-file.
```
class: User
table: users
version: 1
fields:
  name: String
  email: String
  hair_color: String
version: 2
fields:
  name -> surname: String
  lastname: String
  gender: int
  hair_color: null
```

- The -> indicates that the column should be renamed. Splitting the name and store them in separeate columns is then up to the developer to handle.
- gender: int adds the column to the end of the table (just like it currently does)
- null as type removes the column.
Everything else in the table is left as is.

The auto generated class should take all versions in consider when created.

I don't know if this is possible to implement but it would be of greate use and the threshold for developers not familiar with backend management would be reduces.
