### DISCUSSION TITLE
Storing id instead of serialized object

### DISCUSSION THREAD

**Discussion by stantemo** [serverpod/serverpod#366] [General]
I noticed that when referencing another class in the yaml-file the fully serialized object is stored with the object referencing it when saving to the database.

```
class: User
table: users
fields:
  name: String
  toys: List<Toy>
```

```
class: Toy
table: toys
fields:
  name: String
  brand: String
```

The toys column would the be populated as

`{"class":"Toys","data":{"id":1,"name":"Barbie","brand":"Mattel Inc."}}`

For each user having a Babrie in their toys collection.

Wouldn't this approach potentially crash the app/server when making changes to the Toy-class since it's not reflected in the serialized object? It would also make the data inconsistent since the Toys-table could be updated, eg. fixing a typo, without it reflected in each user referencing that toy.

Would it be possible to store the reference as a list of Id's instead?

EDIT:
Haven't tested circular references yet but I guess that won't perform very well.
Doing a family tree app where someone is both sibling and parent to the same person won't be possible if the whole object is serialized when storing.
