### DISCUSSION TITLE
Pagination in Get Request

### DISCUSSION THREAD

**Discussion by tusharbhambere** [serverpod/serverpod#393] [Q&A] [answered]
How to get Paginated Data?

**Comment by vlidholt** [comment, marked as answer]
You can get paginated data from the database by using the `offset` and `limit` arguments of the `find` method.

```dart
var companies = await Company.find(
  tCompany,
  where: (t) => ...,
  offset: 200,
  limit 50,
);
```

It's up to you how you want to pass that to your client, but one way is to set up a custom serializable object for that which you can return from your search method:

```yaml
class: CompanySearchResult
fields:
  companies: List<Company>
  page: int
```
