### DISCUSSION TITLE
How to show my `app.example.com` page in `example.com`?

### DISCUSSION THREAD

**Discussion by yahu1031** [serverpod/serverpod#436] [Q&A] [answered]
So, to develop the web server we need to access the `8082` port in development env, where we need to access `app.mydoamin.com` in production. But how could I show my website in `mydomain.com` by default?

**Comment by vlidholt** [comment, marked as answer]
You will need to modify the `config.auto.tfvars` file in your aws terraform scripts.

Set:
`use_top_domain_for_web = true` 

And you may also want to change the `subdomain_web` to:
`subdomain_web      = "www"`

Also configure your `config/production.yaml` to point to the correct domain:

```yaml
webServer:
  port: 8082
  publicHost: example.com
  publicPort: 443
  publicScheme: https
```

**Comment by yahu1031** [comment]
And in `production.yaml`, 
```yaml
webServer:
  port: 8082
  publicHost: example.com
  publicPort: 443
  publicScheme: https
```

this will let you directly access the webserver with the main domain `example.com`
