### DISCUSSION TITLE
is it yaml or windows doesnt support

### DISCUSSION THREAD

**Discussion by kazerdira** [serverpod/serverpod#529] [Q&A]
It is my first day using serverpod but i am ok with using flutter ,
i try to understand with some tutorials of codeX channel from youtube , 
after writing a yaml file like this

class: Article

fields:
  title: String
  content: String
  publishedOn: DateTime
  isPrime: bool

I am getting this error 
WARNING! Windows is not officially supported yet. Things may or may not work as expected.

Running serverpod generate.
Found 1 error.

Error on line 1, column 1 of lib\src\protocol\article.yaml: The top level object in the class yaml file must be a Map.
  ╷
1 │
  │ ^
  ╵

Done.

**Comment by yahu1031** [comment]
@kazerdira Line 1 must not be empty or space before the class

**Comment by yahu1031** [comment]
Also can you please share a screenshot.

**Comment by kazerdira** [comment]
[
![serverpod](https://user-images.githubusercontent.com/103287463/210008527-c086b4a8-405b-4b2d-9b9b-7f893b2e74c8.png)
](url)

**Reply by yahu1031** [reply]
Looks like you are not using the latest version. Try `v0.9.21`.

**Reply by kazerdira** [reply]
thank you so much , i upgrade the flutter to last version .

**Reply by yahu1031** [reply]
So fixed right? If it does, then mark it as answered.

**Comment by yahu1031** [comment]
The first line is an empty line
```yaml
# Considering the first line is empty/whitespace (This comment will be removed while code generation)

class: Example

# Add the table key, if this class represents a row in the database.
#table: example

# The fields (and columns if connected to the database) of the class. Supported
# types are `bool`, `int`, `double`, `String`, `DateTime`, and any other
# generated classes. You can also add lists of objects and types have support
# for null safety. Eg. `List<int>?` or `List<MyOtherClass?>`.
fields:
  name: String
  data: int
```

Console
```console
WARNING! Windows is not officially supported yet. Things may or may not work as expected.


Running serverpod generate.

Done.

Serverpod code generation exited
```
