### DISCUSSION TITLE
Is there a way to change the HTTP response status codes?

### DISCUSSION THREAD

**Discussion by AvoMandjian** [serverpod/serverpod#571] [Q&A] [answered]
lets say I want to create a user and the email is unique in the database, when the client enters an email that already exists, i want to send my response with HTTP status code 400, with a model/json that contains a title and message to be displayed in a snackbar

**Comment by vlidholt** [comment, marked as answer]
The way to achieve a similar result with Serverpod is to create a response object.

```yaml
class: CreateAccountResponse
fields:
  success: bool
  failReason: String? # Or use a code or enum here, whichever you prefer
```

Then you return the response in your method call:

```dart
Future<CreateAccountResponse> createAccount(Session session, String email, String otherOptionsEtc) async {
  // Attempt to create account
  return CreateAccountResponse(
    success: false,
    failReason: 'Duplicate account',
  );
}
