### DISCUSSION TITLE
Protocolfile definition

### DISCUSSION THREAD

**Discussion by fischerscode** [serverpod/serverpod#626] [Ideas]
It would be create if we could simplify the parsing the yaml files in the `protocol` directory.

I think it would be great to define a the structure of those files in a yaml/json schema. Then we could use this to validate and maybe even parse the yaml files (maybe this would be the job of a new package). Additionally, the schema could be used for validation / auto-completion in an editor (vscode).

As a next step there could even be a Serverpod VSCode extension.

Additionally I think it would be best if there was a easy / short / dense format for the classes (the current one) and an extended one, where the type all the additional parameters (like `parent`) are defined in a map. *This would not be a breaking change.*

**Comment by yahu1031** [comment]
@fischerscode I'm just thinking to create a ticket on this 😅. Thanks for having our back(ideas) 🙏

**Reply by fischerscode** [reply]
I almost added this to my serialization PR a few month back, but then I decided it was already large enough 😆

**Comment by yahu1031** [comment]
Not asking to change but hoping this is one of the better solutions to understand and generate a better pgsql and models scripts

```yaml
class: Community
table: community
fields:
  - name: name
    type: String
  - name: description
    type: String?
  - name: created
    type: DateTime
  - name: city
    type: String
  - name: country
    type: String
  - name: location
    type: Location
  - name: creator
    type: String
  - name: updated
    type: DateTime
  - name: communityId
    type: String
    # primary_key: true
primary_key: communityId
indexes:
  - name: community_id_idx
    fields: communityId
    unique: true
foreign_keys:
  - columns: [location]
    referenced_table: location
    referenced_columns: [locationId]
    on_delete: CASCADE
    on_update: CASCADE
```
