### DISCUSSION TITLE
Where is the documentation to deploy Flutter web app to AWS?

### DISCUSSION THREAD

**Discussion by Frank1016** [serverpod/serverpod#678] [Q&A] [answered]
I can follow ServerPod Documentation to deploy the server successfully to AWS, but couldn't find any instructions to deploy Flutter web app also to AWS using Github and Terraform. I was trying to clone thte official Pixorama demo project to see how to achieve this purpose, but maybe because it's kind of outdated or lack of documentation, I met a lot of issues such as "502 bad gateway" and Dart SDK version issue and couldn't make it work.

I'm wondering, is there another good serverpod example to show how to deploy both the server and web app to AWS using Github and Terraform?

**Comment by vlidholt** [comment]
We should definitely add a tutorial for this!

**Reply by jason-downs** [reply]
I still think this would be a good idea. In my opinion, at this point there's more than enough guides/tutorials on how to set up your project, create basic models & endpoints, etc., all the same stuff again in various formats, but little to nothing on topics like this that will inevitably come up once people have moved beyond the basics of setting up their serverpod project.

**Comment by eamnicoletti** [comment, marked as answer]
Try following these steps:

1. create the build web script `scripts/build_web`: 
```
#!/bin/sh

# Makes sure we break the script on any error.
set -e

# Build the web app.

cd example_web
flutter build web --release --web-renderer canvaskit
cd ..

# Copy the build files into the web/app diretory.
sudo rm -rf example_server/web/app
sudo cp -r example_web/build/web example_server/web/app

# Move the index.html file into the templates directory.
sudo mkdir -p example_server/web/templates
sudo mv example_server/web/app/index.html example_server/web/templates/index.html
```

2. Add the Flutter block below to your `.github/workflows/deployment-aws.yml` (change de Flutter SDK version to yours):
```
[...]
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.16.9

      - name: Compile Flutter web app
        shell: bash
        run: |
          scripts/build_web
[...]
```

3. Setup a default page to the web root: 
 3.1. Change the directory name from `'static'` to `'app'`, in `server.dart` :
```
 pod.webServer.addRoute(
    // RouteStaticDirectory(serverDirectory: 'static', basePath: '/'),
    RouteStaticDirectory(serverDirectory: 'app', basePath: '/'),
    '/*',
  );
```

3.2. At `lib/src/web/widgets/default_page_widget.dart` I change the name of the Widget to `IndexPageWidget`, you can keep the same, but change the `name` value from `'default'` to `'index'`:
```
class IndexPageWidget extends Widget {
  IndexPageWidget() : super(name: 'index');
}

// class DefaultPageWidget extends Widget {
//   DefaultPageWidget() : super(name: 'default') {
//     values = {
//       'served': DateTime.now(),
//       'runmode': Serverpod.instance!.runMode,
//     };
//   }
// }
```
