### DISCUSSION TITLE
Is there any way to use dynamic data type in protocol in my serverpod project ?

### DISCUSSION THREAD

**Discussion by Shubhamdsingh** [serverpod/serverpod#684] [Q&A] [answered]
Can we use Dynamic data type in protocol ?

**Comment by fischerscode** [comment, marked as answer]
It is not supported. As a workaround, you can create a wrapper:

```yaml
class: MyDynamicWrapper
fields:
  type1: Type1?
  type2: Type2?
```
