### DISCUSSION TITLE
Switch Serverpod version from stable to main

### DISCUSSION THREAD

**Discussion by damienissa** [serverpod/serverpod#704] [Q&A] [answered]
I'm trying to switch version using:
```yaml
serverpod:
    git:
      url: https://github.com/serverpod/serverpod.git
      ref: main
      path: packages/serverpod
```

And I got an error:
```bash
dart pub get
Resolving dependencies...
Error on line 33, column 11: Invalid description in the "serverpod" 
pubspec on the "serverpod_shared" dependency: "../serverpod_shared" 
is a relative path, but this isn't a local pubspec.
   ╷
33 │     path: ../serverpod_shared
   │           ^^^^^^^^^^^^^^^^^^^
   ╵
exit code 65

```

@yahu1031 @vlidholt Do you have any ideas about how I need to change it?

The same problem when I try to activate Serverpod CLI: 

```bash
dart pub global activate -sgit https://github.com/serverpod/serverpod.git --git-path tools/serverpod_cli/
Package serverpod_cli is currently active at version 1.0.1.
Error on line 32, column 11: Invalid description in the "serverpod_cli" 
pubspec on the "serverpod_shared" dependency: "../../packages/serverpod_shared" 
is a relative path, but this isn't a local pubspec.
   ╷
32 │     path: ../../packages/serverpod_shared
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

**Comment by vlidholt** [comment, marked as answer]
If you are not using the stable version, the recommended way is to use Serverpod as a submodule in your project. Place it in a directory called `vendor` (this is also where you should place any additional external dependencies). Then you can reference the Serverpod packages with relative paths and it is also easy to control which version of Serverpod you are using by updating the submodule.

```
myproject
  |- myproject_flutter
  |- myproject_client
  |- myproject_server
  |- vendor
     |- serverpod
```

**Reply by lukehutch** [reply]
I think you mean to `git clone` serverpod to `vendor/`?

What is the correct way to refer to `vendor/serverpod` if you do this? I am doing the following, but I have had a number of strange runtime errors trying to use serverpod this way, so I'm wondering if I'm missing a build step or something. I'll report bugs as I nail things down.

```yaml
dependencies: 
  flutter: 
    sdk: flutter
  serverpod_flutter: ^1.0.1
  serverpod_auth_shared_flutter: ^1.0.1
  serverpod_auth_google_flutter: ^1.0.1
  serverpod_auth_apple_flutter: ^1.0.1

dependency_overrides:
  serverpod_client:
    path: ../vendor/serverpod/packages/serverpod_client
  serverpod_flutter:
    path: ../vendor/serverpod/packages/serverpod_flutter
  serverpod_auth_client:
    path: ../vendor/serverpod/modules/serverpod_auth/serverpod_auth_client
  serverpod_auth_shared_flutter:
    path: ../vendor/serverpod/modules/serverpod_auth/serverpod_auth_shared_flutter
  serverpod_auth_google_flutter:
    path: ../vendor/serverpod/modules/serverpod_auth/serverpod_auth_google_flutter
  serverpod_auth_apple_flutter:
    path: ../vendor/serverpod/modules/serverpod_auth/serverpod_auth_apple_flutter
```
