### DISCUSSION TITLE
Are there Expressions for Lists?

### DISCUSSION THREAD

**Discussion by fleeser** [serverpod/serverpod#736] [Q&A]
Currently I am storing the IDs of guests of an event inside a List:

```
class: Event
table: events
fields:
  guests: List<int>
```

I would like to be able to filter based on that. Something like:

`Event.find(session, where: (t) => t.guests.contains(id));`

Extra: I was also trying to figure out how to directly compare these lists to for e.g. the following approach where the Friendship between two users is stored inside a table with a List<int> for the two IDs 

```
class: Friendship
table: friendships
fields:
  users: List<int>
  created: DateTime
```

instead of having something like:

```
class: Friendship
table: friendships
fields:
  userOne: int
  userTwo: int
  created: DateTime
```

to use it something like this:

`Friendship.find(session, where: (t) => t.users.equals(userIds));`
