### ISSUE TITLE
Report an error if the same field is used twice in an index

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1084]
**Describe the bug**

The following protocol file is considered valid by the analyzer / generator, but will generate invalid SQL as it will try to create an index referencing the same field twice.

```yaml
class: Note
table: note
fields:
  name: String
indexes:
  index_format:
    fields: name, name
    unique: true
```

**Expected behavior**
Give an error
