### ISSUE TITLE
Minimal type verification of field datatypes in the protocol

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1086]
**Is your feature request related to a problem? Please describe.**
If you use invalid characters in the type of a field, the generator will crash.

Example:

```yaml
class: Example
fields:
  name: invalid-type
```

**Describe the solution you'd like**
The generator should report an error.
