### ISSUE TITLE
No validation of index type is made, enforce only valid index types.

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1089]
**Is your feature request related to a problem? Please describe.**
The following yaml uses an invalid type for the index, but the analyzer is not reporting any errors for this, resulting in invalid SQL code being generated.

```yaml
class: Example
table: example
fields:
  name: String
indexes:
  name_index:
    fields: name
    unique: true
    type: invalid
```

**Describe the solution you'd like**
The analyzer should only allow the following strings in the type field: `btree`, `hash`, `gist`, `spgist`, `gin`, and `brin`.

If any other value is found an error should be reported.
