### ISSUE TITLE
Do not allow the parent key word on a field, if the class does not have a table defined

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1090]
**Is your feature request related to a problem? Please describe.**

The following protocol definition will generate valid dart but the syntax is logically incorrect as the parent keyword only makes sense in the context of a database table. We should let the user know they most likely forgot to add the "table" keyword to the class.

```yaml
class: Example
fields:
  referenceId: int, parent=parent_table
```

**Describe the solution you'd like**
Report an error that the class has no table defined.
