### ISSUE TITLE
Do not allow the parent keyword in conjunction with the api scope.

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1091]
**Is your feature request related to a problem? Please describe.**

The following yaml will generate invalid SQL code. We will create a table without the `referenceId` field but then try to add a foreign key to the same field.

```yaml
class: Example
table: example
fields:
  referenceId: int, parent=parent_table, api
```

**Describe the solution you'd like**
Give an error if the api scope is defined together with a parent relation.
