### ISSUE TITLE
Do not allow duplicated enum values in protocol

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1092]
**Is your feature request related to a problem? Please describe.**
Currently you can define multiple enum values with the same name. This will cause the generator to fail when formatting the invalid dart code.

Example:
```yaml
enum: Example
values:
  - name
  - name
```

**Describe the solution you'd like**
Report an error if the same string is used twice in the values list.
