### ISSUE TITLE
Verify that datatypes from modules exists

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1097]
**Is your feature request related to a problem? Please describe.**

If I try to use a datatype from a module, but forgot to add the module in my config file, the generate command will crash. 

```yaml
class: Example
fields:
   user: module:auth:UserInfo
```

**Describe the solution you'd like**
Print a helpful error instead.
