### ISSUE TITLE
Map with a List in the protocol throws an error by the code generator.

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1104]
**Describe the bug**
If you declare a field datatype with a map that has a nested list the type converter throws an error.

**To Reproduce**

```yaml
class: Example
fields:
  name: Map<String, List<int>>
```

`$ serverpod generate`
`Error on line 3, column 9 of lib/src/protocol/example.yaml: Invalid Type`

**Expected behavior**
Should generate the classes

**Serverpod versions**
 -  _CLI Version:_ 1.1.1.
 - _Library version:_ 1.1.1.
