### ISSUE TITLE
Error location in comma seperated string inside the protocol not accurate

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1115]
**Describe the bug**
The source location of errors in a field string reports the entire string instead of the specific location the error occurred.

Example:
```yaml
class: Example
fields:
  name: String, invalidKey
```
Where `invalidKey` should be marked as the source of the error, but the entire range `String, invalidKey` is reported.

**Expected behavior**
Report the specific key and/or value that was the problem!
