### ISSUE TITLE
Less restrictive naming of yaml enum values.

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1128]
Allow yaml enums to follow a less restrictive syntax.

Examples of values we should consider valid:

```yaml
enum: Example
values:
 - androidCTV
 - M
```
 
We should consider implementing warnings in the analyzer and report the following as warnings instead of errors.

```yaml
enum: Example
values:
 - FULLCAPS
 - PascalCase
 - snake_case
```

----

             ^^ Ha! I guess the strict lowerCamelCase is a good thing for this as well, which seems a bit funky with some of the names but will help prevent simple user error like changing the case of a value and having it break the database:

```
Error on line 3, column 5 of lib/src/protocol/platform_type.yaml: Enum values must be lowerCamelCase.
  ╷
3 │   - androidCTV
  │     ^^^^^^^^^^
  ╵
```

_Originally posted by @tgrushka in https://github.com/serverpod/serverpod/issues/885#issuecomment-1625831189_
