### ISSUE TITLE
Simplified unique fields in protocol

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1141]
**Feature: unique fields**
Allow the simplified unique syntax to create unique indexes on fields.

Using the default index name of `table_name__field_name__unique_idx` should guarantee that the index name it self is unique in the db. 

If the index name `table_name__field_name__unique_idx` is manually used at the same time as we generate the same name we need to give an error.

Example:
```yaml
class: Example
table: example
fields:
  exampleField: String, unique
```

Would have the same result as the current way:
```yaml
class: Example
table: example
fields:
  exampleField: String
indexes:
  example_example_field_unique_idx
    fields: exampleField
    unique: true
```

This would save a lot of typing for the programmer.
