### ISSUE TITLE
Introduce scope key in protocol, depricate database and api

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1142]
**Is your feature request related to a problem? Please describe.**

Replace the `database` and `api` keywords with the `scope` keyword in the protocol.

Example:
```yaml
class: Example
table: example
fields:
  name: String, scope=database
```

```yaml
class: Example
table: example
fields:
  name: String, scope=api
```

We should maybe also rethink the words `database` and `api` as they do not always make sense. For example if you have a serverOnly class here you want to make sure a field is not stored as a column in the database.

Example:
```yaml
class: Example
serverOnly: true
table: example
fields:
  custom: CustomClass, scope=api
```

In this situation we wouldn't actually serialize this object for the client, hence api is not strictly true.

This feature would deprecate the old database and api keys, we can earliest remove them in 2.0.

**Comment by Isakdl** [comment]
Revised solution:

introduce negated boolean keys in the protocol files by adding a !

example: !api and api=false would be the inverse of api or api=true

Instead of transient we use persist but this is true by default and you have to negate the key to opt out of database storage.

Scope: one of serverOnly or all, in the future we can also add clientOnly.

```yaml
class: Example
table: example
fields:
  name: String, scope=serverOnly, !persist # server side only but not stored in the db
  age: int, !persist # visible to the client, but not stored in the db
  nick: String, scope=serverOnly # server side only AND is stored in the db
  url: String # visible to client and stored in db
```
