### ISSUE TITLE
Support automatic audit fields for database entries.

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1143]
**Feature: audit fields**

A common use case is to know when and who created / updated a specific entry in the database. To make this easier and more convenient to implement we should support this functionality out of the box. 

We should support the following types:
* __createdAt__ a special functionality to manage a DateTime field to be set only when the row is created.
* __updatedAt__ a special functionality to let Serverpod manage a DateTime field to be updated each time the row is updated.
* __createdBy__ a special functionality to let Serverpod manage the field and link it to a user_id. Take this value from the session object, if the field is not nullable an error would be thrown if there is no authenticated user in the session object.
* __updatedBy__ a special functionality to let Serverpod manage the field and link it to a user_id. Changes every time the row is updated.

Example:
```yaml
class: Audit
table: audit # The keywords below require a table
fields:
  createdAt: createdAt
  updatedAt: updatedAt
  createdBy: createdBy # If no authenticated user, updating/inserting will fail
  updatedBy: updatedBy
```

```yaml
class: Audit
table: audit
fields:
  createdBy: createdBy? # set to null if no authenticated user
  updatedBy: updatedBy?
```

We treat these as special datatypes where `createdAt` and `updatedAt` maps to `DateTime` & `createdBy` and `updatedBy` maps to `int`.

A `table` must be defined on the class or else this type should give an error.
