### ISSUE TITLE
Introduce `relation` keyword in protocol

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1144]
**Is your feature request related to a problem? Please describe.**

Deprecate the current usage of the keyword `parent` and replace it with the keyword `relation`.

The `relation` keyword has nested values and can support multiple keywords inside it. We achieve that by this syntax: `relation()` where any nested keywords appear inside the '()'.

To fully support the current usage of the `parent` keyword the following syntax needs to be implemented and supported:

```yaml
class: Example
table: example
fields:
  parentId, int, relation(parent=parent_table)
```
