### ISSUE TITLE
Allow to configure the referenced field in a relation

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1147]
**Is your feature request related to a problem? Please describe.**
Allow a relation to specify the referencing field of another table/object. If this value is not set we simply use the default id field. 

The reference field can be configured by specifying reference=<field> which always defaults to reference=id. This will set the column we use as a foreign key in the relationship between objects.

If the referenced field is not of the same datatype as the local field with the relation an error should be reported.

Example valid usage:
```yaml
# user.yaml
class: User
table: user
fields:
  addressReference: int, relation(parent=address, reference=zip)

# address.yaml
class: Address
table: address
fields:
  zip: int
```

Example invalid usage:
```yaml
# user.yaml
class: User
table: user
fields:
  addressReference: String, relation(parent=address, reference=zip)

# address.yaml
class: Address
table: address
fields:
  zip: int
```
