### ISSUE TITLE
Add scalar references to relations 

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1150]
**Is your feature request related to a problem? Please describe.**
Add the keyword `field` to a relation. This keyword should reference another field in the class that has the same datatype as the `reference` field of the related table/object. 

In this situation we also expect the current fields datatype to match the referenced parent. I.E. the referenced class has a table we want to look at. Hence for this situation we allow the user to omit the `parent` keyword.

This issue focuses only on the field keyword and how it interacts with the other fields. The query side of this feature is handled in a subsequent issue (). As a result of this the fields datatype must be optional (for now).

Example:
```yaml
# company.yaml
class: Company
table: company
fields:
  name: String

# employee.yaml
class: Employee
table: employee
fields:
  companyId: int
  company: Company?, relation(field=companyId)
```

```yaml
# employee.yaml
class: Employee
table: employee
fields:
  company: Company?, relation(optional)
```

Where this would have the same meaning:
`company: Company?, relation(field=companyId, parent=company, reference=id)`

In the above example the field `company` is not visible in the database, there is no column called `company` inside the `employee` table. It would function as if we set the scope to `api` on this field.

The `companyId` has the reverse rule, this field has an implicit scope of `database` where we hide it from the api by default.

The user can always opt in to show the id anyway by setting the scope to all.

Example: 
```yaml
# employee.yaml
class: Employee
table: employee
fields:
  companyId: int, scope=all
  company: Company?, relation(field=companyId)
```
