### ISSUE TITLE
It's not possible to depend directly upon the git main version of `serverpod_client`

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1153]
**Describe the bug**

I'm trying to run my project using a git fork of Serverpod. Given the dependency

```
dependencies:
  serverpod_client: 1.1.0

dependency_overrides:
  serverpod:
    path: ../../serverpod/packages/serverpod_client
```

I get the error

```console
# dart pub get
Resolving dependencies...
Error on line 5, column 7 of ../../serverpod/packages/serverpod_client/pubspec.yaml: "name" field doesn't match expected name "serverpod".
  ╷
5 │ name: serverpod_client
  │       ^^^^^^^^^^^^^^^^
  ╵
exit code 65
```

The same extra (invalid) `name` key is in several yaml files, about 6 of them IIRC.
