### ISSUE TITLE
Support 1:n relations in protocol

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1154]
**Is your feature request related to a problem? Please describe.**
Allow 1:n relationships to be specified in the protocol using the `relation` keyword.

Example of protocol:
```yaml
# company.yaml
class: Company
table: company
fields:
  name: String
  employees: List<Employee>, relation

# employee.yaml
class: Employee
table: employee
fields:
  companyId: int,
  company: Company?, relation(field=companyId)
  name: String
```

```yaml
# company.yaml
class: Company
table: company
fields:
  name: String
  employees: List<Employee>, relation

# employee.yaml
class: Employee
table: employee
fields:
  companyId: int, relation(parent=company)
  name: String
```

If a list type has a relation keyword then it should be hidden from the database, (no column created). If there is no relation keyword the list is treated as a json value.

If a list has a relation keyword, there needs to be a relation inside the referenced class.

The analyzed representation of the classes has to include all this information (to be passed to the code generator).
