### ISSUE TITLE
Support explicit m:n relations in the protocol

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1156]
**Is your feature request related to a problem? Please describe.**
```yaml
# post.yaml
class: Post
table: post
fields:
  title: String
  categories: List<CategoriesOnPosts>, relation

# category.yaml
class: Category
table: category
fields:
  name: String
  posts: List<CategoriesOnPosts>, relation

# categories_on_posts.yaml
class CategoriesOnPosts
table categories_on_posts
fields:
  postId, int
  post: Post, relation(field: postId)
  categoryId: int
  category: Category, relation(field: categoryId)
indexes:
  unique_relation_idx
     fields: postId, categoryId
     unique: true
```

Assuming we have implemented 1:1 and 1:n relations this issue should mostly be resolved by it self. What could be interesting is discussing a more lightweight syntax to create the unique constraint on the id's. Alternatively allow us to define the id of a class as the union of two other ids, in the above case `postId` and `categoryId`.
