### ISSUE TITLE
Support implicit m:n relations in the protocol 

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1157]
**Is your feature request related to a problem? Please describe.**
Allow the definition of an implicit m:n relation. See related issue on explicit relations: https://github.com/serverpod/serverpod/issues/1156. The end result of an implicit relation should be the same as the explicit one but where you do not need to specify the relation table as we create this automatically instead.

```yaml
# post.yaml
class: Post
table: post
fields:
  title: String
  categories: List<Category>, relation

# category.yaml
class: Category
table: category
fields:
  name: String
  posts: List<Post>, relation
```
