### ISSUE TITLE
Serverpod generate --watch, sometimes crashes even when we detect known errors in protocols

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1164]
**Bug**

Consider this invalid protocol:
```yaml
class: Example
table: example
fields:
  name: String, api, parent=Invalid
```
If we run `serverpod generate` the command will crash even though we have detected the errors in the analyzer. 

**Describe the solution you'd like**
Do not crash.
