### ISSUE TITLE
Verify that a field has the same datatype as the id of the foreign relation.

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1171]
**Describe the solution you'd like**
Right now you are allowed to specify a relationship in the protocol even if there is a mismatch in types between the id of the parent and the current field. This means we are generating invalid SQL code if the programmer defines a relation with a mismatch of the types.

Example

```yaml
class: Example
table: example
fields:
  parentId: DateTime, parent=parent_table
```

Where `parent_table` has an id of type `int`.

**Solution**
Check that the types match if they don't give an error.
