### ISSUE TITLE
Allow spaces between '= sign' and key/values in protocol files

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1177]
If you add spaces in the protocol value `parent=parent_table` you get an error from the analyzer because we include the whitespace in the name.

Example:
```yaml
class: Example
table: example
fields:
  parentId: int, parent = parent_table
```

This syntax should be allowed, the solution is to trim the names.
