### ISSUE TITLE
Support named relations

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1231]
**Is your feature request related to a problem? Please describe.**
We currently cannot support multiple relations between two protocols as the relation then becomes ambiguous. As described in this PR: https://github.com/serverpod/serverpod/pull/1229.

The solution is to introduce the ability to name our relations to be able to resolve the reference. 

Proposed syntax:
```yaml
class: Example
table: example
field:
  parent: User?, relation(name=ParentRelation)
  child: User?, relation(name=ChildRelation)
```

Setting the name is only required if there is multiple references AND the other side of the relation is a List, I.E. one to many. 

We are also going to need this feature to support many-to-many relations.
