### ISSUE TITLE
Support referencing module classes in relations

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1232]
**Is your feature request related to a problem? Please describe.**
Extend the relationship syntax to also resolve module classes / tables.

Today this does not work:

```yaml
class: Example
table: example
field:
  userInfo: module:auth:UserInfo?, relation
```

Where `module:auth:UserInfo` would reference the `UserInfo` object in the auth module.
