### ISSUE TITLE
Duplicated keys are reported twice

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1284]
**Describe the bug**
Duplicated keys are reported twice by the validator.

Example:

```yaml
class: Example
fields:
  name: String, api, api
```
