### ISSUE TITLE
Support orderBy on relation attributes in one to one relations

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#1293]
**Is your feature request related to a problem? Please describe.**
When querying the database I would like to be able to order the response on properties of nested relations for the entities I'm fetching.

Given the following entities:

``` yaml
class: Player
table: player
fields:
  name: String
  score: Score?, relation
```

``` yaml
class: Score
table: score
fields:
  points: Int
```

There should be support to order Citizens by the points in their Score.

**Describe the solution you'd like**
There should be typed support for creating a orderBy query.

The following syntax should be supported:
``` dart
Future<List<Citizen>> findPlayersOrderedByScore(
    Session session,
    String name,
  ) async {
    return await Citizen.find(
      session,
      orderBy: Citizen.t.score.points,
    );
  }
  ```

**Describe alternatives you've considered**
-

**Additional context**
-
