### ISSUE TITLE
The code generator silently fails if a field name is used that collide with predefined method names.

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1319]
**Describe the bug**
Example protocol:

```yaml
class: Example
table: example
fields:
  count: int
  insert: String
  findById: int
```

`count`, `insert`, `findById` are all methods on the generated class and will collide with the fields, the code generator gives no error but the outputted code does not compile.

**Expected behavior**
Give a clear error
