### ISSUE TITLE
It is possible to configure an invalid relation definition

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1321]
**Describe the bug**

A relation can be defined on the foreign key name simultaneously as the object pointing to the same field. This can lead to diverging configurations for the relation.

Example of the invalid syntax that gives no errors:

```yaml
class: Example
table: example
fields:
  exampleId: int, relation(parent=random_table)
  example: Example, relation(field=exampleId)
```

In this example, exampleId has the parent table set to `random_table`. The `example` field has the parent table set to `example` but is also using `exampleId` as the foreign key holder for the relation. Hence we have an invalid configuration of the relation.
 
**Expected behavior**
Do not allow the relation keyword to be used on the foreign key field if there is another relation field pointing to it.

**Version**
Only affects the main branch.
