### ISSUE TITLE
Problem with deserialization of DateTime? fields.

### ISSUE THREAD

**Issue by juanjosegarcia98** [serverpod/serverpod#1339]
**Describe the bug**
I want to deserialize data from a `Map<String,dynamic>` to a generated class using the generated `Protocol()` `SerializationManager` class.

```dart
MySerializableClass.fromJson(mapWithData, Protocol());
```
I have a class like this:
```yaml
class: MySerializableClass
table: my_serializable_class
fields:
  name: String
  webSite: String
  users: List<User>?, api
  createdAt: DateTime?
  updatedAt: DateTime?
```
When i do that, if I have `null` fields in the DB record belonging to _nullable_ fields in my class of type `DateTime?` (I've only had problems with fields of this type so far) the function crashes and throws me the following error:
```
type 'DateTime' is not a subtype of type 'String'
```

It also happened when I filled that fields manually, inserting the timestamps in the DB. EDIT: This case also happens with non-nullable `DateTime` fields manually modified in the DB. 

Thank you.

**Serverpod versions**
 -  _CLI Version: 1.1.1
 - _Library version: 1.1.1

**Platform information**
I'm running the server locally in Fedora 38 and testing the endpoints with HTTP requests. **I'm hosting my DB in Supabase**.
