### ISSUE TITLE
Support `add`, `remove` and `replace` relations on existing 1:1 relations

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1340]
**Relational operations**
Imagine the following protocol setup:

```yaml
#employee.yaml
class: Employee
table: employee
fields:
  company: Company?, relation

#company.yaml
class: Company
table: company
fields:
  name: String
```

To make it more convenient to create a relation between two existing rows in this scenario we should add additional methods on the generated `Employee` class. To help reduce the issue of naming collisions we should namespace these methods as well.

Proposal for the name space is using `db` as the keyword.

```dart
var employee = await Employee.findById(...);
var company = await Company.findById(...);

// To add
await Employee.db.add.company(employee, company);

// To replace
var anotherCompany = await Company.findById(...);
await Employee.db.replace.company(employee, anotherCompany);

// To remove
await Employee.db.remove.company(employee); // No required company param as we already know which company to remove in a 1:1 relation.
```

The `add`, `remove`, `replace` keywords are always generated for each class, the variables inside are created only if there is a 1:1 relation where the current side has an actual object. 

In the following scenario:
```yaml
#employee.yaml
class: Employee
table: employee
fields:
  addressId: int
  address: Address?, relation(name=employee_address, field=adressId)

#company.yaml
class: Address
table: address
fields:
  street: String
  employee: Employee?, relation(name=employee_address)
```

All the methods would be generated on both sides and you should be able to add an employee to an address or vice versa. The real implementation would have to still inject the id on the correct side.

```dart
await Address.db.add.employee(address, employee);
```
This would in the background modify the employee tables `addressId` column as it is there the relation is stored.
