### ISSUE TITLE
Specifying list relation creates invalid dart code.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#1381]
**Describe the bug**
Defining an entity with an implicit list relation generates invalid dart code.

**To Reproduce**
1. Define the following two entities.

``` yaml
class: Citizen
table: citizen
fields:
  name: String
```

``` yaml
class: Citizen
table: citizen
fields:
  name: String
```
2. Generated the project

**Expected behavior**
Generated dart code should not contain any errors.

**Screenshots**
<img width="674" alt="Screenshot 2023-09-20 at 18 00 59" src="https://github.com/serverpod/serverpod/assets/137198655/1a81085e-e82d-46b2-b3e4-e7c4c5ccadb6">
