### ISSUE TITLE
Generate findBy<FieldName> methods based on unique indexing

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1396]
**Is your feature request related to a problem? Please describe.**
Automatically create `findBy` methods in protocol classes if the field has a unique index. This makes it quite convenient to query fields that we can guarantee that there are only 0 or 1 entries. 

Example:

```yaml
class: Example
table: example
fields:
  email: String
indexes:
  email_unique_idx:
    unique: true
```

```dart
var example = await Example.db.findByEmail(session, 'name@example.com');
```

**Describe the solution you'd like**
To make this easy to generate, we should add a bool in our internal representation for the fields on our classes to denote whether the said field is unique.
