### ISSUE TITLE
Possible to configure an implicit n:m relation.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#1506]
**Describe the bug**
There is no yaml validation that prevents us from configuring an implicit n:m relation.

However, implicit n:m relations are not yet supported by Serverpod and therefore we should give an error on this.

**To Reproduce**
1. Create the following entity files:

```yaml
# post.yaml
class: Post
table: post
fields:
  title: String
  categories: List<Category>, relation

# category.yaml
class: Category
table: category
fields:
  name: String
  posts: List<Post>, relation
```
2. Generate project.
3. Unexpected behavior happens.

**Expected behavior**
An exception with an error message occurs informing about what the issues is.
