### ISSUE TITLE
Selectivly opt out of migration system per model file

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1681]
**Is your feature request related to a problem? Please describe.**
As a programmer, you may want to opt out of the migration system for various reasons such as using some unsupported use-case.

**Describe the solution you'd like**
Add a new keyword to classes with a table defined, to tag the model as manually managed.

Suggestion:
```yaml
class: Example
table: example
migration: manual
fields:
  name: String
```

```yaml
class: Example
table: example
migration: automatic
fields:
  name: String
```

Where the default would be `automatic` if nothing is written.
