### ISSUE TITLE
API only relationships are broken 

### ISSUE THREAD

**Issue by kieran-novarca** [serverpod/serverpod#1778]
**Describe the bug**
It seems that when you have a class that is defined in the yaml files which is not a database class (API only), that relates to another class which is also not a database class (API only), the generated code is causing errors. 

**To Reproduce**
1. Create a protocol file for a class that does not have the table attribute
2. Create a second protocol file for a class that does not have the table attribute
3. Add a field to one of the classes that is of the type of the other class you created 
4. Run serverpod generate, your generated code will error. 

**Expected behavior**
No errors

**Screenshots**
![image](https://github.com/serverpod/serverpod/assets/120369588/70f42c41-6d25-4249-b218-d3890d5989d6)
![image](https://github.com/serverpod/serverpod/assets/120369588/aacb071b-615f-4552-8c87-802d0787ad9f)

**Serverpod versions**
 -  _CLI Version: 1.2
 - _Library version: 1.2

**Comment by SandPod** [comment]
Hi, thanks for the report @kieran-novarca.

Could you provide examples of protocol files that causes this issue?

**Comment by Isakdl** [comment]
I'm not able to reproduce this issue with the following files:


```yaml
class: FieldInputType
fields:
  valueType: InputValueType
  name: String
  description: String
  thumbnailUrl: String
```

```yaml
class: InputValueType
fields:
  name: String
```
