### ISSUE TITLE
Defining data validation rules directly in `.spy.yaml` files

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1809]
### Discussed in https://github.com/serverpod/serverpod/discussions/1792

<div type='discussions-op-text'>

<sup>Originally posted by **egonm12** January 21, 2024</sup>
Implement a system for defining data validation rules directly in `.spy.yaml` files used by Serverpod. This feature would enable developers to specify constraints and validation rules for each field of a data model.

Example implementation:

```yaml
class: User
table: user
fields:
  name:
    type: String
    validation:
      notEmpty: true
  password:
    type: String
    validation:
      size:
        min: 8
        max: 20
    email:
      type: String
      validation:
        pattern: "^[a-zA-Z0-9._]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$"
```

</div>
