### ISSUE TITLE
Relation queries with table names exceeding n characters do not include relation data

### ISSUE THREAD

**Issue by freppps** [serverpod/serverpod#1816]
**Describe the bug**
When performing relation queries the returned data doesn’t include the related data even if it's specified. I've done some testing and it seems to be related to table names exceeding n characters.

To replicate the issue, follow the steps below. You can get the example to work by removing the `_with_long_name` prefix.

Is it possible that this issue could be connected to https://github.com/serverpod/serverpod/issues/1708? Just speculating here.

**To Reproduce**
1. Create a fresh project `serverpod create mypod`
2. Add the below models and endpoint
3. Run `serverpod generate` and `serverpod create-migration`
4. Start docker containers `docker compose up --build --detach`
5. Apply migration `dart run bin/main.dart --role maintenance --apply-migrations`
6. Run the endpoint method `create` to insert test data to the database
7. Run the endpoint method `get` and inspect the returned data. No instance of IngredientToResource is returned (the variable resources) - see screenshot. 

**Expected behavior**
Relational data should be included in the result.

**Screenshots**
![image](https://github.com/serverpod/serverpod/assets/41991003/4741c9c1-7492-4098-96b1-d23c1a3eda27)

**Serverpod versions**
 -  _CLI Version: Serverpod version: 1.2.1
 - _Library version: serverpod: 1.2.1

**Platform information**
MacOS
App running in Flutter Web

**Additional context**

**Models definitions**
```
class: Recipe
table: recipe_with_long_name
fields:
  name: String
  ingredients: List<RecipeToIngredient>?, relation

class: RecipeToIngredient
table: recipe_to_ingredient_with_long_name
fields:
  amount: int
  ingredient: Ingredient?, relation(onUpdate=NoAction, onDelete=NoAction)

class: Ingredient
table: ingredient_with_long_name
fields:
  name: String
  resources: List<IngredientToResource>?, relation

class: IngredientToResource
table: ingredient_to_resource
fields:
  amount: int
  resource: Resource?, relation(onUpdate=NoAction, onDelete=NoAction)

class: Resource
table: resource
fields:
  name: String
```

**Endpoint**
```
class TestEndpoint extends Endpoint {
  Future<List<Recipe>> get(Session session) async {
    final parts = await Recipe.db.find(
      session,
      include: Recipe.include(
        ingredients: RecipeToIngredient.includeList(
          include: RecipeToIngredient.include(
            ingredient: Ingredient.include(
              resources: IngredientToResource.includeList(
                include: IngredientToResource.include(
                  resource: Resource.include(),
                ),
              ),
            ),
          ),
        ),
      ),
    );

    return parts;
  }

  Future<void> create(Session session) async {
    final insertedResource = await Resource.db.insertRow(session, Resource(name: 'name'));

    final ingredient = Ingredient(
      name: 'name',
      resources: [
        IngredientToResource(amount: 1, resourceId: insertedResource.id!),
      ],
    );

    final insertedIngredient = await Ingredient.db.insertRow(session, ingredient);
    final insertedIngredientToResource = await IngredientToResource.db.insertRow(session, ingredient.resources!.first);
    await Ingredient.db.attachRow.resources(session, insertedIngredient, insertedIngredientToResource);

    final recipe = Recipe(
      name: 'name',
      ingredients: [
        RecipeToIngredient(amount: 1, ingredientId: insertedIngredient.id!),
      ],
    );

    final insertedRecipe = await Recipe.db.insertRow(session, recipe);
    final insertedRecipeToIngredient = await RecipeToIngredient.db.insertRow(session, recipe.ingredients!.first);
    await Recipe.db.attachRow.ingredients(session, insertedRecipe, insertedRecipeToIngredient);
  }
}
```
