### ISSUE TITLE
[Bug][Models] Indexes do not allow referencing module-extended Model IDs

### ISSUE THREAD

**Issue by kevinpthorne** [serverpod/serverpod#1851]
**Describe the bug**
When extending a module-defined model (e.g. the auth `UserInfo` model) into your own model (e.g. `Player`), the ID of `Player` cannot be references in a Junction table index declaration.

**To Reproduce**
One way to repro:
1. Start a new serverpod project
2. Install serverpod auth module
3. Logically extend the auth module's UserInfo table following https://docs.serverpod.dev/concepts/database/relations/modules and call it `Player` for example
```yaml
class: Player
table: player
fields:
  userInfo: module:auth:UserInfo?, relation
  games: List<GameRegistration>?, relation(name=player_registration)
indexes:
  user_info_id_unique_idx:
    fields: userInfoId
    unique: true
```
4. Create another model called `Game`
```yaml
class: Game
table: game
fields:
  name: String
  joinCode: String
  players: List<GameRegistration>?, relation(name=game_registration)
```
5. Create a many-to-many relationship between `Game` and `Player` called `GameRegistration` (follow https://docs.serverpod.dev/concepts/database/relations/many-to-many)
```yaml
class: GameRegistration
table: game_registration
fields:
  gameSession: Game?, relation(name=game_registration)
  player: Player?, relation(name=player_registration)
indexes:
  game_registration_index:
    fields: gameSessionId, userInfoId
    unique: true
```
6. Run `serverpod generate`; observe the error:
```
Error on line 8, column 13 of lib/src/models/game_registration.spy.yaml: The field name "userInfoId" is not added to the class or has an api scope.
  ╷
8 │     fields: gameSessionId, userInfoId
  │             ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```
Variations of using `playerId` or `userInfoId` produce the same error

**Expected behavior**
Since the `Player` model declares an index on `userInfoId`, `GameRegistration` should be no different and be able to reference it

**Serverpod versions**
 -  _CLI Version:_ 1.2.1
 - _Library version:_ 1.2.1

**Platform information**
CLI ran on Linux Manjaro -- not running within Flutter.

**Additional context**
This is my first use of serverpod, so I might be missing some small detail. I will remove the `GameRegistration` index for now, but will become a significant problem in the future.
