### ISSUE TITLE
Updates to documentation around relations.

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#1863]
### Discussed in https://github.com/serverpod/serverpod/discussions/1830

<div type='discussions-op-text'>

<sup>Originally posted by **sulthanalihsan** January 27, 2024</sup>
I often encounter schema examples in the documentation like this:

implicit one-to-many relationship

company.yaml
```
class: Company
table: company
fields:
  name: String
  employees: List<Employee>, relation
```

employee.yaml
```
class: Employee
table: employee
fields:
  name: String
```
  
However, I'm curious why when I tried it, an error occurred: 
`Fields with model relations must be nullable (e.g., employees:List<Employee>?)`</div>
