### ISSUE TITLE
Add support for immutable models

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#1864]
There should be a way to declare models to be immutable. Perhaps by adding a keyword to the model files:

```yaml
class: MyModel
immutable: true
fields:
  myField:int
```

Then we can also support equality and hash.
