### ISSUE TITLE
FormatException: Invalid type code in substitution variable SQL INJECTION RISK

### ISSUE THREAD

**Issue by yourny** [serverpod/serverpod#1924]
**Describe the bug**
When inserting a row via "MyModel.db.insertRow" I get an exception.

**To Reproduce**
1. Have a model with a field of type String
2. Insert a row with a value containing '@', i.e. "Studio@40: Stylish & modern 1 bedroom apartment.",  "TheBamboo@Grass: Cool & minimalistic condo studio"
3. Get an exception.

**Expected behavior**
Strings inserted MUST NOT be interpreted due to safety risks concerning SQL Injection.

**Serverpod versions**
 -  _CLI Version:_ 1.2.3
 - _Library version:_ 1.2.3

**Platform information**
MacOS, running Serverpod local Docker Image

**Comment by yourny** [comment]
I did some research an it seems to be due to the way postgres packages handles placeholder values.

**Comment by yourny** [comment]
This is a super big problem for us since we can not prevent hotels having @ signs in their name.
Would love a hotfix :)

**Comment by Isakdl** [comment]
Thank you for the added context, will take a look asap.

**Comment by Isakdl** [comment]
I made a quick test but I'm not able to replicate. What exception do you get?

Test code: 
```dart
import 'package:serverpod/database.dart';
import 'package:serverpod_test_server/src/generated/protocol.dart';
import 'package:serverpod_test_server/test_util/test_serverpod.dart';
import 'package:test/test.dart';

void main() async {
  var session = await IntegrationTestServer().session();

  tearDown(() async {
    await UniqueData.db.deleteWhere(session, where: (_) => Constant.bool(true));
  });

  test(
      'Given a model with a string containing a "@" then the data is inserted into the database without errors.',
      () async {
    var expectedEmail = 'info@serverpod.dev';

    var data = UniqueData(number: 1, email: expectedEmail);

    var inserted = await UniqueData.db.insertRow(session, data);

    expect(inserted.email, expectedEmail);
  });
}
```

Model:
```yaml
class: UniqueData
table: unique_data
fields:
  number: int
  email: String
indexes:
  email_index_idx:
    fields: email
    unique: true
```

**Comment by yourny** [comment]
Does this run a real query? 

Here's the query I found in database.dart that would be passed to postgres package:

```sql
INSERT INTO "rate_hawk_hotel" ("address", "checkInTime", "checkOutTime", "email", "factsId", "frontDeskTimeEnd", "frontDeskTimeStart", "hotelChain", "rateHawkId", "images", "isClosed", "kind", "latitude", "longitude", "metapolicyExtraInfo", "metapolicyStructId", "name", "paymentMethods", "phone", "postalCode", "regionId", "serpFilters", "starRating") VALUES ('40 Nicklaus Street, Pretoria', '14:00:00', '10:00:00', 'dlangley@netactive.co.za', 2717171, null, null, 'No chain', 'studio40_stylish_modern_1_bedroom_apartment', '["https://cdn.worldota.net/t/{size}/content/e2/a4/e2a4a97838b25733c05964c785b20c70766bb676.jpeg"]', FALSE, 'Hotel', -25.770170211791992, 28.378559112548828, 'This property will not accommodate hen, stag or similar parties. Please inform Studio@40: Stylish & modern 1 bedroom apartment. in advance of your expected arrival time. You can use the Special Requests box when booking, or contact the property directly with the contact details provided in your confirmation. Managed by a private host', 2717168, 'Studio@40: Stylish & modern 1 bedroom apartment.', '[]', null, '0081', 4506, '["has_internet","has_parking","has_meal","kitchen"]', 0) RETURNING *
```

**Comment by yourny** [comment]
Here's the yaml I had serverpod generate the DB from:

```yaml
class: RateHawkHotel
table: rate_hawk_hotel
fields:
  address: String
  ### Hotel's amenities (e.g. "Health and Safety Measures" or "Beauty and wellness").
  amenityGroups: List<RateHawkAmenityGroup>?, relation(name=rate_hawk_amenity_group_rate_hawk_hotel)
  ### Check-in time. The local time is specified in HH:MM:SS format.
  checkInTime: String
  ### Check-out time. The local time is specified in HH:MM:SS format.
  checkOutTime: String
  ### Hotel's description.
  descriptionStruct: List<RateHawkDescriptionItem>?, relation(name=rate_hawk_description_item_rate_hawk_hotel)
  email: String?
  facts: RateHawkFacts?, relation(onDelete=Cascade)
  ### Reception closing time. The local time is specified in HH:MM:SS format.
  frontDeskTimeEnd: String?
  ### Reception opening time. The local time is specified in HH:MM:SS format.
  frontDeskTimeStart: String?
  ### Hotel chain name.
  hotelChain: String
  ### Hotel's unique ID at Emerging Travel Group. This ID needs to be provided during availability calls if necessary.
  rateHawkId: String
  ### Hotel's images.
  ### {size} - size of the image that you can request. List of available values:
  ### • 100x100 — crop
  ### • 1024x768 — fit
  ### • 120x120 — crop
  ### • 240x240 — crop
  ### • x220 — fit-h
  ### • x500 — fit-h
  ### crop - image is fit by the width, and is cut equally from the bottom and top till the middle part (of height's value)
  ### fit-h - image is fit by the height
  ### fit - image is fit into the rectangle of the size in question
  images: List<String>
  ### Indicates whether the property is closed.
  isClosed: bool
  ### Hotel type. Possible values:
  ### - Resort
  ### - Sanatorium
  ### - Guesthouse
  ### - Mini-hotel
  ### - Castle
  ### - Hotel
  ### - Boutique_and_Design
  ### - Apartment
  ### - Cottages_and_Houses
  ### - Farm
  ### - Villas_and_Bungalows
  ### - Camping
  ### - Hostel
  ### - BNB
  ### - Glamping
  ### - Apart-hotel
  kind: String
  ### Geographical latitude of the hotel.
  latitude: double
  ### Geographical longitude of the hotel.
  longitude: double
  ### Hotel's extra information (is the same as the section "Extra info" from hotel pages on the core website). Taxes and fees that are not included in the booking price may be shown in this field.
  ### The data from this param must be shown.
  metapolicyExtraInfo: String?
  ### Additional accommodation conditions (is the same as the section "Hotel policies" from hotel pages on the core website). Taxes and fees that are not included in the booking price may be shown in this field.
  ### The data from this param must be shown.
  metapolicyStruct: RateHawkMetapolicyStructInfo?, relation(onDelete=Cascade)
  name: String
  ### The cards accepted by the hotel (in case pay at the hotel).
  ### List of available values:
  ### • unspecified — unspecified
  ### • american_express — American Express
  ### • cash — Cash
  ### • china_unionpay — China UnionPay
  ### • diners_club — Diners Club International
  ### • euro_mastercard — Euro/Mastercard
  ### • jcb — JCB
  ### • maestro — Maestro
  ### • mastercard — Mastercard
  ### • switch_maestro — Switch (Maestro)
  ### • visa — Visa
  ### • visa_debit — Visa Debit
  ### • vise_delta — Visa Delta
  ### • visa_electron — Visa Electron
  ### • pro100 — Pro100
  paymentMethods: List<String>
  phone: String?
  postalCode: String?
  region: RateHawkRegion?, relation
  roomGroups: List<RateHawkRoomGroup>?, relation(name=rate_hawk_room_group_rate_hawk_hotel)
  ### List of amenities for the hotels' selection based on a cumulative set of features from all of the hotels' rates and common hotels' features.
  ### There is a request which returns all available room amenities and definitions (serp_filters key):
  ### https://api.worldota.net/api/b2b/v3/hotel/static/
  serpFilters: List<String>
  ### Hotel rating on a scale from 1 to 5 ("star" rating). 0 means no rating is available.
  ### min_value: 0
  ### max_value: 5
  starRating: int
indexes:
  rh_hotel_rh_facts_idx:
    fields: factsId
  rh_hotel_rhid_idx:
    fields: rateHawkId
    unique: true
  rh_hotel_rh_metapolicy_struct_info_idx:
    fields: metapolicyStructId
  rh_hotel_rh_region_idx:
    fields: regionId
```
