### ISSUE TITLE
!!! Nullable Custom Object in Models

### ISSUE THREAD

**Issue by AndryHTC** [serverpod/serverpod#1947]
**Describe the bug**
The "models" feature in Serverpod 1.2.4 incorrectly treats nullable fields as required. This issue breaks the expected behavior of nullability in models, affecting type safety from Flutter to Server.

**To Reproduce**
1. Define a model with both nullable and non-nullable fields in Serverpod using YAML configuration.
```yaml
class: UtenteDto
fields:
  uuid: String
  negozio: Negozio?
  nomeVisualizzato: String
  photoUrl: String?
  ruolo: String
  email: String
  firebaseUid: String?
```
2. Generate Dart code for the model.
3. The generated Dart code incorrectly requires nullable fields to be non-null.
```dart
UtenteDto._({
    required this.uuid,
    required this.negozio, // Should not be required
    required this.nomeVisualizzato,
    this.photoUrl,
    required this.ruolo,
    required this.email,
    this.firebaseUid,
});
```

**Expected behavior**
Nullable fields like `negozio` and `photoUrl` should not be marked as `required` in the generated Dart code, allowing for null values as defined in the YAML configuration.

**Serverpod versions**
- _CLI Version:_ 1.2.4
- _Library version:_ 1.2.4

**Platform information**
- Issue observed on both Windows and Mac platforms.
- Serverpod version 1.2.4 is used.

**Additional context**
This issue disrupts the intended use of nullability in Serverpod models, potentially leading to runtime errors or forcing unnecessary workarounds in code that relies on these models.
