### ISSUE TITLE
List object relation not being saved automatically

### ISSUE THREAD

**Issue by itsJoKr** [serverpod/serverpod#2031]
**Describe the bug**
I have one-to-many relation, one `CustomConfig` having many `CustomFieldConfig`:

```yaml
class: CustomConfig
table: custom_config
fields:
    useRestock: bool
    useLots: bool
    useDecimals: bool
    customFields: List<CustomFieldConfig>?, relation
```

```yaml
class: CustomFieldConfig
table: custom_field_config
fields:
    entity: int
    name: String
    required: bool
    options: List<String>?
    type: CustomFieldType
    
```

**To Reproduce**
1. Insert a `CustomConfig` with `List<CustomFieldConfig>` populated

**Expected behavior**
I expected that when saving `CustomConfig` it will auto-save the one-to-many relation for `CustomFieldConfig`. But it's not doing that. Am I supposed to manually manage that? I'm so confused because the docs imply that it's automatically managed for me.

**Screenshots**
- Here's proof that I'm sending non-empty List<CustomFieldConfig>

<img width="994" alt="Screenshot 2024-03-20 at 22 40 25" src="https://github.com/serverpod/serverpod/assets/11093480/d2ca21b5-e119-41af-9a88-504461dcd851">

- Here's screenshot showing that items are null, and in fact there are no rows in the table at all
<img width="1210" alt="Screenshot 2024-03-20 at 22 44 46" src="https://github.com/serverpod/serverpod/assets/11093480/409a938d-d625-43d0-a35c-d9dcbe989f14">

**Serverpod versions**
 -  _CLI Version:_ 1.2.5
 - _Library version:_ 1.2.5

**Platform information**
Running on Macbook Pro M1
