### ISSUE TITLE
Documentation is not clear on how to use enums

### ISSUE THREAD

**Issue by ebitogu** [serverpod/serverpod#2054]
I've gone through the documentation and I still can't get enums to work. The documentations are not clear enough on enums.

Is the following not supposed to be the approach or is it wrong?
```yaml

enum: Animal
serialized: byName
values:
  - dog
  - cat
  - bird

class: Example
fields:
  name: String
  data: int
  animal: Animal
```

When I ran `serverpod generate` I get several errors.

Can anyone please show me how to define and tie enums to a model?
