### ISSUE TITLE
Custom lint rules to help with serverpod development

### ISSUE THREAD

**Issue by dkbast** [serverpod/serverpod#2068]
The existing VSCode extension ships a language server for the serverpod yaml files - I would like to add more lint rules / code actions to the dart side. This can either be solved by building a dart analyzer plugin (e.g. using custom_lint from invertase) or by adding this to the serverpod language server and exposing the quick fixes etc through this lsp.

I will use this issue to collect ideas I have while developing with serverpod, adding numbers for easier reference:

1) "Where Queries" need to use "&" instead of "&&" - took me a while to figure this out, would be a highest priority lint
2) When accessing the userId in an Endpoint Method, suggest setting "requireLogin" to true ("info" lint)
3) Some lints around queries would be nice (there should be some best practices for this somewhere)
4) Some kind of "helper" for working with Datetime - the server seems to be running in UTC the client runs in local time

**Comment by SandPod** [comment]
Completely understand the problem you are trying to solve.

Our LSP server only analyses endpoint dart classes and model files. Adding rules to the current system would, therefore, only be applied there.

For us to provide a more general system where you could apply lint rules anywhere in the project, we would need to expand our LSP analysis to the full packages.

This makes me think this is almost more of an ask for hooking in lint rules to the general Dart analyzer than hooking into our LSP. The benefit is that we would also avoid duplicate analysis of the full project.

Are there any drawbacks in providing your linting rules to the dart analyzer directly?

**Comment by dkbast** [comment]
I'm not 100% sure, but I believe that the analyzer plugins only work in the scope of the currently open file - not sure if it possible to check multiple files for conflicting keys etc with the current architecture of custom_lint. 

I'm also not sure if it is "that bad" if the codebase has two analyzers running, since that will already be the case with most IDEs which bring their own refactorings etc. Could be something to toggle on and off, or to hook into the already running instance of the dart analysis server (like custom_lint does).

**Comment by dkbast** [comment]
It looks like the first party analyzer plugin system is getting a rework and is ready soon - it seems to be relatively easy to convert `custom_lint` rules as described in this article: https://leancode.co/blog/migrating-to-dart-analyzer-plugin-system - see https://github.com/dart-lang/sdk/issues/53402 for the current state of the new plugin system.

**Comment by mathis6787** [comment]
@dkbast  Hey I just migrate to the first party package it when well except dart hooks are not supported yet the lint will work but you won't be able to run dart analyze if you have native hook in your project see : https://github.com/dart-lang/sdk/issues/62351.  I think the custom lint could be a great things if we could add custom linting rules to .spy.yaml. for instance I have a base class like this :
``` yaml
class: BaseTenantEntity
fields:
  id: UuidValue, defaultModel=random_v7
  createdAt: DateTime, default=now
  updatedAt: DateTime, default=now
```

I extend it  in several model: 
```yaml 
class: Asset
table: asset
extends: BaseTenantEntity
fields:
  assetId: String
  barcode: String?
  item: Item?, relation(onDelete=cascade)
  location: Location?, relation(onDelete=restrict)
  tenantId: UuidValue?, relation(parent=tenant, onDelete=cascade), scope=serverOnly
indexes:
  asset_tenant_asset_id_idx:
    fields: tenantId, assetId
    unique: true
  asset_item_idx:
    fields: itemId, createdAt
  asset_location_idx:
    fields: locationId
  asset_item_location_idx:
    fields: itemId, locationId
```

I would like to throw a lint error if    tenantId: UuidValue?, relation(parent=tenant, onDelete=cascade), scope=serverOnly
 is not present .
