### ISSUE TITLE
Erroro when run serverpod run

### ISSUE THREAD

**Issue by infolinematrix** [serverpod/serverpod#208]
Starting Serverpod.
 • Automatic generate and reload are enabled.
 • Running Postgres and Redis in Docker container.

Spinning up serverpod generate (this can take a few seconds).
Starting Docker (for Postgres and Redis).
Waiting for Postgres on localhost:8090.
Waiting for Redis on localhost:8091.
Setup complete. Starting the server.

Unhandled exception:
type 'Null' is not a subtype of type 'Map<dynamic, dynamic>'
#0      new ServerpodConfig (package:serverpod_shared/src/config.dart:42:35)
#1      new Serverpod (package:serverpod/src/server/serverpod.dart:228:14)
#2      run (package:serverpod_server/server.dart:12:15)
#3      main (file:///home/subha/Desktop/mobileApp/serverpod/serverpod_server/bin/main.dart:6:3)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by anandsubbu007** [comment]
There is change serverpod server config file.
make sure it is updated

New Format

```

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http

# This is the database setup for your server.
database:
  host: localhost
  port: 8090
  name: subbu_shop
  user: postgres

# This is the setup for Redis.
redis:
  enabled: true
  host: localhost
  port: 8092
```
