### ISSUE TITLE
Doc comment generates differently between Windows and Linux

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#2120]
Generator gives different results on windows vs linux if there is an empty line between a doc comment and a field in a spy file.

**To Reproduce**

```yaml
class: Example
fields:
  ### This is a doc comment

  name: String
```

On Linux the output class contains the documentation comment above the field declaration but on Windows, it does not.

**Expected behavior**
The output should be consistent between platforms.

**Serverpod versions**
main
