### ISSUE TITLE
A field marked with `scope=serverOnly` is included in the client's `Protocol.deserialize` method.

### ISSUE THREAD

**Issue by birkineau** [serverpod/serverpod#2136]
**Describe the bug**
The type of a field marked with `scope=serverOnly` is included in the client's `Protocol.deserialize` method after running `serverpod generate`. The models below contain only the relevant fields.

The `UserTag` model is a server-only junction table for a m:n relationship between the `User` and `Tag` models.
```
class: UserTag
table: user_tag
serverOnly: true
fields:
  user: User?, relation(name=user_tag_user)
  tag: Tag?, relation(name=user_tag_tag)
indexes:
  user_tag_userId_tagId_unique_idx:
    fields: userId, tagId
    unique: true
```

A `User` has a field for the list of associated `Tag` entries. The field `tags` is marked as server-only,
```
class: User
table: user
fields:
  tags: List<UserTag>?, relation(name=user_tag_user), scope=serverOnly
```

A `Tag` has a field for the list of associated `User` entries. The model is defined with `serverOnly: true`.
```
class: Tag
table: tag
serverOnly: true
fields:
  users: List<UserTag>?, relation(name=user_tag_tag)
```

After running `serverpod generate`, the following check gets added to the protocol.dart file in the client project:

![image](https://github.com/serverpod/serverpod/assets/109599857/a189674e-f825-4498-91af-021ae83a3cc2)

However, since the model was marked as server-only, it doesn't exist in the client project, which prevents the project from compiling.

**Expected behavior**
Deserialization code for the `List<UserTag>` is not generated in the protocol.dart file, since the `UserTag` model is defined with `serverOnly: true` and all fields using the `UserTag` model are marked with `scope=serverOnly`.
