### ISSUE TITLE
Removing any entry in the envrionment configs results in a crash

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#2179]
# Bug

If the `redis` or any other configuration (even if redis is not enabled) is removed from the config the server crashes on startup. 

With an obscure error message 

```
Unhandled exception:
type 'Null' is not a subtype of type 'Map<dynamic, dynamic>'
```

 ## Expected behavior

Should not crash and should probably not be required unless this feature is enabled.

If the feature is enabled but the config is missing, give a reasonable error message.

### Discussed in https://github.com/serverpod/serverpod/discussions/2089

<div type='discussions-op-text'>

<sup>Originally posted by **AslamThachapalli** March 31, 2024</sup>
The purpose of docker is to make a pg db up and running right. 
Let's say I don't want to use docker, but a hosted db from, say neon.tech or aiven, for the dev environment. Isn't it straight forward and possible?

I added the following config in development.yaml:
```yaml
database:
  host: ep-hottest-noice-a16o6wqg.ap-southeast-1.aws.neon.tech
  port: 5432
  name: ptest
  user: aslam.develop912%50gmail.comd

# This is the setup for Redis.
# redis:
#   enabled: false
#   host: localhost
#   port: 8091
```
and edited the passwords.yaml
```yaml
development:
  database: 'thisIsADummyPass'
  # redis: '5mXNVdStJLrTvVQTpvA8Sv_NaTuOBT_e'
```
But when I do `dart bin/main.dart --apply-migrations`, I am getting the following error:
```
Unhandled exception:
type 'Null' is not a subtype of type 'Map<dynamic, dynamic>'
#0      new ServerpodConfig (package:serverpod_shared/src/config.dart:65:9)
#1      new Serverpod (package:serverpod/src/server/serverpod.dart:271:14)
#2      run (package:mypod_server/server.dart:14:15)
#3      main (file:///Users/aslam/Programming/Serverpod/mypod/mypod_server/bin/main.dart:6:3)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
---
But when I tried with the docker setup everything was working fine though. Is there anything I am missing?</div>
