### ISSUE TITLE
Add a way to make a column unique in the .spy.yaml

### ISSUE THREAD

**Issue by qiqetes** [serverpod/serverpod#2180]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
```yaml
class: User
table: x_user
fields:
  email: String (unique=true)
  nickname: String
  fullName: String?
```
**Describe alternatives you've considered**
Do a manual migration.
