### ISSUE TITLE
An "empty" model with only id field in DB cause SQL syntax error on insert

### ISSUE THREAD

**Issue by nuumio** [serverpod/serverpod#2306]
**Describe the bug**

The following "simplest possible model" with no fields specified causes a SQL syntax error:

```yaml
class: IdOnly
table: id_only
fields: {}
```

Using that model, this code on server

```dart
IdOnly.db.insertRow(session, IdOnly());
```

causes the following unhandled exception:

```
Unhandled exception:
PostgreSQLSeverity.error 42601: syntax error at or near ")" 
package:postgres/src/connection.dart 520:18                     _PostgreSQLExecutionContextMixin._query
package:postgres/src/connection.dart 481:7                      _PostgreSQLExecutionContextMixin.query
package:postgres/src/connection.dart 549:22                     _PostgreSQLExecutionContextMixin.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 820:23                 _PgExecutionContextWrapper.mappedResultsQuery.<fn>
package:postgres_pool/postgres_pool.dart 746:27                 _PgExecutionContextWrapper._run
package:postgres_pool/postgres_pool.dart 819:12                 _PgExecutionContextWrapper.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 661:16                 PgPool.mappedResultsQuery.<fn>
package:postgres_pool/postgres_pool.dart 352:22                 PgPool.run.<fn>.<fn>
package:postgres_pool/postgres_pool.dart 451:27                 PgPool._useOrCreate
package:postgres_pool/postgres_pool.dart 423:14                 PgPool._withConnection.<fn>
package:executor/src/executor_impl.dart 61:19                   _Executor.scheduleTask
package:postgres_pool/postgres_pool.dart 351:18                 PgPool.run.<fn>
package:retry/retry.dart 131:16                                 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 349:14                 PgPool.run
package:serverpod/src/database/database_connection.dart 395:20  DatabaseConnection.mappedResultsQuery
package:serverpod/src/database/database_connection.dart 153:9   DatabaseConnection.insert
package:serverpod/src/database/database_connection.dart 167:18  DatabaseConnection.insertRow
===== asynchronous gap ===========================
package:postgres_pool/postgres_pool.dart 351:18                 PgPool.run.<fn>
package:retry/retry.dart 131:16                                 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 349:14                 PgPool.run
package:serverpod/src/database/database_connection.dart 395:20  DatabaseConnection.mappedResultsQuery
package:serverpod/src/database/database_connection.dart 153:9   DatabaseConnection.insert
package:serverpod/src/database/database_connection.dart 167:18  DatabaseConnection.insertRow
```

**To Reproduce**
1. Add the model shown above to server
2. Insert an instance that that model to database
3. See the error

For convenience I create a repo with reproduction code: https://github.com/nuumio/serverpod-repro-id-only-model-sql-error

Here's a direct link to server code causing the error: https://github.com/nuumio/serverpod-repro-id-only-model-sql-error/blob/main/id_only_model_sql_error_server/lib/server.dart#L42

**Expected behavior**
No exceptions thrown.

**Screenshots**
N/A

**Serverpod versions**
 -  _CLI Version:_  `Serverpod version: 1.2.7`
 - _Library version:_ `1.2.7`

**Platform information**
I'm running the server on Manjaro Linux.

**Additional context**
Be looking at it really quick, in this case [`DatabaseConnection.insert()` generates](https://github.com/serverpod/serverpod/blob/13795a7bd4c0cc5a03101b6f378cb914673046dd/packages/serverpod/lib/src/database/database_connection.dart#L149) following invalid SQL: `INSERT INTO "id_only" () VALUES () RETURNING *`

I'm not familiar with serverpod internals but maybe explicitly including `id` with `DEFAULT` value would solve this one. The generated SQL would then be `INSERT INTO "id_only" (id) VALUES (DEFAULT) RETURNING *`

Simple workaround is to have some DB column generating field in the model (like most models probably do). In reality I bumped into this when working on models and I tried my app when the models looked something like this:

```yaml
# container.yaml, still "id only"
class: Container
table: container
fields:
  items: List<Item>?, relation

# item.yaml
class: Item
table: item
fields:
  name: String
  containerId: int, relation(parent=container)
```

**Comment by Isakdl** [comment]
Hey @nuumio interesting setup, you are not supposed to be able to specify a yaml model without a field but you seem to have found a workaround for that restriction 😀.

The framework is currently built around the assumption that you have at least one field defined. 

What is your use case for having no fields at all?

**Comment by nuumio** [comment]
> Hey @nuumio interesting setup, you are not supposed to be able to specify a yaml model without a field but you seem to have found a workaround for that restriction 😀.
> 
> The framework is currently built around the assumption that you have at least one field defined.
> 
> What is your use case for having no fields at all?

Hi there! That `IdOnly` model was the simplest possible way to reproduce the error. I've added a more complete example to a separate branch in repro repo here: https://github.com/nuumio/serverpod-repro-id-only-model-sql-error/tree/example-models

Reproduction code is in [`id_only_model_sql_error_server/lib/server.dart`](https://github.com/nuumio/serverpod-repro-id-only-model-sql-error/blob/example-models/id_only_model_sql_error_server/lib/server.dart#L50).

Here are the example models:
```yaml
# item_list.spy.yaml. Has only id column in DB
class: ItemList
table: item_list
fields:
  items: List<ItemListEntry>?, relation(name=item_list_entries)

# item_list_entry.spy.yaml
class: ItemListEntry
table: item_list_entry
fields:
  itemListId: int, relation(name=item_list_entries, parent=item_list)
  itemId: int, relation(parent=item)
  amount: int

# item.spy.yaml
class: Item
table: item
fields:
  name: String
  # etc...

# shipping_crate.spy.yaml
class: ShippingCrate
table: shipping_crate
fields:
  # itemList is common in model containing items
  itemList: ItemList?, relation
  # Crate specific fields
  weight: double
  source: String
  destination: String

# warehouse.spy.yaml
class: WareHouse
table: warehouse
fields:
  # itemList is common in model containing items
  itemList: ItemList?, relation
  # Warehoure specific fields
  address: String
```

And here's ER diagram of `item_list` and `item_list_entry` tables combined into one image:
![id_only_model_sql_error_server_erd](https://github.com/serverpod/serverpod/assets/9162363/80c21744-9c13-43cb-8a68-959b85003d40)

So, the `item_list` table is the problematic one here and the example code throws the same exception as I described earlier when trying to add a new `ItemList`.

Basically, when I was working on the data model, it went like this: First I only had a `Warehouse` with a list of `Item`s. Then I needed to add `ShippingCrate` which would have the same kind of items as a `Warehouse`, and I might need to add more "container types" later - again with the same kind of items. So I thought that because items are always the same kind so collections of `Item`s would also be of the same kind -> I'll add a `ItemList` model which would represent these collections as a list of `ItemListEntry`s. At the moment `ItemList` only has field `items: List<ItemListEntry>?, relation(name=item_list_entries)` which doesn't generate any database columns so there's only an id column.

I hope you can get the idea from this example as I cannot share the actual project repo. The data model is still a work in progress and the problematic `ItemList` may still change but this is what I currently have.
