### ISSUE TITLE
Migrations don't work unless you add new fields to the bottom of the model entries

### ISSUE THREAD

**Issue by kieran-myopnotes** [serverpod/serverpod#2308]
**Describe the bug**
It appears that if you insert a new field into one of your model files between two existing fields, migrations don't work

**To Reproduce**
1. Create a model and give it two fields
2. Generate a migration and apply it
3. Change the model file and add a new field between the two original fields
4. Generate another migration 

**Expected behavior**
The generator should not care about the order of the fields when creating a migration. It would also be cool if migrations could also insert new columns in between existing columns to match the order in the model.

**Comment by SandPod** [comment]
Hey @kieran-myopnotes!

I can't seem to reproduce the issue.
Could you supply models used to reproduce the issue?

From this model: 

```yaml
class: Types
table: types
fields:
  anInt: int?
  aBool: bool?
  ```

I added a double field in the middle:

 ```yaml
class: Types
table: types
fields:
  anInt: int?
  aDouble: double?
  aBool: bool?
 ```

And could successfully create a migration that reflected the change:

```sql
--
-- ACTION ALTER TABLE
--
ALTER TABLE "types" ADD COLUMN "aDouble" double precision;
```
