### ISSUE TITLE
Can't pass serializable object in endpoint 

### ISSUE THREAD

**Issue by jackstefansky** [serverpod/serverpod#235]
I defined UserSession object in protocol directory. 
```
class: UserSession

table: user_session
fields:
  email: String
  passwordHash: String, database
  accessToken: String
  refreshToken: String
  accessTokenEnd: DateTime
```

Then I wanted to use it as a parameter in getUserData endpoint call:
```
  Future<UserDataResult> getUserData(
    Session session,
    UserSession userSession,
  ) async {
  
  ...
```

but server throws following exception when I call the endpoint with UserSession object:
```
METHOD CALL: auth.getUserData duration: 0ms numQueries: 0 authenticatedUser: null
type 'Null' is not a subtype of type 'UserSession'
#0      Endpoints.initializeEndpoints.<anonymous closure> (package:yummy_server/src/generated/endpoints.dart:62:21)
#1      Endpoints.initializeEndpoints.<anonymous closure> (package:yummy_server/src/generated/endpoints.dart:59:17)
#2      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:115:37)
<asynchronous suspension>
#3      Server._handleRequest (package:serverpod/src/server/server.dart:220:18)
<asynchronous suspension>
```

The docs say that it's possible to pass serializable object as a parameter.
I also have another endpoint that returns `UserSession` and it works like a charm. The problem only occurs when I try to pass the object in the constructor.
