### ISSUE TITLE
Bad state: Webserver is disabled

### ISSUE THREAD

**Issue by mtkgeek** [serverpod/serverpod#2486]
**Describe the bug**
I'm trying to deploy the server on a linux vps but I keep running into the error shown below
```
SERVERPOD version: 2.0.1, dart: 3.2.5 (stable) (Tue Jan 16 15:02:13 2024 +0000) on "linux_x64", time: 2024-07-13 08:48:29.758444Z
mode: production, role: monolith, logging: normal, serverId: default
#2      main (file:///app/bin/main.dart:6)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
Unhandled exception:
Bad state: Web server is disabled, supply a web server configuration to enable this feature.
#0      Serverpod.webServer (package:serverpod/src/server/serverpod.dart:121)
#1      run (package:mypod_server/server.dart:24)
#2      main (file:///app/bin/main.dart:6)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```
**To Reproduce**
Deploy serverpod using default production.yaml file

**Expected behavior**
It shouldn't throw the above error because my production.yaml looks accurate. There is a webserver section as shown below

```
production.yaml

# This is the configuration file for your production environment.
# Typically, you will want to route the traffic through a load balancer
# which adds SSL security through https. If you use Serverpod's standard
# Terraform scripts to deploy your server, all you need to change in
# this file is the examplepod.com domain name.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: https://k4ws4go.mydomain.com
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: https://k4ws4go.mydomain.com
  publicPort: 8081
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: https://k4ws4go.mydomain.com
  publicPort: 8082
  publicScheme: https

# This is the database setup for your servers. The default for the Google Cloud
# Engine Terraform configuration is to connect on a private IP address.
# If you are connecting on a public IP (e.g. on AWS or Google Cloud Run), you
# connect on the public IP of the database e.g. database.examplepod.com.
database:
  host: postgres
  port: 5432
  name: $POSTGRES_DB
  user: $POSTGRES_USER

# This is the setup for Redis. The default for the Google Cloud Engine Terraform
# configuration is to connect on a private IP address.
# If you are connecting on a public IP (e.g. on AWS or Google Cloud Run), you
# connect on the public IP of the database e.g. redis.examplepod.com.
redis:
  enabled: true
  host: redis  # Referring to the redis service by its name
  port: 6379
  password: $REDIS_PASSWORD
```

**Serverpod versions**
SERVERPOD version: 2.0.1, dart: 3.2.5 (stable)

**Platform information**
Linux running ubuntu latest distribution
