### ISSUE TITLE
File uploading through List<int> bytes throws an error while uploading larger files

### ISSUE THREAD

**Issue by Danyal-noorani** [serverpod/serverpod#2493]
While trying to upload larger files through byte arrays serverpod throws a Null value error

**To Reproduce**
Frontend File:
```
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:asibackend_client/asibackend_client.dart';
import 'dart:io';
import 'dart:typed_data';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              FilePickerResult? result =
                  await FilePicker.platform.pickFiles(type: FileType.any);

              if (result != null) {
                PlatformFile file = result.files.first;

                // You can directly upload the bytes
                Uint8List bytes = file.bytes!;
                // Create an instance of your client
                var client = Client('http://192.168.0.103:8080/');
                client.connectionTimeout = Duration(seconds: 200);
                print(file.size);

                try {
                  await client.companyEndpoints.fileUploader(
                      'Location', 'monument', file.name, file.bytes);
                  print('File uploaded successfully');
                } catch (e) {
                  print('File upload failed: $e');
                }
                // var desc = await client.companyEndpoints
                //     .getUploadDescription("storage/${file.name}");
                // var uploader = FileUploader(desc!);

                // await uploader.uploadByteData(file.bytes!.buffer.asByteData());
              }
            },
            child: Text('Upload File'),
          ),
        ),
      ),
    );
  }
}
```
Backend Endpoint method:
```
  Future<String?> fileUploader(Session session, String location,
      String monument, String fileName, List<int>? bytes) async {
    try {
      var path = "storage/$location/$monument/$fileName";
      var file = io.File(path);
      await file.writeAsBytes(bytes!);

      return path; // Return whatever response is needed
    } catch (e, stackTrace) {
      print('Error uploading file: $e');
      print(stackTrace);
      throw Exception('Failed to upload file: $e');
    }
  }
```

**Expected behavior**
Client Error:
```
File upload failed: ServerpodClientException: Unknown server response code. (ClientException: XMLHttpRequest error., uri=http://192.168.0.103:8080/companyEndpoints), statusCode = -1
```

Server Error:
```
2024-07-16 10:22:26.496641Z Internal server error. Zoned exception.
Null check operator used on a null value
#0      Server._handleRequest (package:serverpod/src/server/server.dart:296:48)
<asynchronous suspension>
```

development.yaml

```
# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.
#
# When running your server locally, the server ports are the same as the public
# facing ports.

# Configuration for the main API server.
maxRequestSize: 1048576
timeout: 200

apiServer:
  port: 8080
  publicHost: 192.168.0.103
  publicPort: 8080
  publicScheme: http

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http

# This is the database setup for your server.
database:
  host: localhost
  port: 8090
  name: asibackend
  user: postgres

# This is the setup for Redis.
redis:
  enabled: false
  host: localhost
  port: 8091

```

**Serverpod versions**
Serverpod version: 2.0.2
serverpod_auth_server: 2.0.2
serverpod_flutter: 2.0.2
file_picker: ^8.0.6
http: ^1.2.1

Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (6 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Platform information**
Windows 11 home build 22631.3810
IDE : VSC

**Additional context**
this issue is currently being tested on the web deployment of Flutter , mobile deplyment has yet to be tested
The issue is that its not a Null check problem as the file uploading works for smaller files, from my testing the issue starts somewhere between 265KB-270KB files , under 265KB uploading works perfectly , even if I pick a larger file and then only send the first few bytes it works further proving that the file isnt returning a null value 

In theory this should work as my maxRequestSize is more than the  file size and I have also provided timeout buffer, are there any other methods currently to upload files directly to the server machine with serverpod or any other alternatives to achieve the same goal
