### ISSUE TITLE
Logging events in stream interface

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#2563]
# Feature

Log each incoming event on each stream in the new streaming interface, similar to how the old interface / logging worked.

We need at least one new table for these logs.

A new log message table.

```yaml
class: StreamMessageEntry
table: serverpod_stream_message_entry
fields:
   endpoint: String
   method: String
   stream: String
   sessionLogId: int, relation(parent=serverpod_session_log),
   serverId: String
   order: int
   # Maybe? but it cannot be linked with a query log because of the async nature of the stream
   #messageId: int
```

Create an entry on each message that is published to the stream.

Optionally we can create another table to track each stream as a parent for the stream message entry and have metadata on each stream param (if we have the need!).
