### ISSUE TITLE
Can't apply migration with bidirectional 1:n relation

### ISSUE THREAD

**Issue by estevez-dev** [serverpod/serverpod#2587]
**Describe the bug**
I declared two models with bidirectional one-to-many relations containing referential actions. I have no migration and my database is clean, meaning it is the first container start after `docker compose down -v `. I made a migration for DB and can't apply that migration. I'm getting:
```
Failed to apply migration 20240810073801476.
DatabaseException: data type json has no default operator class for access method "btree"
Failed to apply database migrations. DatabaseException: data type json has no default operator class for access method "btree"
Failed to load runtime settings. DatabaseException: relation "serverpod_runtime_settings" does not exist
Failed to store runtime settings. DatabaseException: relation "serverpod_runtime_settings" does not exist
Insights listening on port 8081
Server default listening on port 8080
Webserver listening on port 8082
2024-08-10 07:38:22.305501Z Internal server error. Failed to connect to database in future call manager.
DatabaseException: relation "serverpod_future_call" does not exist
#0      DatabaseConnection._query (package:serverpod/src/database/adapters/postgres/database_connection.dart:404:9)
<asynchronous suspension>
#1      DatabaseConnection._mappedResultsQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:458:18)
<asynchronous suspension>
#2      DatabaseConnection._deserializedMappedQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:476:18)
<asynchronous suspension>
#3      DatabaseConnection.deleteWhere (package:serverpod/src/database/adapters/postgres/database_connection.dart:288:12)
<asynchronous suspension>
#4      FutureCallManager._checkQueue (package:serverpod/src/server/future_call_manager.dart:107:18)
<asynchronous suspension>

Local stacktrace:
#0      FutureCallManager._checkQueue (package:serverpod/src/server/future_call_manager.dart:145:36)
<asynchronous suspension>
```

**To Reproduce**
1. Create two models with bidirectional one-to-many relations containing referential actions, and one enum:
```yaml
# article.spy.yaml
class: Article
table: articles
fields:
    name: String
    orderVariants: List<ArticleOrderVariant>?, relation(name=article_variants)
    images: List<String>
    slug: String
    shortDescription: String
    categories: List<String>
    longDescription: String
indexes:
    article_slug_index:
        fields: slug
        unique: true
    article_categories_index:
        fields: categories

#article_order_varian.spy.yaml
class: ArticleOrderVariant
table: article_order_variants
fields:
  contentUnits: ContentUnit
  contentUnitsPerOrder: double
  price: double
  articleId: int, relation(name=article_variants, parent=articles, onUpdate=NoAction, onDelete=Cascade)
indexes:
  price_index:
    fields: price

#content_unit.spy.yaml
enum: ContentUnit
serialized: byName
values:
 - pice
 - kg
```
3. Ensure you have no migrations in the `migrations` directory.
4. Make sure the database is brand new running `docker compose down -v`
5. Generate code with `serverpod generate`
6. Start the database container with `docker compose up --build --detach`
7. Create migration with `serverpod create-migration`
8. Try to apply migration with `dart run bin/main.dart --apply-migrations`
9. See the output in console

**Expected behavior**
Migration applied succesfully

**Serverpod versions**
 -  _CLI Version:_ 2.0.2
 - _Library version:_ 2.0.2

**Platform information**
M2 Macbook with MacOS Sonoma 14.5. Docker Desktop 4.33.0
