### ISSUE TITLE
Serverpod generate fails after upgrade to Dart 3.5.0

### ISSUE THREAD

**Issue by qiqetes** [serverpod/serverpod#2591]
**Describe the bug**
```
Information about the latest pub run.

If you believe something is not working right, you can go to
https://github.com/dart-lang/pub/issues/new to post a new issue and attach this file.

Before making this file public, make sure to remove any sensitive information!

Pub version: 3.5.0
Created: 2024-08-12T11:59:13.380873
FLUTTER_ROOT: /Users/enriquellopis/development/flutter
PUB_HOSTED_URL: <not set>
PUB_CACHE: "<not set>"
Command: dart pub -v global run 'serverpod_cli:serverpod_cli' generate
Platform: macos

---- /Users/enriquellopis/dev/spod/spod_server/pubspec.yaml ----
name: spod_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod: ^2.0.2
  serverpod_auth_server: ^2.0.2

dev_dependencies:
  lints: ^4.0.0

---- End pubspec.yaml ----
---- /Users/enriquellopis/dev/spod/spod_server/pubspec.lock ----
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  _discoveryapis_commons:
    dependency: transitive
    description:
      name: _discoveryapis_commons
      sha256: "113c4100b90a5b70a983541782431b82168b3cae166ab130649c36eb3559d498"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.7"
  archive:
    dependency: transitive
    description:
      name: archive
      sha256: cb6a278ef2dbb298455e1a713bda08524a175630ec643a242c399c932a0a1f7d
      url: "https://pub.dev"
    source: hosted
    version: "3.6.1"
  args:
    dependency: transitive
    description:
      name: args
      sha256: "7cf60b9f0cc88203c5a190b4cd62a99feea42759a7fa695010eb5de1c0b2252a"
      url: "https://pub.dev"
    source: hosted
    version: "2.5.0"
  asn1lib:
    dependency: transitive
    description:
      name: asn1lib
      sha256: "58082b3f0dca697204dbab0ef9ff208bfaea7767ea771076af9a343488428dda"
      url: "https://pub.dev"
    source: hosted
    version: "1.5.3"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  buffer:
    dependency: transitive
    description:
      name: buffer
      sha256: "389da2ec2c16283c8787e0adaede82b1842102f8c8aae2f49003a766c5c6b3d1"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.3"
  charcode:
    dependency: transitive
    description:
      name: charcode
      sha256: fb98c0f6d12c920a02ee2d998da788bca066ca5f148492b7085ee23372b12306
      url: "https://pub.dev"
    source: hosted
    version: "1.3.1"
  clock:
    dependency: transitive
    description:
      name: clock
      sha256: cb6d7f03e1de671e34607e909a7213e31d7752be4fb66a86d29fe1eb14bfb5cf
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: a1ace0a119f20aabc852d165077c036cd864315bd99b7eaa10a60100341941bf
      url: "https://pub.dev"
    source: hosted
    version: "1.19.0"
  convert:
    dependency: transitive
    description:
      name: convert
      sha256: "0f08b14755d163f6e2134cb58222dd25ea2a2ee8a195[...]ources:
    dependency: transitive
    description:
      name: system_resources
      sha256: "7e78cf8ef224c1e0b6bf4462322b6739fea2274fef928cbcbf21ae5e5a8272d8"
      url: "https://pub.dev"
    source: hosted
    version: "1.6.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: "664d3a9a64782fcdeb83ce9c6b39e78fd2971d4e37827b9b06c3aa1edc5e760c"
      url: "https://pub.dev"
    source: hosted
    version: "0.7.3"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      sha256: facc8d6582f16042dd49f2463ff1bd6e2c9ef9f3d5da3d9b087e244a7b564b3c
      url: "https://pub.dev"
    source: hosted
    version: "1.3.2"
  unorm_dart:
    dependency: transitive
    description:
      name: unorm_dart
      sha256: "23d8bf65605401a6a32cff99435fed66ef3dab3ddcad3454059165df46496a3b"
      url: "https://pub.dev"
    source: hosted
    version: "0.3.0"
  uuid:
    dependency: transitive
    description:
      name: uuid
      sha256: "83d37c7ad7aaf9aa8e275490669535c8080377cfa7a7004c24dfac53afffaa90"
      url: "https://pub.dev"
    source: hosted
    version: "4.4.2"
  vm_service:
    dependency: transitive
    description:
      name: vm_service
      sha256: f652077d0bdf60abe4c1f6377448e8655008eef28f128bc023f7b5e8dfeb48fc
      url: "https://pub.dev"
    source: hosted
    version: "14.2.4"
  web:
    dependency: transitive
    description:
      name: web
      sha256: d43c1d6b787bf0afad444700ae7f4db8827f701bc61c255ac8d328c6f4d52062
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  x509:
    dependency: transitive
    description:
      name: x509
      sha256: "3262dc9a7d45b0876f886c01bfc7d5e765704f7dfd31f8cf5224fc875c17a6c6"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.4+2"
  xml:
    dependency: transitive
    description:
      name: xml
      sha256: b015a8ad1c488f66851d762d3090a21c600e479dc75e68328c52774040cf9226
      url: "https://pub.dev"
    source: hosted
    version: "6.5.0"
  yaml:
    dependency: transitive
    description:
      name: yaml
      sha256: "75769501ea3489fca56601ff33454fe45507ea3bfb014161abc3b43ae25989d5"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.2"
sdks:
  dart: ">=3.4.0 <4.0.0"

---- End pubspec.lock ----
---- Log transcript ----
FINE: Pub 3.5.0
FINE: Package Config up to date.
MSG : Building package executable...
IO  : Created temp directory /Users/enriquellopis/.pub-cache/global_packages/serverpod_cli/bin/tmpVczNeP
IO  : Copying "/Users/enriquellopis/.pub-cache/global_packages/serverpod_cli/bin/serverpod_cli.dart-3.5.0.snapshot.incremental" to "/Users/enriquellopis/.pub-cache/global_packages/serverpod_cli/bin/tmpVczNeP/serverpod_cli.dart-3.5.0.snapshot.incremental.temp".
IO  : Renaming "/Users/enriquellopis/.pub-cache/global_packages/serverpod_cli/bin/tmpVczNeP/serverpod_cli.dart-3.5.0.snapshot.incremental.temp" to "/Users/enriquellopis/.pub-cache/global_packages/serverpod_cli/bin/serverpod_cli.dart-3.5.0.snapshot.incremental".
IO  : Deleting directory /Users/enriquellopis/.pub-cache/global_packages/serverpod_cli/bin/tmpVczNeP.
ERR : [33mFailed to build [1mserverpod_cli:serverpod_cli[0m[33m:
    | [39m../../../.pub-cache/hosted/pub.dev/archive-3.4.10/lib/src/bzip2/bzip2.dart:5:7: Error: Method not found: 'UnmodifiableUint8ListView'.
    |       UnmodifiableUint8ListView(Uint8List(0));
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^
    | ../../../.pub-cache/hosted/pub.dev/archive-3.4.10/lib/src/bzip2/bzip2.dart:7:7: Error: Method not found: 'UnmodifiableUint32ListView'.
    |       UnmodifiableUint32ListView(Uint32List(0));
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^
    | ../../../.pub-cache/hosted/pub.dev/archive-3.4.10/lib/src/bzip2/bzip2.dart:9:7: Error: Method not found: 'UnmodifiableInt32ListView'.
    |       UnmodifiableInt32ListView(Int32List(0));
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^
FINE: Exception type: ApplicationException
FINE: package:pub/src/dart.dart 186:7                                  precompile
    | ===== asynchronous gap ===========================
    | dart:async                                                       Future.catchError
    | package:pub/src/utils.dart 178:21                                waitAndPrintErrors.<fn>
    | dart:async                                                       Future.wait
    | package:pub/src/utils.dart 176:17                                waitAndPrintErrors
    | package:pub/src/entrypoint.dart 677:14                           Entrypoint.precompileExecutable.<fn>
    | package:pub/src/log.dart 450:18                                  progress
    | package:pub/src/entrypoint.dart 675:15                           Entrypoint.precompileExecutable
    | package:pub/src/command/global_run.dart 85:32                    GlobalRunCommand.runProtected.<fn>.<fn>
    | package:pub/src/log.dart 433:32                                  errorsOnlyUnlessTerminal
    | package:pub/src/command/global_run.dart 84:38                    GlobalRunCommand.runProtected.<fn>
    | package:pub/src/global_packages.dart 452:24                      GlobalPackages.runExecutable.<fn>
    | package:pub/src/executable.dart 104:22                           runExecutable
    | ===== asynchronous gap ===========================
    | dart:async                                                       _CustomZone.registerUnaryCallback
    | package:pub/src/executable.dart 97:5                             runExecutable
    | package:pub/src/global_packages.dart 446:23                      GlobalPackages.runExecutable
    | package:pub/src/command/global_run.dart 77:36                    GlobalRunCommand.runProtected
    | ===== asynchronous gap ===========================
    | dart:async                                                       _CustomZone.registerUnaryCallback
    | package:pub/src/command/global_run.dart 76:30                    GlobalRunCommand.runProtected
    | package:pub/src/command.dart 197:21                              PubCommand.run.<fn>
    | dart:async                                                       new Future.sync
    | package:pub/src/utils.dart 137:12                                captureErrors.wrappedCallback
    | package:stack_trace                                              Chain.capture
    | package:pub/src/utils.dart 154:11                                captureErrors
    | package:pub/src/command.dart 196:13                              PubCommand.run
    | package:args/command_runner.dart 212:27                          CommandRunner.runCommand
    | package:dartdev/dartdev.dart 236:30                              DartdevRunner.runCommand
    | package:args/command_runner.dart 122:25                          CommandRunner.run.<fn>
    | dart:async                                                       new Future.sync
    | package:args/command_runner.dart 122:14                          CommandRunner.run
    | package:dartdev/dartdev.dart 47:29                               runDartdev
    | /Volumes/Work/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 13:11  main
FINE: Building package executable finished (0.983s).
---- End log transcript ----
```
I think it has to do with some dependency that has **win32** as dependency was not updated.
**To Reproduce**
Upgrade to last flutter, dart gets updated to 3.5.0. Run `serverpod generate` in the proyect_server folder.

**Expected behavior**
Generates the files.

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_ Run `serverpod version` to determine the version of installed tooling.
 - _Library version:_ Check the pubspec.yaml file for the version of Serverpod you are using.

**Platform information**
On which platforms do you experience the issue. Please provide as much information here as you can. Where are you running the server, which front end device are you using?

**Additional context**
