### ISSUE TITLE
Production Profile with default data in Dockerfile

### ISSUE THREAD

**Issue by FantaMagier** [serverpod/serverpod#2642]
**Describe the bug**
Hey, I am using a Dockerfile like this but the production profile is not used from Serverpod. In the App Folder the production.yaml is visible with the values.

```Dockerfile
# Stage 1: Build the server application
FROM --platform=$BUILDPLATFORM dart:3.5.0 AS build

# Resolve app dependencies.
WORKDIR /app
COPY server /app

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

# Stage 2: Create the final Docker image
FROM debian:buster-slim

# Set environment variables
ENV runmode=production
ENV serverid=default
ENV logging=verbose
ENV role=monolith

# Copy the built artifacts from the previous stage
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ /app/config/
COPY --from=build /app/web/ /app/web/
COPY --from=build /app/migrations/ /app/migrations/

# Copy passwords file
COPY ./intolerapp_server/config/passwords.yaml /app/config/passwords.yaml

# Expose ports
EXPOSE 8083
EXPOSE 8084
EXPOSE 8085

# Define the command to run the server application
CMD /app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role --apply-migrations 
```

My production yaml which is also visible in the Docker Container:

```yaml
# Configuration for the main API server.
apiServer:
  port: 8083
  publicHost: api.xy.tools.xy.de
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8084
  publicHost: insights.xy.tools.xy.de
  publicPort: 443
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8085
  publicHost: app.xy.tools.xy.de
  publicPort: 443
  publicScheme: https

```
```bash
2024-08-20T12:17:50.661668356Z mode: production, role: monolith, logging: verbose, serverId: default
2024-08-20T12:17:50.661670971Z api port: 8080
2024-08-20T12:17:50.661673445Z api public host: localhost
2024-08-20T12:17:50.661675810Z api public port: 8080
2024-08-20T12:17:50.661678435Z api public scheme: http
```

**Expected behavior**
The Server should start with wanted Ports 8083 instead of 8080 and the url instead of localhost

**Serverpod versions**
 -  _CLI Version:_ 2.0.2
 - _Library version:_   serverpod: 2.0.2

**Platform information**
On my VPS and Docker Desktop

**Comment by SandPod** [comment]
Hey @FantaMagier!

Are you sure the `production.yaml` file is accessible in the container on the correct path?
If the config yaml can't be loaded, the instance will use the default values written mentioned:
https://github.com/serverpod/serverpod/blob/f1d65ebf578095ddcead0d352e402840bfb625ba/packages/serverpod_shared/lib/src/config.dart#L156-L170

If so, did you rebuild the Dockerfile once your project was done? If you inspect the `production.yaml` file in the container, does it match the one you have defined locally?

**Comment by FantaMagier** [comment]
Hey @SandPod 

Thanks for your reply. The production.yaml in the app folder is the same one I used locally. I tested the docker image offline and copied the app folder from the container to my local folder and launched the project manually and everything works as expected. Only using the dockerfile does not work. 

I am using its GitHub actions code: https://medium.com/@ben.auer.dev/flashlist-part-6-how-i-deployed-serverpod-to-a-vps-cad6a9f6c1df

I save everything and run Serverpod generate und push the files to my git repo and the action builds the image.

**Comment by SandPod** [comment]
@BenAuerDev Do recognize any issues with this?

**Comment by BenAuerDev** [comment]
> @BenAuerDev Do recognize any issues with this?

I think the issue is related to the SSL/HTTPS configuration.

@FantaMagier Can you show me the part in your docker-compose.yaml that configures Traefik to handle SSL/HTTPS? 

**But please remove any sensitive information first**


If you're using Traefik, it should look something like:

```
  flashlist-api:
    image: ghcr.io/benauerdev/flashlist:latest
    container_name: flashlist-api
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    labels:
      - "traefik.enable=true"

      # For API
      - "traefik.http.routers.myapi.entrypoints=websecure"
      - "traefik.http.routers.myapi.rule=Host(`api.flashlistapp.com`)"
      - "traefik.http.routers.myapi.tls=true"
      - "traefik.http.routers.myapi.tls.certresolver=myresolver"
      - "traefik.http.services.myapi.loadbalancer.server.port=8080"

      # For Insights
      - "traefik.http.routers.myapi.entrypoints=websecure"
      - "traefik.http.routers.myapi.rule=Host(`insights.flashlistapp.com`)"
      - "traefik.http.routers.myapi.tls=true"
      - "traefik.http.routers.myapi.tls.certresolver=myresolver"
      - "traefik.http.services.myapi.loadbalancer.server.port=8081"

      # For Webserver
      - "traefik.http.routers.myapi.entrypoints=websecure"
      - "traefik.http.routers.myapi.rule=Host(`app.flashlistapp.com`)"
      - "traefik.http.routers.myapi.tls=true"
      - "traefik.http.routers.myapi.tls.certresolver=myresolver"
      - "traefik.http.services.myapi.loadbalancer.server.port=8082"
```

and


```
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # uncomment this line to test ssl generation first
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" 
      - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web
```

**Comment by FantaMagier** [comment]
Hey @BenAuerDev, thanks for your reply. I want to try Coolify for deployment because you can add Postgres and Redis easily.

My Traefik Conf for the Coolify Serverpod Container is: 
```
traefik.enable=true
traefik.http.middlewares.gzip.compress=true
traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
traefik.http.routers.http-0-coolifyContainerID.entryPoints=http
traefik.http.routers.http-0-coolifyContainerID.middlewares=redirect-to-https
traefik.http.routers.http-0-coolifyContainerID.rule=Host(`api.backend.url.com`) && PathPrefix(`/`)
traefik.http.routers.http-0-coolifyContainerID.service=http-0-coolifyContainerID
traefik.http.routers.http-1-coolifyContainerID.entryPoints=http
traefik.http.routers.http-1-coolifyContainerID.middlewares=redirect-to-https
traefik.http.routers.http-1-coolifyContainerID.rule=Host(`insights.backend.url.com`) && PathPrefix(`/`)
traefik.http.routers.http-1-coolifyContainerID.service=http-1-coolifyContainerID
traefik.http.routers.http-2-coolifyContainerID.entryPoints=http
traefik.http.routers.http-2-coolifyContainerID.middlewares=redirect-to-https
traefik.http.routers.http-2-coolifyContainerID.rule=Host(`app.backend.url.com`) && PathPrefix(`/`)
traefik.http.routers.http-2-coolifyContainerID.service=http-2-coolifyContainerID
traefik.http.routers.https-0-coolifyContainerID.entryPoints=https
traefik.http.routers.https-0-coolifyContainerID.middlewares=gzip
traefik.http.routers.https-0-coolifyContainerID.rule=Host(`api.backend.url.com`) && PathPrefix(`/`)
traefik.http.routers.https-0-coolifyContainerID.service=https-0-coolifyContainerID
traefik.http.routers.https-0-coolifyContainerID.tls.certresolver=letsencrypt
traefik.http.routers.https-0-coolifyContainerID.tls=true
traefik.http.routers.https-1-coolifyContainerID.entryPoints=https
traefik.http.routers.https-1-coolifyContainerID.middlewares=gzip
traefik.http.routers.https-1-coolifyContainerID.rule=Host(`insights.backend.url.com`) && PathPrefix(`/`)
traefik.http.routers.https-1-coolifyContainerID.service=https-1-coolifyContainerID
traefik.http.routers.https-1-coolifyContainerID.tls.certresolver=letsencrypt
traefik.http.routers.https-1-coolifyContainerID.tls=true
traefik.http.routers.https-2-coolifyContainerID.entryPoints=https
traefik.http.routers.https-2-coolifyContainerID.middlewares=gzip
traefik.http.routers.https-2-coolifyContainerID.rule=Host(`app.backend.url.com`) && PathPrefix(`/`)
traefik.http.routers.https-2-coolifyContainerID.service=https-2-coolifyContainerID
traefik.http.routers.https-2-coolifyContainerID.tls.certresolver=letsencrypt
traefik.http.routers.https-2-coolifyContainerID.tls=true
traefik.http.services.http-0-coolifyContainerID.loadbalancer.server.port=8083
traefik.http.services.http-1-coolifyContainerID.loadbalancer.server.port=8084
traefik.http.services.http-2-coolifyContainerID.loadbalancer.server.port=8085
traefik.http.services.https-0-coolifyContainerID.loadbalancer.server.port=8083
traefik.http.services.https-1-coolifyContainerID.loadbalancer.server.port=8084
traefik.http.services.https-2-coolifyContainerID.loadbalancer.server.port=8085
caddy_0.encode=zstd gzip
caddy_0.handle_path.0_reverse_proxy={{upstreams 8083}}
caddy_0.handle_path=/*
caddy_0.header=-Server
caddy_0.try_files={path} /index.html /index.php
caddy_0=https://api.backend.url.com
caddy_1.encode=zstd gzip
caddy_1.handle_path.1_reverse_proxy={{upstreams 8084}}
caddy_1.handle_path=/*
caddy_1.header=-Server
caddy_1.try_files={path} /index.html /index.php
caddy_1=https://insights.backend.url.com
caddy_2.encode=zstd gzip
caddy_2.handle_path.2_reverse_proxy={{upstreams 8085}}
caddy_2.handle_path=/*
caddy_2.header=-Server
caddy_2.try_files={path} /index.html /index.php
caddy_2=https://app.backend.url.com
caddy_ingress_network=coolify
```

I am using 8083,8084,8085 as port expose and for the domains https://api.backend.url.com:8083,https://insights.backend.url.com:8084,https://app.backend.url.com:8085

When I open a site I get a Bad Gateway Error but it is werid because running my Serverpod project locally in production the sever connects to the DB etc and uses the production conf but not with the Dockerimage / file.

**Comment by BenAuerDev** [comment]
@FantaMagier Unfortunately I have never used coolify. But I'll can take a look on the weekend 😊 

Also just to be sure on top of your Dockerfile you have 

`COPY server /app`

But when you copy the password you have 

`COPY ./intolerapp_server/config/passwords.yaml /app/config/passwords.yaml`

Shouldn't it both be intolerapp_server?

**Comment by FantaMagier** [comment]
@BenAuerDev Yes that is correct in my dockerfile, I changed it for the issue :D

**Comment by BenAuerDev** [comment]
@FantaMagier I had a closer look at your Dockerfile and yaml-file, apart from the above mentioned they look good. 

I also checked the Traefik/Caddy config you provided. And I noticed that you  shared both a `Traefik` and a `Caddy` configuration. Where imho it would be better to choose one for handling SSL and routing to avoid conflicts. 

Furthermore I think you're missing this part in your `docker-compose.yaml`:

If you use `Traefik`

```yaml
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # uncomment this line to test ssl generation first
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" 
      - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web
```


If you use `Caddy` (it would look something like this)

```yaml
caddy:
  image: caddy:latest
  restart: unless-stopped
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
  networks:
    - web

volumes:
  caddy_data:
```

Without this setup, there is no container on your VPS running `Traefik` or `Caddy`. Which means the config you created is not being serviced, resulting in  `bad gateway` when trying to access the url.


Furthermore it's important to make sure there is a network that connects your Docker containers with each other, in my example I called it `web`. 

```yaml
networks:
  web:
    external: true
```
