### ISSUE TITLE
Serialize by name as default for Enums.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#2669]
> [!WARNING]  
> This is a breaking change and must be done as part of the next major release of Serverpod.

**Is your feature request related to a problem? Please describe.**
Enums, by default, should be serialized by name.
This ensures the data integrity of the database regardless if new enum values are added.

To preserve the current behavior of serializing by index, the developer will need to add a `serialized: byIndex` to their enum models:

```yaml
enum: TestEnum
serialized: byIndex
values:
  - one
  - two
  - three
```

**Additional context**
Currently, developers can choose to serilize by name by using the `serialized: byName` keyword.

```yaml
enum: TestEnum
serialized: byName
values:
  - one
  - two
  - three
```
