### ISSUE TITLE
Non-persistent data is lost when inserting a row into the database.

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#2709]
Consider the following model (from the chat module):

```yaml
### A chat message.
class: ChatMessage
table: serverpod_chat_message
fields:
  ### The channel this message was posted to.
  channel: String

  ### The body of the message.
  message: String

  ### The time when this message was posted.
  time: DateTime

  ### The user id of the sender.
  sender: int

  ### Information about the sender.
  senderInfo: module:auth:UserInfoPublic?, !persist

  ### True, if this message has been removed.
  removed: bool

  ### The client message id, used to track if a message has been delivered.
  clientMessageId: int?, !persist

  ### True if the message has been sent.
  sent: bool?, !persist

  ### List of attachments associated with this message.
  attachments: List<ChatMessageAttachment>?
indexes:
  serverpod_chat_message_channel_idx:
    fields: channel
```

We are using the following code to insert a row in the database.

```dart
var chatMessage = ChatMessage(
    channel: channel,
    message: message.message,
    time: DateTime.now(),
    sender: userInfo.id!,
    senderInfo: userInfo,
    removed: false,
    clientMessageId: message.clientMessageId,
    sent: true,
    attachments: message.attachments,
  );

chatMessage = await ChatMessage.db.insertRow(session, chatMessage);
```

The `chatMessage` returned from `insertRow` has the `userInfo` property stripped. Perhaps the expected behaviour is that `!persist` fields should be preserved?
