### ISSUE TITLE
Refactor TableRow and the way it is implemented to allow to use inheritance on Models with Database

### ISSUE THREAD

**Issue by BenAuerDev** [serverpod/serverpod#2711]
With implementing #2710 we have the option to use the `extends` keyword in a yaml-file when declaring our model.

```yaml
class: BaseClass
fields: 
  fieldOne: String
```

```yaml
class: SubClass
extends: BaseClass
fields: 
  fieldTwo: String
```

Which generates a class that can be used like:

```dart
SubClass(fieldOne: '...', fieldTwo: '...');
```

BUT this is not yet possible with classes that have a `table` property, as a class with table-property is generated extending `TableRow` 

```dart 
abstract class MyClass extends TableRow ....
```

**Describe the solution you'd like**
Change TableRow to be an interface kind of like:
```dart
abstract interface class NewTableRow {
  int? id;

  Table get table;
}
```

This way we can `implement` the TableRow instead of extending it.

```dart
abstract class SubClass extends BaseClass
    implements _i1.TableRow, _i1.ProtocolSerialization {
```

**Describe alternatives you've considered**
Allow inheritance only for data-classes but not for classes related to a database

**Additional context**
