### ISSUE TITLE
 Suggestion: Add Melos Setup in generated project for Easier Script Management

### ISSUE THREAD

**Issue by egyleader** [serverpod/serverpod#2766]
Issue Description:

First, I'd like to commend the team for the fantastic achievement of enabling both server-side and Flutter code to run using the same language. This is a major milestone!

However, I've noticed that this also introduces some workflow friction. Specifically, it becomes common to switch back and forth between folders to run scripts—whether at the beginning of a development session or to run generators, for instance.

To streamline this process, I suggest including a Melos setup in the root directory with useful scripts. This would allow developers to easily execute scripts across folders from the root directory, making development more efficient. Additionally, it would scale well if more packages or scripts were added in the future (like creating model or an endpoint ..etc ).

Proposed Solution: Add a melos.yaml file at the root with some pre-defined scripts. Here's a suggested example of what the Melos configuration could look like:

```yaml
name: mypod

packages:
  - mypod_flutter
  - mypod_server

scripts:
  dev: cd ./mypod_server && docker compose up --build --detach && dart bin/main.dart --apply-migrations && cd ..
  gen: cd ./mypod_server && serverpod generate && cd ..
  genwatch: cd ./mypod_server && serverpod generate --watch
```

also in the root folder must be a pubspec.yaml:

```yaml
name: mypod

environment:
  sdk: '>=3.3.0 <4.0.0'
dev_dependencies:
  melos: ^6.1.0
```

now the user can run all the scripts from root folder : 
```dart
///  runs the docker containers and the server with migrations 
melos run dev 
```
```dart
/// runs serverpod generate in the server folder
melos run gen 
```

```dart
/// runs serverpod generate with watch argument
melos run genwatch 
```
