### ISSUE TITLE
"Interface" model support.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#2842]
**Is your feature request related to a problem? Please describe.**
As an alternative to inheritance, there might be fields that I would like to share between different unrelated models.

A use case for this could be audit fields that standardizes the format of when a record was created or updated.

By supporting interfaces, we would enable multiple definitions of standardized fields that could be added to a model.

**Describe the solution you'd like**
Add a new model type called `interface` that can be `implemented` by other models.

The definition for an `Interface` could look like this:

```yaml
interface: AuditLog
fields:
  createdAt: Datetime, default=now
  updatedAt: Datetime, default=now
```

And then be used in `Class` model like so:

```yaml
class: MyUser
implements: AuditLog
fields:
    name: String
    age: Int
```

The fields `createdAt` and `updatedAt` are then accessible for the user.

**Additional context**
- It should be possible to implement multiple interfaces.
- SerializableExceptions should also have support for implementing interfaces.

**Comment by BenAuerDev** [comment]
I'll look into this :) 🚀

**Comment by vlidholt** [comment]
@BenAuerDev, this is awesome! 🥳

**Comment by dkbast** [comment]
It would be great if this would also allow the user to implement a Dart class interface - this would allow the user to use the objects which are passed over the wire in more scenarios without the need to map them into an object which would ducktype to the same fields.

**Comment by borutjures** [comment]
It would be nice to be able to determine where the interface fields are inserted in the database table.

```
interface: AddressInterface
fields:
  address: String
  city: String
```

```
interface: AuditLog
fields:
  createdAt: Datetime, default=now
  updatedAt: Datetime, default=now
```

```
class: MyUser
implements: PositionedInterface, AuditLog
fields:
  name: String
  _addressInterface: AddressInterface
  age: Int
  _auditLog: AuditLog
```

p.s.
The current PR already adds a great feature even without allowing to specify the exact position of the interface fields.

---

Another nice feature that extends on the above is to allow the use of the same interface more than once in the same table. This would require specifying a fields name prefix for each use.

```
class: MyUser
implements: AddressInterface
fields:
  name: String
  age: Int
  _homeAddressInterface: AddressInterface
  workAddressIsSameAsHome: Boolean
  _workAddressInterface: AddressInterface
```

In the above example the fields prefix would be determined by removing the interface name (`_`**home**`AddressInterface`).
