### ISSUE TITLE
Add stricter analyzer and linter rules regarding 'dynamic' handling

### ISSUE THREAD

**Issue by christerswahn** [serverpod/serverpod#2898]
Bug #2897 occurred in part because we silently accept dynamic-typed variables to be operated on, duck-typing style. There are analyzer and linter rules available to prevent this, and perhaps we should enable them.

The below rules can be tried:

https://dart.dev/tools/linter-rules/avoid_dynamic_calls
https://dart.dev/tools/analysis#enabling-additional-type-checks

analysis_options.yaml:
```
linter:
  rules:
    - avoid_dynamic_calls

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
```

Update - after trying the analyzer rules, these were the problem counts reported by the analyzer:

- strict-casts: true # 563 errors
- strict-inference: true # 68 warnings
- strict-raw-types: true # 271 warnings

These were all deemed low value to fix at this time.

This issue should focus on `avoid_dynamic_calls`.
