### ISSUE TITLE
Failing to create an index on an inherited field

### ISSUE THREAD

**Issue by marcelomendoncasoares** [serverpod/serverpod#3093]
**Describe the bug**
The code generator is failing to create a table class with an index that uses fields from inherited classes.

**To Reproduce**
1. Create a `base.spy.yaml` file with the contents:
```yaml
class: ExampleParent
fields:
  name: String
```

2. Create a `child.spy.yaml` file with the contents:
```yaml
class: ExampleChild
table: example_child_table
extends: ExampleParent
fields:
  age: int
indexes:
  example_index:
    fields: name
    unique: true
```

3. Run `serverpod generate --experimental-features=inheritance` to generate the models. See the error:
```shell
Found 1 issue.
Error on line 8, column 13 of lib\src\models\child.spy.yaml: The field name "name" is not added to the class or has an !persist scope.
  ╷
8 │     fields: name
  │             ^^^^
  ╵
```

**Expected behavior**
As the fields are correctly inherited to the table, it should be possible to create indexes on them. In the example above, without the index, the `name` field is present on the table as expected.

**Serverpod versions**
 -  _CLI Version:_ 2.3.0.
 - _Library version:_ 2.3.0.

**Platform information**
Running the generation code from Windows.
