### ISSUE TITLE
Serverpod CLI generate command from master throws errors when using serverOnly + one to one relation to id

### ISSUE THREAD

**Issue by obiwanzenobi** [serverpod/serverpod#3225]
### Describe the bug

After switching to cli from main branch my project no longer generates  (works fine on 2.3.1)

```
Error on line 5, column 32 of lib/src/features/comment/data/comment_data.spy.yaml: The relation with scope "serverOnly" requires the relation to be optional.
  ╷
1 │ parent=submission
  │ ^^^^^^^^^^^^^^^^^
  ╵
```

My model is a table server only with a simple one to one id relation.

`submissionId: int?, relation(parent=submission)`

Putting an issue to prevent regression

### To reproduce

Setup simple project 
add 2 simple table models
add to one of them one to one to id relation to the other, like in above description

### Expected behavior

model should generate

### Library version

Master ref: f852fd7a0637c3541cc27b94285a7b0ac4c13319
Project created using 2.3.1

### Platform information

macos

### Additional context

looks like adding "customField" - https://docs.serverpod.dev/concepts/database/relations/one-to-one#custom-foreign-key-field
workarounds this issue but it forces us to use it every time

### How experienced are you with this library?

Intermediate - Familiar with the basics or have used it in a few projects

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by SandPod** [comment]
Thank you for the report @obiwanzenobi!

For a faster debug process on this, would it be possible to supply two minimal model files that trigger the incorrect behavior?

**Comment by obiwanzenobi** [comment]
@SandPod

```yaml
# university.spy.yaml
class: University
table: university
serverOnly: true

fields:
  name: String

# user.spy.yaml
class: User
table: user
serverOnly: true

fields:
  name: String
  universityId: int?, relation(parent=university)
```
