### ISSUE TITLE
The argument type 'dynamic' can't be assigned to the parameter type 'Map<String, dynamic>'.

### ISSUE THREAD

**Issue by vanlooverenkoen** [serverpod/serverpod#3235]
### Describe the bug

When upgrading to 2.3.1 to start using the testing framework I encountered this issue.

I have `strict-casts` & `strict-raw-types` enabled. But when generating the `serverpod_test_tools.dart` it generates non strict code.

This dynamic throws the error below
```dart
import 'dart:convert';

import 'package:serverpod/serverpod.dart';

/// A test helper that serializes objects to JSON before passing it to [EndpointDispatch].
/// Used by the generated code.
dynamic testObjectToJson(dynamic object) {
  return jsonDecode(SerializationManager.encodeForProtocol(object));
}
```

![Image](https://github.com/user-attachments/assets/d7653eda-dc9b-4878-805a-011024d8c840)

### To reproduce

The analyzer

```
include: package:lints/recommended.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - "lib/src/generated/**.dart"
    - "**.g.dart"
    - "**.config.dart"
    - "**.mocks.dart"
    - "**.navigator.dart"
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - unawaited_futures

```

Make sure the `testObjectToJson` is used by creating an endpoint that uses the `testObjectToJson`
```dart
var _localCallContext = await _endpointDispatch.getMethodCallContext(
          createSessionCallback: (_) => _localUniqueSession,
          endpointPath: 'app',
          methodName: 'method',
          parameters: _i1.testObjectToJson({}), //error
          serializationManager: _serializationManager,
        )
```

### Expected behavior

The analyzer should not fail after running the generate command.

This code should be generate like this:

```
var _localCallContext = await _endpointDispatch.getMethodCallContext(
          createSessionCallback: (_) => _localUniqueSession,
          endpointPath: 'app',
          methodName: 'method',
          parameters: _i1.testObjectToJson({}) as Map<String, dynamic>,
          serializationManager: _serializationManager,
        )
```

### Library version

2.3.1

### Platform information

testing

### How experienced are you with this library?

Intermediate - Familiar with the basics or have used it in a few projects

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by vanlooverenkoen** [comment]
As a workaround I disabled strictmode when running.

```
include: package:lints/recommended.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - "lib/src/generated/**.dart"
    - "**.g.dart"
    - "**.config.dart"
    - "**.mocks.dart"
    - "**.navigator.dart"
  language:
    #strict-casts: true
    #strict-raw-types: true

linter:
  rules:
    - unawaited_futures
```

But serverpod should have support for strict mode
