### ISSUE TITLE
Generate multiple client libraries based on tags

### ISSUE THREAD

**Issue by vanlooverenkoen** [serverpod/serverpod#3253]
### Problem to Solve

Right now if you create a model, that model is exported to the client library.
You can use `serverOnly: true` to make sure it is only used on the server.

Ideally you want to have all your tables configured like this. 

I am working on this: https://github.com/serverpod/serverpod/issues/2095

And I want to have all the tables in my cms client library, but for my mobile client I don't want to tables included in there.

### Proposal

It would be really cool to have the option to generate multiple client libraries with only what we actually want to export.

Genreated only for cms
```
class: DbUser
table: app_user
generateFor:
  - cms
fields:
  id: int
  uuid: UuidValue, default=random
  name: String
```

Generated only for moiblie
```yaml
class: User
generateFor:
  - mobile
fields:
  uuid: String
  name: String
```

Generated for all clients
```yaml
class: OtherModel
fields:
  uuid: String
  name: String
```

The generator config could look like this

```
type: server

client_package_paths: 
   mobile: ../mobile_client
   cms: ../cms_client
```

### Use Case

- To only export what you want to be exported for each client
- minimize code & size

### Alternatives

Export the table always

### How experienced are you with this library?

Expert - Experienced and comfortable with using this library in complex projects

### Are you interested in working on a PR for this?

- [ ] I want to work on this
