### ISSUE TITLE
db.updateRow is setting a private field to null.

### ISSUE THREAD

**Issue by Draice** [serverpod/serverpod#3286]
### Describe the bug

I've got this method in my "zone_endpoint.dart" file:

```
/// Edits a given zone.
  Future<Zone?> editZone(
      Session session, int zoneId, String name, String description) async {
    var zone = await Zone.db.findById(session, zoneId);

    // If the zone exists, update its properties.
    if (zone != null) {
      // Preserve the realmId
      final realmId = zone.realmId;

      zone.name = name;
      zone.description = description;
      zone.realmId = realmId; // Ensure realmId is preserved

      await Zone.db.updateRow(session, zone);
    }

    return zone;
  }
```

These are my two model files:

```
class: Zone
table: zone
fields:
  name: String
  description: String
  locations: List<Location>?, relation
  combatEncounters: List<CombatEncounter>?, relation
  realmId: int?, relation(parent=realm, onDelete=Cascade)
```

and

```
class: Realm
table: realm
fields:
  name: String
  description: String
  zones: List<Zone>?, relation
  worldId: int?, relation(parent=world, onDelete=Cascade)
```

This is the before screen shot when I update the name and description of 'Zone B' to 'Zone C'
![Image](https://github.com/user-attachments/assets/c1c8981c-3c20-4411-8fca-7671c7535a36)

and after:
![Image](https://github.com/user-attachments/assets/0da9482b-e59f-4e16-b781-2b299bc597b9)

Notice that while the foreign key is preserved, there's what appears to be a private field "_realmZonesRealmId" that is getting set to null. When I restart my app, it is no longer able to fine the renamed "Zone C".

### To reproduce

1. Use the provided snippets above to create a Zone.spy and Realm.spy file. 
2. Create a zone_endpoint.dart with the method provided above
3. Call that method from a test app
4. Notice that the _realmZonesRealmId field is being set to null.

### Expected behavior

_realmZonesRealmId does not get set to null, it retains its original value.

### Library version

Serverpod 2.3.1

### Platform information

Flutter Web

### How experienced are you with this library?

Beginner - Just getting started with this library

### Are you interested in working on a PR for this?

- [ ] I want to work on this
