### ISSUE TITLE
Github Actions example

### ISSUE THREAD

**Issue by vanlooverenkoen** [serverpod/serverpod#3315]
### Summary of the issue

It would be nice to have an example of how we can validate our tests with github actions (even our serverpod tests that access the database) because we don't have access to a docker.

How should we be doing this? (Without using custom runners where we could install docker very easily)

### How experienced are you with this library?

Expert - Experienced and comfortable with using this library in complex projects

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by Isakdl** [comment]
Excellent idea, just to give you a quick hint on how you can set this up with the test tooling, this is how we do it.

Replace `my_project` with your project name, and `<password>` with the password in your `passwords.yaml` file for en runMode you are using, `test` in this case.

```yaml
on:
    pull_request:

jobs:
    integration_tests:
        name: Integration tests
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
        services:
          postgres_test:
            image: postgres:17
            ports:
              - '9090:5432'
            env:
              POSTGRES_USER: postgres
              POSTGRES_DB: my_project_test
              POSTGRES_PASSWORD: "<password>"
            volumes:
              - my_project_test_data:/var/lib/postgresql/data
          redis:
            image: redis:6.2.6
            ports:
              - '8091:6379'
              - '9091:6379'
            env:
              REDIS_REPLICATION_MODE: master
              REDIS_ARGS: "--requirepass <password>"
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Initialize
              run: dart pub get
              working-directory: "my_project/my_project_server"
            - name: Apply migrations
              run: dart bin/main.dart --apply-migrations --role maintenance
              working-directory: "my_project/my_project_server"
            - name: Run tests
              run: dart test test_integration
              working-directory: "my_project/my_project_server"
```
