### ISSUE TITLE
Project not configed in Insights

### ISSUE THREAD

**Issue by vanlooverenkoen** [serverpod/serverpod#3329]
### Describe the bug

I select my project and I can see the logs of development. 

Then I use this config for staging
```
apiServer:
  port: 8080
  publicHost: myapp.com
  publicPort: 443
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: 10.10.1.3
  publicPort: 10001
  publicScheme: http

webServer:
  port: 8082
  publicHost: myapp.com
  publicPort: 443
  publicScheme: https

database:
  host: localhost
  port: 5432
  name: my_app
  user: postgres
  requireSsl: false
```

And I get this
![Image](https://github.com/user-attachments/assets/ceab7c3f-8e03-4f51-b4e4-18a7656dd09b)

I can access the insights api
![Image](https://github.com/user-attachments/assets/be0f27e9-30b9-4817-ae13-60a194e1722d)

### To reproduce

Not sure how to reproduce it actually. Maybe it is related to my internal ip? But it is accessible in my browser.

The ip is located on hetzner, so maybe it does not take the correct dns records?

### Expected behavior

It should just work

### Library version

2.4.0

### Platform information

macOS

### How experienced are you with this library?

Expert - Experienced and comfortable with using this library in complex projects

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by SandPod** [comment]
Your configuration is pointing towards `10.10.10.3` but your printscreen shows you visiting `10.10.1.3`.
Could this be a simple typo?

**Comment by vanlooverenkoen** [comment]
@SandPod I am sorry it was a typo in the config when creating this ticket. So `10.10.1.3` is the correct ip, on my dev machine is is also set correctly in the `staging.yaml` file

But I always get `No project configured` and the project itself is then completely removed from the serverpod insights app. So I need to add it manually again, just to see the `No project configured` again. (the app does work for develop, which is all localhost)

**Comment by vanlooverenkoen** [comment]
@SandPod I found the issue:

I don't use redis so I removed it from my config. (apparently it was still in my development config)

```yaml
redis:
  enabled: false
  host: localhost
  port: 8091
```

If I add it again, and set it to `enabled: false` the insights app does work. 

Why is this? Does the insights app require redis? Can't we just fallback to enabled false?
