### ISSUE TITLE
Serverpod columns names in postgres are not is line with recommended naming conventions

### ISSUE THREAD

**Issue by Tananga** [serverpod/serverpod#3361]
### Describe the bug

Base on documentation od PostgreSQL columns should be named with snake_case but Serverpod uses camelCase which is problematic. I have a hard time to add data to columns created by Serverpod because 
https://pub.dev/packages/postgres expect all columns to be lowercase.
https://www.geeksforgeeks.org/postgresql-naming-conventions/

```
class: TaxOfficeData
table: tax_office
fields:
  name: String
  street: String
  houseNumber: String
  postalCode: String
indexes:
  tax_office_soft_deleted_idx:
    fields: softDeleted
```

![Image](https://github.com/user-attachments/assets/45c490e2-02ee-457b-a149-96390c99d713)

### To reproduce

You can create table base on this model

```
class: TaxOfficeData
table: tax_office
fields:
  name: String
  street: String
  houseNumber: String
  postalCode: String
indexes:
  tax_office_soft_deleted_idx:
    fields: softDeleted
```

### Expected behavior

I would like to use naming convention recommended by PostggreSQL 

### Library version

All

### Platform information

All

### How experienced are you with this library?

Intermediate - Familiar with the basics or have used it in a few projects

### Are you interested in working on a PR for this?

- [x] I want to work on this
