### ISSUE TITLE
Serializable classes should be searchable in the db if they serialize to Strings, ints, DateTimes etc.

### ISSUE THREAD

**Issue by marcglasberg** [serverpod/serverpod#3428]
Consider this spy file:

```yaml
class: Invite
table: invite
fields:
  email: String
  teamId: TeamId # Here!!!
```

Class `TeamId` above is serializable (implements toJson/fromJson). However, I need to search by teamId, and this doesn't work:

```
Invite.db.find(session, where: (t) => t.teamId.equals(teamId.uid));
```

In this case, you are forcing me to make the `teamId` a `String`:

```yaml
class: Invite
table: invite
fields:
  email: String
  teamId: String # Here!!!
```

I'd like to ask that serializable classes are directly searchable, as long as they serialize to Strings, ints, DateTimes etc.
