### ISSUE TITLE
Deployment on Vitual private server VPS

### ISSUE THREAD

**Issue by excellencemichel** [serverpod/serverpod#347]
Add support to deploy on VPS server (Our own server) that will be good to let client/users independant of cloud services like AWS or GCP

**Comment by vlidholt** [comment]
Serverpod can already run anywhere you can run Dart and have access to Postgres. In which form would you like to see the deployment support?

**Comment by excellencemichel** [comment]
Okay I will explore more

**Comment by excellencemichel** [comment]
In the deploy docs the are only AWS terraform deploy documentation. When I say VPS, I mean if customer has his own server where he want to deploy on, or VPS from maybe Digital Ocean other VPS what we have access with SSH.
Thank you to help us

**Comment by chanan** [comment]
@vlidholt specific direction to run on fly.io would be awesome!

**Comment by daniel-naegele** [comment]
I guess there would be a few ways to implement this:
1. Use docker compose and the possibility to connect to a remote docker daemon via SSH and deploy a docker-compose file with serverpod in it, though you would need to host your image somewhere (ghcr or something). You could also include a Postgres and Redis database, MinIO for S3 storage and even Traefik for cert management. This could be an easy way to get started fast with an opinionated way on a cheap VPS (no fear of unexpected costs as on AWS).
2. Use systemd to do the same/something similar

You could also use the then finished deployment process and Terraform to deploy it quickly to [Hetzner Cloud](Hetzner Cloud), Digitial Ocean, ... for example.

If there is something I can help with, let me know.

**Comment by excellencemichel** [comment]
Do you have any idea to combine it with reverse proxy like nginx ?

**Comment by mkoehne** [comment]
@excellencemichel Maybe this can help you:
https://medium.com/@markus_32812/host-serverpod-on-your-vps-with-ci-cd-6e1c56eaa027

**Comment by dkbast** [comment]
> I guess there would be a few ways to implement this:
> 
> 1. Use docker compose and the possibility to connect to a remote docker daemon via SSH and deploy a docker-compose file with serverpod in it, though you would need to host your image somewhere (ghcr or something). You could also include a Postgres and Redis database, MinIO for S3 storage and even Traefik for cert management. This could be an easy way to get started fast with an opinionated way on a cheap VPS (no fear of unexpected costs as on AWS).
> 2. Use systemd to do the same/something similar
> 
> You could also use the then finished deployment process and Terraform to deploy it quickly to [Hetzner Cloud](Hetzner Cloud), Digitial Ocean, ... for example.
> 
> If there is something I can help with, let me know.

I think what many devs are looking for is a "single machine" solution where you run server and database on the same vps (or raspberry pi). Bonus if there is also a backup mechanism :) 

Would you @daniel-naegele & @mkoehne be interested in pairing to build something like this? @mkoehne has already written a pretty good article, but it's missing a few pieces to make this "painless" for people coming from the app / frontend world without "any" infrastructure experience.

**Comment by mkoehne** [comment]
@dkbast Yeah I would be very interested :)

**Comment by daniel-naegele** [comment]
@dkbast Same here too

**Comment by dkbast** [comment]
A quick update, just to avoid anybody else working on this as well - @inf0rmat1x and I have been working on this and we do have a working (github) pipeline which builds a Dockerimage from the Dockerfile, publishes it to ghcr and deploys it to a VPS using docker compose and a github action. We need to do some cleanup on our end and would appreciate some guidance on how we can best contribute this upstream @vlidholt

**Comment by KristijanZic** [comment]
@dkbast when I follow your setup I get a `Bad Gateway` error on web.fairstore.app, insights.fairstore.app and api.fairstore.app

My registrar is CloudFlare and I have an A record for each of the subdomains.



<details>
  <summary>testpod_server/config/staging.yaml</summary>
  
```yaml
# This is the configuration file for your staging environment. The staging
# environment is meant to resemble the production environment as much as
# possible and may connect to production databases services and data. You use it
# for final testing before deploying the production server.
#
# Typically, you will want to route the traffic through a load balancer
# which adds SSL security through https. If you use Serverpod's standard
# Terraform scripts to deploy your server, all you need to change in
# this file is the fairstore.app domain name.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: api.fairstore.app
  # publicHost: 49.12.99.243
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: insights.fairstore.app
  # publicHost: 49.12.99.243
  publicPort: 443
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: web.fairstore.app
  # publicHost: 49.12.99.243
  publicPort: 443
  publicScheme: https

# This is the database setup for your servers. The default for the Google Cloud
# Engine Terraform configuration is to connect on a private IP address.
# If you are connecting on a public IP (e.g. on AWS or Google Cloud Run), you
# connect on the public IP of the database e.g. database-staging.fairstore.app.
database:
  host: database.private-staging.fairstore.app
  # host: 49.12.99.243
  port: 5432
  name: testpod
  user: postgres

# This is the setup for Redis. The default for the Google Cloud Engine Terraform
# configuration is to connect on a private IP address.
# If you are connecting on a public IP (e.g. on AWS or Google Cloud Run), you
# connect on the public IP of the database e.g. redis-staging.fairstore.app.
redis:
  enabled: false
  host: redis.private-staging.fairstore.app
  # host: 49.12.99.243
  port: 6379
```
</details>

<details>
  <summary>testpod_server/docker-compose-staging.yaml</summary>
  
```yaml
version: "3.7"

networks:
  # explicitly setting up a docker virutal network for the serverpod services
  # by default, a network is implicitly created for each compose file
  # this makes it easier to connect to any other docker containers,
  # i.e. when using a separate docker compose to setup grafana, prometheus, etc.
  serverpod-network:
    name: serverpod-network
    driver: bridge

services:
  traefik:
    restart: on-failure
    image: traefik:v3.0
    command:
      - "--api.dashboard=true"
      - "--log.filepath=/var/log/traefik.log"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=kristijan.zic@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.fairstore.app`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=user:<redacted>"
    depends_on:
      - postgres
      - serverpod
    networks:
      - serverpod-network

  postgres:
    restart: on-failure
    image: postgres:14.1
    labels:
      - "traefik.enable=false" # We typically don't expose databases externally via HTTP
    ports:
      - "5432:5432" # You should have a firewall in place that DOES NOT allow access from the internet on this port. However on the host machine, we need access to it.
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: testpod
      POSTGRES_PASSWORD: $DATABASE_PASSWORD_STAGING
    volumes:
      - testpod_data:/var/lib/postgresql/data
    networks:
      - serverpod-network

  serverpod:
    restart: on-failure
    image: ghcr.io/${GHCR_ORG}/testpod_server:latest
    command:
      [
        "--mode",
        "staging",
        "--server-id",
        "default",
        "--logging",
        "normal",
        "--role",
        "monolith",
        "--apply-migrations",
      ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.fairstore.app`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.service=api-service"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api-service.loadbalancer.server.port=8080"

      - "traefik.http.routers.insights.rule=Host(`insights.fairstore.app`)"
      - "traefik.http.routers.insights.entrypoints=websecure"
      - "traefik.http.routers.insights.service=insights-service"
      - "traefik.http.routers.insights.tls.certresolver=myresolver"
      - "traefik.http.services.insights-service.loadbalancer.server.port=8081"

      - "traefik.http.routers.web.rule=Host(`web.fairstore.app`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.service=web-service"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web-service.loadbalancer.server.port=8082"
    depends_on:
      - postgres
    networks:
      - serverpod-network

  whoami:
    restart: on-failure
    image: "traefik/whoami"
    container_name: "whoami-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.fairstore.app`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.service=whoami-service"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.services.whoami-service.loadbalancer.server.port=80"
    networks:
      - serverpod-network

volumes:
  testpod_data:
```
</details>

<details>
  <summary>testpod_server/Dockerfile</summary>
  
```yaml
# If you update the dart version, make sure the image is
# compatible with the busybox image.
FROM dart:3.2.5 AS build

# Accept the GITHUB_PAT and GITHUB_USER as an argument
ARG GITHUB_PAT
ARG GITHUB_USER

WORKDIR /app
COPY . .

# Conditionally configure Git to use the provided GitHub token
RUN if [ -n "$GITHUB_PAT" ] && [ -n "$GITHUB_USER" ]; then \
    echo "Configuring Git to use provided GitHub token..."; \
    # Add GitHub's public SSH key to known_hosts for security
    mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts; \
    git config --global credential.helper 'store'; \
    echo "url=https://github.com/.insteadOf git://github.com/" >> ~/.gitconfig; \
    echo "https://$GITHUB_USER:$GITHUB_PAT@github.com" > ~/.git-credentials; \
    else \
    echo "No GitHub token provided. Skipping Git configuration..."; \
    fi

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

# Create a directory for runtime dependencies
RUN mkdir /app/runtime

# If you update the busybox version, make sure the image is
# compatible with the dart image.
FROM busybox:1.36.1-glibc

# Correcting the source directory for runtime dependencies
COPY --from=build /runtime/ /
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/web/ web/
COPY --from=build /app/migrations/ migrations/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

ENTRYPOINT ["/app/bin/main"]
CMD ["--mode", "staging", "--server-id", "default", "--logging", "normal", "--role", "monolith"]

```
</details>

<details>
  <summary>.github/workflows/deployment-docker.yml</summary>
  
```yaml
# This is a workflow to deploy your Serverpod to a single machine using docker-compose. This is useful for testing and small deployments. For larger deployments, you should use the deployment-aws.yml or deployment-gcp.yml workflows.
# To reduce the workload on the machine we do not use redis in this deployment. If you want to use redis, you need to add it to the docker-compose file and the serverpod configuration.
# You need to setup the correct hostnames in the docker-compose-production file AND the serverpod configuration file.
# Before deploying this workflow, you need to set up the following secrets in your repository settings:
# GITHUB_TOKEN: A GitHub token with the repo scope
# SERVERPOD_PASSWORDS: The passwords file for the serverpod (simple copy & paste)
#
# ## Server setup ##
# on your vps / server you need to generate a keypair and add the public key to the authorized_keys file
## ssh-keygen -t rsa -b 4096
## cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
# now copy the private key and add it to the secrets in the github repository
## cat ~/.ssh/id_rsa
# SSH_PRIVATE_KEY: The private key for the SSH connection which you just 'cat'ed
# SSH_HOST: The host for the SSH connection -> IP or domain
# SSH_USER: The user for the SSH connection -> often root
# DATABASE_PASSWORD_PRODUCTION: The password for the production database

name: Deploy to docker
on:
  push:
    branches: [deployment-docker-staging]
  workflow_dispatch:
    inputs:
      target:
        description: "Target"
        required: true
        default: "staging"
        type: choice
        options:
          - "staging"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # TODO Update with your GitHub username or organization
  GHCR_ORG: "kristijanzic"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./testpod_server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create passwords file
        working-directory: testpod_server
        shell: bash
        env:
          SERVERPOD_PASSWORDS: ${{ secrets.SERVERPOD_PASSWORDS }}
        run: |
          pwd
          echo "$SERVERPOD_PASSWORDS" > config/passwords.yaml
          ls config/

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            GITHUB_PAT=${{ secrets.PAT_GITHUB }}
            GITHUB_USER=${{ secrets.PAT_USER_GITHUB }}
          context: ./testpod_server
          file: ./testpod_server/Dockerfile
          push: true
          tags: ghcr.io/${{ env.GHCR_ORG }}/testpod_server:latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm/v7, linux/arm64/v8

  deploy:
    needs: build-and-push-image
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List files in the directory
        run: ls -la ./testpod_server/

      - name: Run docker-compose
        run: |
          docker compose -f ./testpod_server/docker-compose-staging.yaml pull
          docker compose -f ./testpod_server/docker-compose-staging.yaml up -d
        env:
          DOCKER_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
          DATABASE_PASSWORD_STAGING: ${{ secrets.DATABASE_PASSWORD_STAGING }}
      - name: cleanup
        run: rm -rf ~/.ssh

```
</details>

If I go into the deployed container and execute /app/bin/main with arguments I get this error:
```sh
/app/bin # ./main --mode=staging --server-id=default --logging=normal --role=monolith --apply-migrations
SERVERPOD version: 2.0.1, dart: 3.2.5 (stable) (Tue Jan 16 15:02:13 2024 +0000) on "linux_arm64", time: 2024-06-29 22:51:58.925151Z
mode: staging, role: monolith, logging: normal, serverId: default
Unhandled exception:
Bad state: Web server is disabled, supply a web server configuration to enable this feature.
#0      Serverpod.webServer (package:serverpod/src/server/serverpod.dart:121)
#1      run (package:testpod_server/server.dart:24)
#2      main (file:///app/bin/main.dart:6)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```
And this is what I get from Serverpod Insights app for the staging:
<img width="1112" alt="Screenshot 2024-06-30 at 00 54 04" src="https://github.com/serverpod/serverpod/assets/10299892/214cfd19-f70a-4449-8fa6-058b85072a71">

Any idea as to what might be the issue?
