### ISSUE TITLE
2.6.0 many-to-many models not backwards compatible wrt id

### ISSUE THREAD

**Issue by daniel-vom** [serverpod/serverpod#3480]
### Describe the bug

After upgrading to 2.6.0 from 2.4.0 and fetching the new packages `pub get` reports following errors:

```
../../project/project_server/lib/src/generated/first.dart:113:8: Error: The field 'First.id' has type 'int?', which does not match the corresponding type, 'dynamic', in the overridden setter, 'TableRow.id'.
  int? id;
       ^
/home/flutter/.pub-cache/hosted/pub.dev/serverpod-2.6.0/lib/src/database/concepts/table.dart:13:8: Context: This is the overridden method ('id').
  T_ID id;
       ^
../../project/project_server/lib/src/generated/first_second_map.dart:55:8: Error: The field 'FirstSecondMap.id' has type 'int?', which does not match the corresponding type, 'dynamic', in the overridden setter, 'TableRow.id'.
  int? id;
       ^
/home/flutter/.pub-cache/hosted/pub.dev/serverpod-2.6.0/lib/src/database/concepts/table.dart:13:8: Context: This is the overridden method ('id').
  T_ID id;
       ^
../../project/project_server/lib/src/generated/second.dart:47:8: Error: The field 'Second.id' has type 'int?', which does not match the corresponding type, 'dynamic', in the overridden setter, 'TableRow.id'.
  int? id;
       ^
/home/flutter/.pub-cache/hosted/pub.dev/serverpod-2.6.0/lib/src/database/concepts/table.dart:13:8: Context: This is the overridden method ('id').
  T_ID id;
```

### To reproduce

1. Add a many-to-many relation as described in [Many-to-many] (https://docs.serverpod.dev/concepts/database/relations/many-to-many) with serverpod `2.4.0`
 ```yaml
class: First
table: first
fields:
    name: String,
    second: List<Second>?, relation(name=second_relation)
```

 ```yaml
class: Second
table: second
fields:
    name: String
    first: List<First>?, relation(name=first_relation)
```

```yaml
class: FirstSecondMap
table: first_second_map
fields:
  first: First?, relation(name=second_relation)
  second: Second?, relation(name=first_relation)
indexes:
  first_second_idx:
    fields: firstId, secondId
    unique: true
```
2. Generate the code
3. Update serverpod to 2.6.0 and fetch the new packages
4. See errors reported by `pub get`

### Expected behavior

There is no reports of backwards incompatibility, so I'd assume that it should had been plug and play.

### Library version

serverpod: `2.6.0` from `2.4.0`
dart: `Dart SDK version: 3.7.0 (stable) (Wed Feb 5 04:53:58 2025 -0800) on "linux_x64"`

### Platform information

`Ubuntu 25.4` running as a VS code devcontainer.

### Additional context

Regenerating the code fixes the errors.

### How experienced are you with this library?

None

### Are you interested in working on a PR for this?

- [ ] I want to work on this
