### ISSUE TITLE
Support nested entries in password configuration

### ISSUE THREAD

**Issue by tp** [serverpod/serverpod#3600]
Since we aim to namespace configuration keys per module, it'd be great to be able to nest them in the password configuration YAML file.

E.g.

```yaml
serverpod_auth_jwt:
  algorithm: HS512
  key: 'asdf…'
```

Could then be made available as `serverpod_auth_jwt.algorithm` and `serverpod_auth_jwt.key` respectively.

_Originally posted by @tp in https://github.com/serverpod/serverpod/pull/3569#discussion_r2121286570_
