### ISSUE TITLE
`create` command does not replace `projectname` in Docker Compose test services for module template projects

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#3611]
### Describe the bug

When creating a new module project using the `create` command with the `--template module` option, the generated `docker-compose.yaml` contains unreplaced `projectname` placeholders in service and volume names.

### To reproduce

1. Run `serverpod create serverpod_auth_user --template module`
2. Open `serverpod_auth_user/docker/test/docker-compose.yaml`
3. Observe the following contents:

```yaml
  POSTGRES_DB: projectname_test
  volumes:
    - projectname_test_data:/var/lib/postgresql/data
...
volumes:
  projectname_test_data:
```

These should reflect the actual project name (`serverpod_auth_user`), not `projectname`.

### Expected behavior

The `projectname` placeholder should be replaced consistently throughout the Docker Compose files, including service names, database names, and volume names.

### Library version

Serverpod CLI: 2.8.0

### Platform information

MacOs

### How experienced are you with this library?

None

### Are you interested in working on a PR for this?

- [ ] I want to work on this
