### ISSUE TITLE
Add index parameter for relation() in YAML table definitions

### ISSUE THREAD

**Issue by Alexqwesa** [serverpod/serverpod#3624]
### Add index parameter to relation() in YAML
 **Before (current usage)**

```
class: Employee
table: employee
fields:
  name: String
  company: Company?, relation(name: company_employees)
```
This setup fails to generate an index on the foreign key companyId, leading to full table scans when querying related records.

### Proposal

**Proposed Syntax**
Add an `index: true` option to the `relation(...)` modifier:

```

class: Employee
table: employee
fields:
  name: String
  company: Company?, relation(name: company_employees, index: true)
``` 

**Behind the scenes**
The system should generate the same code as if user write this:

```
indexes:
  employee_company_id_idx:
    fields: companyId
```
…without requiring a separate manual block.

### Use Case

**Benefits:**
Simplifies schema definition – no need to manually write an indexes section.

Improves performance – ensures efficient FOREIGN KEY lookups, preventing full table scans.

Enhances documentation – clarifies FK usage patterns with built-in indexing.

### Alternatives

Add to documentation - that you need to create indexes for fast lookup like this:

```
indexes:
  employee_company_id_idx:
    fields: companyId
```

### How experienced are you with this library?

None

### Are you interested in working on a PR for this?

- [ ] I want to work on this
