### ISSUE TITLE
Enum with attributes

### ISSUE THREAD

**Issue by GeorgePagounis** [serverpod/serverpod#3705]
### Summary of the issue

I see in your documentation on how I can work with enums for serialization support https://docs.serverpod.dev/concepts/models#enum.

For simple enum cases this does suffice, but  what if I want my enum to also have properties? What would my enum.spy.yaml file look like for an enum that looks like this:

```dart
enum GameEnum{
  rock(id: 1, uid: '1', text: 'Rock', description: 'A solid rock.'),
  paper(id: 2, uid: '2', text: 'Paper', description: 'A piece of paper.'),
  scissors(id: 3, uid: '3', text: 'Scissors', description: 'A pair of scissors.');

  const GameEnum({
    required this.id,
    required this.uid,
    required this.text,
    required this.description,
  });

  final int id;
  final String uid;
  final String text;
  final String description;

```

### How experienced are you with this library?

Beginner - Just getting started with this library

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by SandPod** [comment]
Hello @GeorgePagounis 👋 

This is currently not supported by our enum models.
Should we convert this to a feature request?

**Comment by freppps** [comment]
Hey @SandPod ,

Hope it's okay if I add. I definitely second this feature request for Serverpod. I'm already using enhanced enums for some objects that aren't Serverpod-generated, and I'd love to see that functionality extended to Serverpod-generated code in the future.

**Comment by FXschwartz** [comment]
@SandPod As a first iteration would it be acceptable to just support additional fields/properties on enum's? I feel like that should be fairly straight forward vs supporting custom methods on enums.

**Comment by SandPod** [comment]
@FXschwartz - How would this solution look and how would it be configured?

Feel free to sketch something out and share it here.

It would be great if you could showcase:
1. How do define these fields 
2. How the enum is would be instantiated in code
3. How this would be used
4. How we handle changes that would be breaking for the client (It is OK to have breaking changes, I just want us have this perspective in mind).

From my understanding, the critical part of this feature is to be able to define the values so that we can perform a switch statement over the possible enum options. I would like to understand how that would be captured.

**Comment by FXschwartz** [comment]
@SandPod So I was thinking of keeping it super simple which would (hopefully) keep this from making breaking changes.

> How do define these fields

Keeping inline with how we define classes in .spy.yaml files there are several options here but I think something like this would work. When defining an enum now in addition to `values` you could define `properties`. And then for each value you define the properties listed previously. It keeps the syntax consistent (default=) and is familiar with how classes are defined.
```yaml
  enum: HttpStatus
  serialized: byIndex
  properties:
    code: int
    message: String
    category: String
    retryable: bool, default=false
  values:
    - ok:
        code: 200
        message: 'OK'
        category: 'Success'
    - unauthorized:
        code: 401
        message: 'Unauthorized'
        category: 'Client Error'
```

> How the enum is would be instantiated in code

Since the properties will come from the code definition and we don't have to worry about serializing/deserializing them to/from the database that simplifies things. So as soon as our enum value is deserialized from the DB or from an API call response we would have the properties immediately accessible from that enum value.

> How this would be used

We should be able to use these just as normal dart enhanced enums once they are generated.

Given this enum
```yaml
  enum: HttpStatus
  serialized: byIndex
  properties:
    code: int
    message: String
    category: String
    retryable: bool, default=false
  values:
    - ok:
        code: 200
        message: 'OK'
        category: 'Success'
    - unauthorized:
        code: 401
        message: 'Unauthorized'
        category: 'Client Error'
```
Once generated would look something like this
```dart
  enum HttpStatus implements SerializableModel {
    ok(
      code: 200,
      message: 'OK',
      category: 'Success',
    ),
    unauthorized(
      code: 401,
      message: 'Unauthorized',
      category: 'Client Error',
    );

    const HttpStatus({
      required this.code,
      required this.message,
      required this.category,
      this.retryable = false,
    });

    final int code;
    final String message;
    final String category;
    final bool retryable;

    static HttpStatus fromJson(int index) {
      switch (index) {
        case 0: return HttpStatus.ok;
        case 1: return HttpStatus.unauthorized;
        default:
          throw ArgumentError(
            'Value "$index" cannot be deserialized as a "HttpStatus"',
          );
      }
    }

    @override
    int toJson() => index; 

    @override
    String toString() => name;
  }
```

And could be used like this
```dart
  return switch (status) {
    HttpStatus.ok => Response(),
    HttpStatus.unauthorized => Response(),
  }
```

> How we handle changes that would be breaking for the client (It is OK to have breaking changes, I just want us have this perspective in mind).

The great thing about this is there "shouldn't" be any breaking changes from what I can see. We could even add an additional optional metadata property called "enhanced" or something to the yaml definition that would allow use when generating the enum to know if we need to create an enhanced or normal dart enum. But I think we should be able to make that decision without it by whether or not `properties` are defined.

> From my understanding, the critical part of this feature is to be able to define the values so that we can perform a switch statement over the possible enum options. I would like to understand how that would be captured.

I've only spent about an hour digging through how enums and classes are generated right now and it's definitely fairly complex. But I'm pretty confident this would not be an issue.

Take a look and let me know your feedback. Again I have only spent a short time understanding how Serverpod handles this generation so I could be way off base. But if the above makes sense and you agree with the concept then I could start making some code changes and see if I can get something working.
