### ISSUE TITLE
Add dart docs to generated files

### ISSUE THREAD

**Issue by fischerscode** [serverpod/serverpod#548]
Adding documentation specified in yaml to generated files would be cool.

Example:
```yaml
class: Foo
documentation: "Some documentation goes here."

fields:
  # Not sure if package:yaml can extract this data.
  foo: int
  bar:
    type: String
    documentation: "This approach would required changing the yaml format. Maybe allowing a short and an expanded mode would be an option."
```
