### ISSUE TITLE
Subdirectories in protocol folder produce errors with `serverpod generate`

### ISSUE THREAD

**Issue by mmider** [serverpod/serverpod#622]
**Describe the bug**
When a serialized class is defined in a subfolder of the `protocol` directory and it contains a field of the type: `List<otherSerializedClass>` or `Map<String, otherSerializedClass>`, then the command `serverpod generate` will generate a file for this class that has an incorrect import of `protocol.dart`.

**To Reproduce**
Consider the following simple example. Let's have a protocol directory with the following file structure:
```
/protocol
├─/d 
│ └─ bar.yaml
└─ foo.yaml
```
with files:
```yaml
# /protocol/d/bar.yaml
class: Bar
fields:
  friends: List<Foo>
```
and
```yaml
# /protocol/foo.yaml
class: Foo
fields:
  name: String
```
Let's run `serverpod generate`. Then, the generated folder will be populated with:
```
/generated
├─/d 
│ └─ bar.dart
├─ endpoints.dart
├─ foo.dart
└─ protocol.dart
```
Unfortunately, the `bar.dart` file will have an incorrect import: `import 'protocol.dart' as _i2;`.

Note that when we change the contents of `bar.yaml` to:
```yaml
# /protocol/d/bar.yaml
class: Bar
fields:
  friend: Foo
  friends: List<Foo>
  friendMap: Map<String, Foo>
```
and run `serverpod generate` again, then the generated file `generated/d/bar.dart` will list two imports of `protocol.dart`, one correct (will be used for references to field `friend`) and one incorrect (will be used for references to fields `friends` and `friendMap`), in particular:
```dart
// /generated/d/bar.dart
// (...)
import 'protocol.dart' as _i2;
import '../protocol.dart' as _i3;
// (...)
    return Bar(
      friend: serializationManager
          .deserialize<_i2.Foo>(jsonSerialization['friend']),
      friends: serializationManager
          .deserialize<List<_i3.Foo>>(jsonSerialization['friends']),
      friendMap: serializationManager
          .deserialize<Map<String, _i3.Foo>>(jsonSerialization['friendMap']),
    );
// (...)
  _i2.Foo friend;

  List<_i3.Foo> friends;

  Map<String, _i3.Foo> friendMap;
// (...)
```

**Expected behavior**
Correct paths to `protocol.dart` in generated files.

**Serverpod versions**
Serverpod version: 1.0.0

**Platform information**
MacOS 13.0.1 with M1 chip.
