### ISSUE TITLE
Allow full text/GIN generated PostgreSQL indexes/columns

### ISSUE THREAD

**Issue by tgrushka** [serverpod/serverpod#707]
**Is your feature request related to a problem? Please describe.**
I would like to be able to create a full text index (GIN) in PostgreSQL in my protocol class definition. Currently, `serverpod generate` gives me the following error:
```
Error on line 12, column 13 of lib/src/protocol/article.yaml: The field name "to_tsvector(lang" is not added to the class or has an api scope.
   ╷
12 │     fields: to_tsvector(lang, searchable_text)
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

**Describe the solution you'd like**
I would like to be able to specify a PGSQL function (like to_tsvector) as the "column" to index.

This is documented at: https://www.postgresql.org/docs/current/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX

In the following example, my intention is to generate the `searchable_text` column in my server API code from the title, subtitle, and body:
```yaml
class: Article
table: articles
fields:
  lang: String
  title: String
  subtitle: String?
  body: String
  searchable_text: String
indexes:
  searchable_text_idx:
    type: gin
    fields: to_tsvector(lang, searchable_text)
```

It would also be useful to be able to do something like:
```yaml
    fields: to_tsvector(lang, title || ' ' || coalesce(subtitle, '') || ' ' || body)
```

This might generate SQL like:
```sql
CREATE INDEX searchable_text_idx ON articles USING GIN (to_tsvector(lang, searchable_text));
```

And/or (perhaps a different issue entirely), perhaps be able to define a generated and stored column, like so:
```yaml
fields:
...
  searchable_text:
    sql_type: tsvector
    sql: to_tsvector(lang, title || ' ' || coalesce(subtitle, '') || ' ' || body)
    generated: true
    stored: true
```
which might generate SQL like:
```sql
ALTER TABLE articles
    ADD COLUMN searchable_text tsvector
               GENERATED ALWAYS AS (to_tsvector(lang, title || ' ' || coalesce(subtitle, '') || ' ' || body)) STORED;
```

**Describe alternatives you've considered**
I've just started using ServerPod so not sure if/how I could work around this. Is there a way to add raw SQL to database migrations?
