### ISSUE TITLE
Provide complete documentation or project sample to use Freezed as Custom Serializable objects

### ISSUE THREAD

**Issue by Lzyct** [serverpod/serverpod#858]
**Is your feature request related to a problem? Please describe.**
I am still confused about how to create Custom serializable objects with Freezed. There is no complete [documentation](https://docs.serverpod.dev/concepts/serialization#custom-serializable-objects), for example about the project structure, where we should create the classes, etc.

**Describe the solution you'd like**
Provide complete documentation or sample project which is using Freezed as Custom Serializable

**Describe alternatives you've considered**
n/a

**Additional context**
And also I've tried to create Freezed Class to look like this

### Client Package

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:serverpod_serialization/serverpod_serialization.dart';

part 'merchant.freezed.dart';
part 'merchant.g.dart';

@freezed
class Merchant with _$Merchant {
  const factory Merchant({
    String? id,
    String? name,
    String? image,
    String? address,
    String? phone,
    String? email,
    String? website,
    String? description,
    int? createdAt,
    int? updatedAt,
  }) = _Merchant;

  factory Merchant.fromJson(
          Map<String, dynamic> json, SerializationManager manager) =>
      _$MerchantFromJson(json);
}
```

### generator.yaml
```yaml
type: server

client_package_path: ../clinic_therapy_client

extraClasses:
  - project:src/shared/merchant.dart:Merchant
```

### merchant.yaml 
```
table: merchant
fields:
  name: String
  image: String
  address: String?
  phone: String?
  email: String?
  website: String?
  description: String?
  createdAt: int?
  updatedAt: int?
```

when I run this command

`serverpod generate`

I got this error 
![image](https://user-images.githubusercontent.com/1531684/235380021-99fc923f-ac24-47a0-9950-8d689aa10081.png)
