### ISSUE TITLE
`serverpod_user_info` not created

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#908]
**Describe the bug**

I have the `serverpod_auth` module declared in `generator.yaml`:

```
type: server

client_package_path: ../my_client

modules:
  serverpod_auth:
    nickname: auth
```

However when the database is created, the `serverpod_user_info` table is not created:

```
METHOD CALL: serverpod_auth.google.authenticateWithServerAuthCode duration: 702ms numQueries: 0 authenticatedUser: null
PostgreSQLSeverity.error 42P01: relation "serverpod_user_info" does not exist 
```

This has to be manually added to the database by executing the commands in `serverpod/modules/serverpod_auth/serverpod_auth_server/generated/tables.pgsql`

**Serverpod versions**
 -  _CLI Version:_ 1.0.1
 - _Library version:_ 1.0.1

**Platform information**

Linux
