### ISSUE TITLE
Please add `char` type for column

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#953]
**Is your feature request related to a problem? Please describe.**

The Postgres type `"char"` (note the quotes) is stored in only a single byte (therefore may take only a single ASCII character). 

The type `String` (or even `char(1)`) takes 2 bytes for a single-character string, and I assume has a slightly higher overhead to search or index than `"char"`. (Strings longer than 126 bytes have a 4-byte overhead.)

**Describe the solution you'd like**

It would be great if this were supported in protocol definitions, e.g.:

```yaml
class: EventAcceptance
table: event_acceptance
fields:
  eventId: int
  userId: int
  accepted: char  # <--
```

This would require some special serialization logic that throws an error if a `String` is passed in that is more than 1 byte (since Dart doesn't have a `char` type), or if that character is non-ASCII.
