### ISSUE TITLE
Error: PostgreSQLSeverity.error 42P01: relation "user" does not exist

### ISSUE THREAD

**Issue by maherjaafar** [serverpod/serverpod#955]
When I try to create a user by calling `_createUser` I get the following error: `PostgreSQLSeverity.error 42P01: relation "job" does not exist `

**To Reproduce**
Model:
```
### User model
class: User
table: user
fields:
  firstName: String
  lastName: String
```

When I call: 
```
  void _createUser() async {
    try {
      await client.user.createUser(
        User(
          firstName: 'firstName',
          lastName: 'lastName',
        ),
      );
      debugPrint('Result is success');
    } catch (e) {
      debugPrint('Error message is $e');
    }
  }
```

**Serverpod versions**
 -  _CLI Version: `1.1.1`
 - _Library version: `1.1.1`
 - OS: `MacOS Ventura 13.2.1`

**Comment by fleeser** [comment]
It seems like you did not create the tables correctly.

Make sure to run the pgsql files `example_server/generated/` folder on your database?
- `tables-serverpod.pgsql`
- `tables.pgsql`

**Comment by maherjaafar** [comment]
Thank you @fleeser for the quick answer! I already resolved it by using `Postico` as used in [Observable Flutter: Serverpod](https://www.youtube.com/watch?v=8sCxWBWhm2Y).

1. **Install Postico [Link](https://eggerapps.at/postico2/) (Optional)**
2. **Add your database:** 
Example:
- **Nickname**: `serverpod_project`
- **url**: `localhost`  **Port**: `8090`
- **user**: Check `your_project_server/docker-compose.yaml` and you will find:
```
    environment:
      POSTGRES_USER: <user_name>
      POSTGRES_DB: <project_name>
      POSTGRES_PASSWORD: "<password>"
```

3. **Go to** `tables.pgsql`
4. **Copy text** 
```
CREATE TABLE "job" (
  "id" serial,
  "title" text NOT NULL,
  "description" text NOT NULL,
  "jobLink" text NOT NULL,
  "location" text NOT NULL,
  "postedBy" text NOT NULL
);
```
6. **Paste it in Postico -> SQL Query then execute statement to create the table**
7. **Test it and it will work 🎉** 

Check this [video](https://www.youtube.com/watch?v=8sCxWBWhm2Y) **(min 46)** to learn more about the solution.
