### ISSUE TITLE
"serverpod generate" does not throw error/exception for un-existing class

### ISSUE THREAD

**Issue by pdkcoder** [serverpod/serverpod#97]
I declared a Company class (while I didn't have Employee class)

```
class: Company
table: company
fields:
  name: String
  foundedDate: DateTime
  employees: List<Employee> # Employee class was not declared yet
```

Then I ran `serverpod generate`, the command just ran successfully with no warning/error/exception.

I wonder if it's better to catch this kind of error/exception?
